package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product polardb Resouce Account
// generated by datasource_main.go2.jinja2
import (
	"encoding/json"

	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/errmsgs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func dataSourceAlibabacloudStackPolardbAccounts() *schema.Resource {
	return &schema.Resource{
		Read: dataSourceAlibabacloudStackPolardbAccountsRead,
		Schema: map[string]*schema.Schema{
			"ids": {
				Type:     schema.TypeList,
				Optional: true,
				Elem:     &schema.Schema{Type: schema.TypeString},
				Computed: true,
				ForceNew: true,
				MinItems: 1,
			},

			"account_name": {
				Type:     schema.TypeString,
				Optional: true,
			},

			"data_instance_id": {
				Type:     schema.TypeString,
				Optional: true,
			},

			"accounts": {
				Type:     schema.TypeList,
				Computed: true,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"id": {
							Type:     schema.TypeString,
							Computed: true,
						},

						"account_description": {
							Type:     schema.TypeString,
							Computed: true,
						},

						"account_name": {
							Type:     schema.TypeString,
							Computed: true,
						},

						"account_type": {
							Type:     schema.TypeString,
							Computed: true,
						},

						"data_instance_id": {
							Type:     schema.TypeString,
							Computed: true,
						},

						"database_privileges": {
							Type:     schema.TypeList,
							Computed: true,

							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{

									"account_privilege": {
										Type:     schema.TypeString,
										Computed: true,
									},

									"account_privilege_detail": {
										Type:     schema.TypeString,
										Computed: true,
									},

									"data_base_name": {
										Type:     schema.TypeString,
										Computed: true,
									},
								},
							},
						},

						"priv_exceeded": {
							Type:     schema.TypeString,
							Computed: true,
						},

						"status": {
							Type:     schema.TypeString,
							Computed: true,
						},
					},
				},
			},
		},
	}
}

func dataSourceAlibabacloudStackPolardbAccountsRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)

	request := client.NewCommonRequest("POST", "polardb", "2024-01-30", "DescribeAccounts", "")
	PolardbDescribeaccountsResponse := PolardbDescribeaccountsResponse{}
	request.QueryParams["DBInstanceId"] = d.Get("data_instance_id").(string)
	if v, ok := d.GetOk("account_name"); ok {
		request.QueryParams["AccountName"] = v.(string)
	}

	bresponse, err := client.ProcessCommonRequest(request)
	addDebug(request.GetActionName(), bresponse, request, request.QueryParams)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_polardb_account", "DescribeAccounts", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}

	err = json.Unmarshal(bresponse.GetHttpContentBytes(), &PolardbDescribeaccountsResponse)
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
			"alibabacloudstack_polardb_account", "DescribeAccounts", errmsgs.AlibabacloudStackSdkGoERROR)
	}

	var ids []string
	datas := make([]interface{}, 0)
	for _, data := range PolardbDescribeaccountsResponse.Accounts.DBInstanceAccount {
		database_privileges := make([]map[string]interface{}, 0)
		for _, data1 := range data.DatabasePrivileges.DatabasePrivilege {
			database_privileges = append(database_privileges, map[string]interface{}{
				"account_privilege":        data1.AccountPrivilege,
				"account_privilege_detail": data1.AccountPrivilegeDetail,
				"data_base_name":           data1.DBName,
			})
		}
		i := map[string]interface{}{
			"account_description": data.AccountDescription,

			"account_name": data.AccountName,

			"account_type": data.AccountType,

			"data_instance_id": data.DBInstanceId,

			"priv_exceeded": data.PrivExceeded,

			"status": data.AccountStatus,

			"database_privileges": database_privileges,
		}
		datas = append(datas, i)

		account_name := data.AccountName

		data_instance_id := data.DBInstanceId

		ids = append(ids, account_name+"_"+data_instance_id)
	}

	d.SetId(dataResourceIdHash(ids))
	if err := d.Set("accounts", datas); err != nil {
		return err
	}
	if err := d.Set("ids", ids); err != nil {
		return err
	}

	if output, ok := d.GetOk("output_file"); ok && output.(string) != "" {
		writeToFile(output.(string), datas)
	}

	return nil

}
