package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product CEN Resouce TransitRouterRouteEntry
// generated by datasource_main.go2.jinja2
import (
	"fmt"

	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/errmsgs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func dataSourceAlibabacloudStackCenTransitRouterMulticastDomainSources() *schema.Resource {
	return &schema.Resource{
		Read: dataSourceAlibabacloudStackCenTransitRouterMulticastDomainSourcesRead,
		Schema: map[string]*schema.Schema{
			"ids": {
				Type:     schema.TypeList,
				Optional: true,
				Elem:     &schema.Schema{Type: schema.TypeString},
				Computed: true,
				MinItems: 1,
			},
			"transit_router_multicast_domain_id": {
				Type:     schema.TypeString,
				Required: true,
			},
			"transit_router_attachment_id": {
				Type:     schema.TypeString,
				Optional: true,
			},
			"vswitch_id": {
				Type:     schema.TypeString,
				Optional: true,
			},

			"transit_router_multicast_groups": {
				Type:     schema.TypeList,
				Computed: true,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"id": {
							Type:     schema.TypeString,
							Computed: true,
						},
						"group_ip_address": {
							Type:     schema.TypeString,
							Computed: true,
						},
						"network_interface_id": {
							Type:     schema.TypeString,
							Computed: true,
						},
						"status": {
							Type:     schema.TypeString,
							Computed: true,
						},
						"transit_router_multicast_domain_id": {
							Type:     schema.TypeString,
							Computed: true,
						},
						"transit_router_attachment_id": {
							Type:     schema.TypeString,
							Computed: true,
						},
						"vswitch_id": {
							Type:     schema.TypeString,
							Computed: true,
						},
						"resource_type": {
							Type:     schema.TypeString,
							Computed: true,
						},
						"source_type": {
							Type:     schema.TypeString,
							Computed: true,
						},
						"resource_id": {
							Type:     schema.TypeString,
							Computed: true,
						},
						"group_source": {
							Type:     schema.TypeBool,
							Computed: true,
						},
						"group_member": {
							Type:     schema.TypeBool,
							Computed: true,
						},
					},
				},
			},
		},
	}
}

func dataSourceAlibabacloudStackCenTransitRouterMulticastDomainSourcesRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	cencen_instanceservice := CenService{client}
	transit_router_multicast_domain_id := d.Get("transit_router_multicast_domain_id").(string)
	response, err := cencen_instanceservice.DoCbnDescribeTransitRouterMuliticastDomainSourceRequest(":" + ":" + transit_router_multicast_domain_id)
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg, "alibabacloudstack_cen_transit_router_multicast_domain_sources", errmsgs.AlibabacloudStackSdkGoERROR)
	}
	idsMap := make(map[string]string)
	if v, ok := d.GetOk("ids"); ok {
		for _, vv := range v.([]interface{}) {
			if vv == nil {
				continue
			}
			idsMap[vv.(string)] = vv.(string)
		}
	}
	var ids []string
	datas := make([]interface{}, 0)
	for _, data := range response.TransitRouterMulticastGroups {
		if len(idsMap) > 0 {
			key := fmt.Sprintf("%s:%s:%s:%s", data.GroupIpAddress, data.VSwitchId, data.TransitRouterMulticastDomainId, data.NetworkInterfaceId)
			if _, ok := idsMap[key]; !ok {
				continue
			}
		}
		if vswitch, ok := d.GetOk("vswitch_id"); ok {
			if vswitch.(string) != data.VSwitchId {
				continue
			}
		}
		if transit_router_attachment_id, ok := d.GetOk("transit_router_attachment_id"); ok {
			if transit_router_attachment_id.(string) != data.TransitRouterAttachmentId {
				continue
			}
		}

		i := map[string]interface{}{
			"id":                                 fmt.Sprintf("%s:%s:%s:%s", data.GroupIpAddress, data.VSwitchId, data.TransitRouterMulticastDomainId, data.NetworkInterfaceId),
			"group_ip_address":                   data.GroupIpAddress,
			"network_interface_id":               data.NetworkInterfaceId,
			"transit_router_multicast_domain_id": data.TransitRouterMulticastDomainId,
			"status":                             data.Status,
			"transit_router_attachment_id":       data.TransitRouterAttachmentId,
			"vswitch_id":                         data.VSwitchId,
			"resource_type":                      data.ResourceType,
			"resource_id":                        data.ResourceId,
			"source_type":                        data.SourceType,
			"group_source":                       data.GroupSource,
			"group_member":                       data.GroupMember,
		}
		datas = append(datas, i)

		ids = append(ids, data.TransitRouterMulticastDomainId)
	}

	d.SetId(dataResourceIdHash(ids))
	if err := d.Set("transit_router_multicast_groups", datas); err != nil {
		return err
	}
	if err := d.Set("ids", ids); err != nil {
		return err
	}

	return nil
}
