package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product CEN Resouce CenInstance
// generated by datasource_main.go2.jinja2
import (
	"encoding/json"
	"regexp"
	"strconv"

	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/errmsgs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func dataSourceAlibabacloudStackCenCenInstances() *schema.Resource {
	return &schema.Resource{
		Read: dataSourceAlibabacloudStackCenCenInstancesRead,
		Schema: map[string]*schema.Schema{
			"ids": {
				Type:     schema.TypeList,
				Optional: true,
				Elem:     &schema.Schema{Type: schema.TypeString},
				Computed: true,
				MinItems: 1,
			},
			"name_regex": {
				Type:     schema.TypeString,
				Optional: true,
			},
			"description_regex": {
				Type:     schema.TypeString,
				Optional: true,
			},

			"cens": {
				Type:     schema.TypeList,
				Computed: true,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"id": {
							Type:     schema.TypeString,
							Computed: true,
						},

						"cen_bandwidth_package_ids": {
							Type:     schema.TypeList,
							Elem:     &schema.Schema{Type: schema.TypeString},
							Computed: true,
						},

						"cen_instance_name": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"create_time": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"description": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"protection_level": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"status": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"tags": {
							// TypeList
							Type:     schema.TypeList,
							Computed: true,

							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{

									"tag_key": {
										// TypeString
										Type:     schema.TypeString,
										Computed: true,
									},

									"tag_value": {
										// TypeString
										Type:     schema.TypeString,
										Computed: true,
									},
								},
							},
						},
					},
				},
			},
		},
	}
}

func dataSourceAlibabacloudStackCenCenInstancesRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)

	// api: Cbn - 2017-09-12 - DescribeCens
	request := client.NewCommonRequest("POST", "Cbn", "2017-09-12", "DescribeCens", "")
	CbnDescribecensResponseObj := CbnDescribecensResponse{}

	//调用request_params_handler

	if v, ok := d.GetOk("page_number"); ok {
		request.QueryParams["PageNumber"] = strconv.Itoa(v.(int))
	}

	if v, ok := d.GetOk("page_size"); ok {
		request.QueryParams["PageSize"] = strconv.Itoa(v.(int))
	}

	// tags := d.Get("tags").(map[string]interface{})
	// if tags != nil && len(tags) > 0 {
	// 	Tags := make([]map[string]string, 0, len(tags))
	// 	for k, v := range tags {
	// 		Tag := map[string]string{
	// 			"Key":   k,
	// 			"Value": v.(string),
	// 		}
	// 		Tags = append(Tags, Tag)
	// 	}
	// 	request_byte, _ := json.Marshal(Tags)
	// 	requeststring := string(request_byte)
	// 	request.QueryParams["Tags"] = requeststring
	// }

	bresponse, err := client.ProcessCommonRequest(request)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_cen_cen_instance", "DescribeCens", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}

	err = json.Unmarshal(bresponse.GetHttpContentBytes(), &CbnDescribecensResponseObj)
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
			"alibabacloudstack_cen_cen_instance", "DescribeCens", errmsgs.AlibabacloudStackSdkGoERROR)
	}

	var ids []string
	datas := make([]interface{}, 0)
	idsMap := make(map[string]string)
	if v, ok := d.GetOk("ids"); ok {
		for _, vv := range v.([]interface{}) {
			if vv == nil {
				continue
			}
			idsMap[vv.(string)] = vv.(string)
		}
	}
	for _, data := range CbnDescribecensResponseObj.Cens.Cen {

		if len(idsMap) > 0 {
			if _, ok := idsMap[data.CenId]; !ok {
				continue
			}
		}
		if descriptionRegex, ok := d.GetOk("description_regex"); ok {
			r := regexp.MustCompile(descriptionRegex.(string))
			if !r.MatchString(data.Description) {
				continue
			}
		}

		if nameRegex, ok := d.GetOk("name_regex"); ok {
			r := regexp.MustCompile(nameRegex.(string))
			if !r.MatchString(data.Name) {
				continue
			}
		}
		bandwidth_package_ids := []string{}

		for _, v := range data.CenBandwidthPackageIds.CenBandwidthPackageId {
			bandwidth_package_ids = append(bandwidth_package_ids, v)
		}
		i := map[string]interface{}{
			"id":                        data.CenId,
			"cen_instance_name":         data.Name,
			"create_time":               data.CreationTime,
			"description":               data.Description,
			"protection_level":          data.ProtectionLevel,
			"status":                    data.Status,
			"cen_bandwidth_package_ids": bandwidth_package_ids,
		}
		datas = append(datas, i)

		cen_id := data.CenId

		ids = append(ids, cen_id)
	}

	d.SetId(dataResourceIdHash(ids))
	if err := d.Set("cens", datas); err != nil {
		return err
	}
	if err := d.Set("ids", ids); err != nil {
		return err
	}

	return nil

}
