package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product POLARDB Resouce Database
// generated by datasource_main.go2.jinja2
import (
	"encoding/json"
	"fmt"
	"regexp"
	"strings"

	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/errmsgs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
)

func dataSourceAlibabacloudStackPolardbDatabases() *schema.Resource {
	return &schema.Resource{
		Read: dataSourceAlibabacloudStackPolardbDatabasesRead,
		Schema: map[string]*schema.Schema{
			"ids": {
				Type:     schema.TypeList,
				Optional: true,
				Elem:     &schema.Schema{Type: schema.TypeString},
				Computed: true,
				ForceNew: true,
				MinItems: 1,
			},

			"data_base_instance_id": {
				Type:     schema.TypeString,
				Required: true,
			},

			"data_base_name": {
				Type:     schema.TypeString,
				Optional: true,
			},

			"name_regex": {
				Type:          schema.TypeString,
				Optional:      true,
				ValidateFunc:  validation.StringIsValidRegExp,
				Deprecated:    "Field 'name_regex' is deprecated and will be removed in a future release. Please use new field 'description_regex' instead.",
				ConflictsWith: []string{"description_regex"},
			},
			"description_regex": {
				Type:          schema.TypeString,
				Optional:      true,
				ValidateFunc:  validation.StringIsValidRegExp,
				ConflictsWith: []string{"name_regex"},
			},

			"databases": {
				Type:     schema.TypeList,
				Computed: true,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"id": {
							Type:     schema.TypeString,
							Computed: true,
						},

						"accounts": {
							Type:     schema.TypeList,
							Computed: true,

							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{

									"account": {
										Type:     schema.TypeString,
										Computed: true,
									},

									"account_privilege": {
										Type:     schema.TypeString,
										Computed: true,
									},
								},
							},
						},

						"character_set_name": {
							Type:     schema.TypeString,
							Computed: true,
						},

						"data_base_description": {
							Type:     schema.TypeString,
							Computed: true,
						},

						"data_base_instance_id": {
							Type:     schema.TypeString,
							Computed: true,
						},

						"data_base_name": {
							Type:     schema.TypeString,
							Computed: true,
						},

						"engine": {
							Type:     schema.TypeString,
							Computed: true,
						},

						"page_number": {
							Type:     schema.TypeInt,
							Computed: true,
						},

						"page_size": {
							Type:     schema.TypeInt,
							Computed: true,
						},

						"status": {
							Type:     schema.TypeString,
							Computed: true,
						},
					},
				},
			},
		},
	}
}

func dataSourceAlibabacloudStackPolardbDatabasesRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)

	request := client.NewCommonRequest("POST", "polardb", "2024-01-30", "DescribeDatabases", "")
	PolardbDescribedatabasesResponse := PolardbDescribedatabasesResponse{}

	request.QueryParams["DBInstanceId"] = d.Get("data_base_instance_id").(string)

	if v, ok := d.GetOk("data_base_name"); ok {
		request.QueryParams["DBName"] = v.(string)
	}

	bresponse, err := client.ProcessCommonRequest(request)
	addDebug(request.GetActionName(), bresponse, request, request.QueryParams)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_polardb_database", "DescribeDatabases", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}

	err = json.Unmarshal(bresponse.GetHttpContentBytes(), &PolardbDescribedatabasesResponse)
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
			"alibabacloudstack_polardb_database", "DescribeDatabases", errmsgs.AlibabacloudStackSdkGoERROR)
	}
	idsMap := getIdsStringFilter(d)

	var ids []string
	datas := make([]interface{}, 0)

	for _, data := range PolardbDescribedatabasesResponse.Databases.Database {

		if description_regex, ok := connectivity.GetResourceDataOk(d, "description_regex", "name_regex"); ok {
			r := regexp.MustCompile(description_regex.(string))
			if !r.MatchString(data.DBName) {
				continue
			}
		}

		data_base_instance_id := data.DBInstanceId

		data_base_name := data.DBName

		dbid := fmt.Sprintf("%s:%s", data_base_instance_id, strings.ToLower(data_base_name))

		if len(idsMap) > 0 {
			if _, exist := idsMap[dbid]; !exist {
				continue
			}
		}

		accounts := make([]map[string]interface{}, 0)
		for _, data1 := range data.Accounts.AccountPrivilegeInfo {
			accounts = append(accounts, map[string]interface{}{
				"account":           data1.Account,
				"account_privilege": data1.AccountPrivilege,
			})
		}

		i := map[string]interface{}{

			"id": dbid,

			"character_set_name": data.CharacterSetName,

			"data_base_description": data.DBDescription,

			"data_base_instance_id": data.DBInstanceId,

			"data_base_name": data.DBName,

			"engine": data.Engine,

			"status": data.DBStatus,

			"accounts": accounts,
		}
		datas = append(datas, i)

		ids = append(ids, dbid)
	}

	d.SetId(dataResourceIdHash(ids))
	if err := d.Set("databases", datas); err != nil {
		return err
	}
	if err := d.Set("ids", ids); err != nil {
		return err
	}
	return nil
}
