package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product EBS Resouce DiskReplicaGroup
// generated by datasource_main.go2.jinja2
import (
	"encoding/json"

	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/errmsgs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func dataSourceAlibabacloudStackEbsDiskReplicaGroups() *schema.Resource {
	return &schema.Resource{
		Read: dataSourceAlibabacloudStackEbsDiskReplicaGroupsRead,
		Schema: map[string]*schema.Schema{
			"ids": {
				Type:     schema.TypeList,
				Optional: true,
				Elem:     &schema.Schema{Type: schema.TypeString},
				Computed: true,
				MinItems: 1,
			},

			"site": {
				Type:     schema.TypeString,
				Optional: true,
				Default:  "production",
			},

			"source_region_id": {
				Type:     schema.TypeString,
				Optional: true,
			},

			"output_file": {
				Type:     schema.TypeString,
				Optional: true,
			},

			"disk_replica_groups": {
				Type:     schema.TypeList,
				Computed: true,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"id": {
							Type:     schema.TypeString,
							Computed: true,
						},

						"description": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"destination_region_id": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"destination_zone_id": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"disk_replica_group_name": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"last_recover_point": {
							// TypeInt
							Type:     schema.TypeInt,
							Computed: true,
						},

						"one_shot": {
							// TypeBool
							Type:     schema.TypeBool,
							Computed: true,
						},

						"pair_ids": {
							// TypeList
							Type:     schema.TypeList,
							Computed: true,

							Elem: &schema.Schema{
								//TypeString
								Type:     schema.TypeString,
								Computed: true,
							},
						},

						"pair_number": {
							// TypeInt
							Type:     schema.TypeInt,
							Computed: true,
						},

						"rpo": {
							// TypeInt
							Type:     schema.TypeInt,
							Computed: true,
						},
						"replica_group_id": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"site": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"source_region_id": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"source_zone_id": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"status": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"tags": {
							// TypeList
							Type:     schema.TypeList,
							Computed: true,

							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{

									"tag_key": {
										// TypeString
										Type:     schema.TypeString,
										Computed: true,
									},

									"tag_value": {
										// TypeString
										Type:     schema.TypeString,
										Computed: true,
									},
								},
							},
						},
					},
				},
			},
		},
	}
}

func dataSourceAlibabacloudStackEbsDiskReplicaGroupsRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)

	// api: ebs - 2021-07-30 - DescribeDiskReplicaGroups
	request := client.NewCommonRequest("POST", "ebs", "2021-07-30", "DescribeDiskReplicaGroups", "")
	EbsDescribediskreplicagroupsResponse := EbsDescribediskreplicagroupsResponse{}
	request.QueryParams["Site"] = d.Get("site").(string)

	if v, ok := d.GetOk("source_region_id"); ok {
		request.QueryParams["RegionId"] = v.(string)
	}

	bresponse, err := client.ProcessCommonRequest(request)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_ebs_disk_replica_group", "DescribeDiskReplicaGroups", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}

	err = json.Unmarshal(bresponse.GetHttpContentBytes(), &EbsDescribediskreplicagroupsResponse)
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
			"alibabacloudstack_ebs_disk_replica_group", "DescribeDiskReplicaGroups", errmsgs.AlibabacloudStackSdkGoERROR)
	}

	var ids []string
	datas := make([]interface{}, 0)
	for _, data := range EbsDescribediskreplicagroupsResponse.ReplicaGroups {
		i := map[string]interface{}{
			"description": data.Description,

			"destination_region_id": data.DestinationRegionId,

			"destination_zone_id": data.DestinationZoneId,

			"disk_replica_group_name": data.GroupName,

			"last_recover_point": data.LastRecoverPoint,

			"pair_number": data.PairNumber,

			"rpo": data.RPO,

			"replica_group_id": data.ReplicaGroupId,

			"site": data.Site,

			"source_region_id": data.SourceRegionId,

			"source_zone_id": data.SourceZoneId,

			"status": data.Status,
		}
		datas = append(datas, i)

		replica_group_id := data.ReplicaGroupId

		ids = append(ids, replica_group_id)
	}

	d.SetId(dataResourceIdHash(ids))
	if err := d.Set("disk_replica_groups", datas); err != nil {
		return err
	}
	if err := d.Set("ids", ids); err != nil {
		return err
	}

	// create a json file in current directory and write data source to it.
	if output, ok := d.GetOk("output_file"); ok && output.(string) != "" {
		writeToFile(output.(string), datas)
	}

	return nil

}
