package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product DRDS Resouce Database
// generated by datasource_main.go2.jinja2
import (
	"encoding/json"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func dataSourceAlibabacloudStackDrdsRdsInstances() *schema.Resource {
	return &schema.Resource{
		Read: dataSourceAlibabacloudStackDrdsRdsInstancesRead,
		Schema: map[string]*schema.Schema{
			"ids": {
				Type:     schema.TypeList,
				Optional: true,
				Elem:     &schema.Schema{Type: schema.TypeString},
				Computed: true,
				ForceNew: true,
				MinItems: 1,
			},

			"drds_instance_id": {
				Type:     schema.TypeString,
				Required: true,
			},
			
			"rds_instances": {
				Type:     schema.TypeList,
				Computed: true,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{

						"db_instance_storage": {
							Type:     schema.TypeInt,
							Computed: true,
						},

						"rds_instance_id": {
							Type:     schema.TypeString,
							Computed: true,
						},

						"create_time": {
							Type:     schema.TypeString,
							Computed: true,
						},

					},
				},
			},
		},
	}
}

func dataSourceAlibabacloudStackDrdsRdsInstancesRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	drdsService := DrdsService{client}
	if _,  err := drdsService.DescribeDrdsInstance(d.Get("drds_instance_id").(string)); err != nil {
		// Need to check drds_instance_id first, return empty if not exist
		ids := []string{}
		datas := []interface{}{}
		d.SetId(dataResourceIdHash(ids))
		if err := d.Set("rds_instances", datas); err != nil {
			return err
		}
		if err := d.Set("ids", ids); err != nil {
			return err
		}
		return nil
	}
	reqQuery := map[string]interface{}{
		"DrdsInstanceId": d.Get("drds_instance_id").(string),
	}

	response, err := client.DoTeaRequest("GET", "Drds", "2019-01-23", "DescribeDrdsRdsInstances", "", nil, reqQuery, nil)
	if err != nil {
		return err
	}

	dbInstances := response["DbInstances"].(map[string]interface{})["DbInstance"].([]interface{})


	idsMap := getIdsStringFilter(d)

	datas := make([]interface{}, 0)
	ids := []string{}
	for _, d := range dbInstances{
		dbInstance := d.(map[string]interface{})
		if _, existed := idsMap[dbInstance["DBInstanceId"].(string)]; len(idsMap) > 0 && !existed {
			continue
		}
		if v, err := dbInstance["DBInstanceStatus"].(json.Number).Int64(); err != nil {
			return err
		} else {
			if int(v) < 0 || int(v) == 4 {
				// Do not show resources that are being deleted
				continue
			}
		}
		data := map[string]interface{}{
			"rds_instance_id": dbInstance["DBInstanceId"],
			"db_instance_storage": dbInstance["DBInstanceStorage"],
			"create_time": dbInstance["ExpireTime"],
		}
		datas = append(datas, data)
		ids = append(ids, dbInstance["DBInstanceId"].(string))
	}

	d.SetId(dataResourceIdHash(ids))
	if err := d.Set("rds_instances", datas); err != nil {
		return err
	}
	if err := d.Set("ids", ids); err != nil {
		return err
	}

	return nil

}
