package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product ExpressConnect Resouce VbrPconnAssociation
// generated by datasource_main.go2.jinja2
import (
	"encoding/json"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/errmsgs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"strconv"
)

func dataSourceAlibabacloudStackExpressconnectVbrPconnAssociations() *schema.Resource {
	return &schema.Resource{
		Read: dataSourceAlibabacloudStackExpressconnectVbrPconnAssociationsRead,
		Schema: map[string]*schema.Schema{
			"ids": {
				Type:     schema.TypeList,
				Optional: true,
				Elem:     &schema.Schema{Type: schema.TypeString},
				Computed: true,
				MinItems: 1,
			},

			"vbr_pconn_associations": {
				Type:     schema.TypeList,
				Computed: true,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"id": {
							Type:     schema.TypeString,
							Computed: true,
						},

						"circuit_code": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},
						"client_token": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},
						"enable_ipv6": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},
						"local_gateway_ip": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},
						"local_ipv6_gateway_ip": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},
						"peer_gateway_ip": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},
						"peer_ipv6_gateway_ip": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},
						"peering_ipv6_subnet_mask": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},
						"peering_subnet_mask": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},
						"physical_connection_id": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},
						"status": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},
						"vbr_id": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},
						"vlan_id": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},
					},
				},
			},
		},
	}
}

func dataSourceAlibabacloudStackExpressconnectVbrPconnAssociationsRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)

	// api: Vpc - 2016-04-28 - DescribeVirtualBorderRouters
	request := client.NewCommonRequest("POST", "Vpc", "2016-04-28", "DescribeVirtualBorderRouters", "")
	VpcDescribevirtualborderroutersResponseObj := VpcDescribevirtualborderroutersResponse{}

	//调用request_params_handler

	if v, ok := d.GetOk("page_number"); ok {
		request.QueryParams["PageNumber"] = strconv.Itoa(v.(int))
	}

	if v, ok := d.GetOk("page_size"); ok {
		request.QueryParams["PageSize"] = strconv.Itoa(v.(int))
	}

	request.QueryParams["RegionId"] = d.Get("region_id").(string)

	bresponse, err := client.ProcessCommonRequest(request)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_express_connect_vbr_pconn_association", "DescribeVirtualBorderRouters", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}

	err = json.Unmarshal(bresponse.GetHttpContentBytes(), &VpcDescribevirtualborderroutersResponseObj)
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
			"alibabacloudstack_express_connect_vbr_pconn_association", "DescribeVirtualBorderRouters", errmsgs.AlibabacloudStackSdkGoERROR)
	}

	var ids []string
	datas := make([]interface{}, 0)
	for _, data := range VpcDescribevirtualborderroutersResponseObj.VirtualBorderRouterSet.VirtualBorderRouterType {
		i := map[string]interface{}{
			"circuit_code": data.AssociatedPhysicalConnections.AssociatedPhysicalConnection[0].CircuitCode,
			"enable_ipv6": data.AssociatedPhysicalConnections.AssociatedPhysicalConnection[0].EnableIpv6,
			"local_gateway_ip": data.AssociatedPhysicalConnections.AssociatedPhysicalConnection[0].LocalGatewayIp,
			"local_ipv6_gateway_ip": data.AssociatedPhysicalConnections.AssociatedPhysicalConnection[0].LocalIpv6GatewayIp,
			"peer_gateway_ip": data.AssociatedPhysicalConnections.AssociatedPhysicalConnection[0].PeerGatewayIp,
			"peer_ipv6_gateway_ip": data.AssociatedPhysicalConnections.AssociatedPhysicalConnection[0].PeerIpv6GatewayIp,
			"peering_ipv6_subnet_mask": data.AssociatedPhysicalConnections.AssociatedPhysicalConnection[0].PeeringIpv6SubnetMask,
			"peering_subnet_mask": data.AssociatedPhysicalConnections.AssociatedPhysicalConnection[0].PeeringSubnetMask,
			"physical_connection_id": data.AssociatedPhysicalConnections.AssociatedPhysicalConnection[0].PhysicalConnectionId,
			"record_total": data,
			"status": data.AssociatedPhysicalConnections.AssociatedPhysicalConnection[0].Status,
			"vbr_id": data.VbrId,
			"vlan_id": data.AssociatedPhysicalConnections.AssociatedPhysicalConnection[0].VlanId,
		}
		datas = append(datas, i)

		physical_connection_id := data.AssociatedPhysicalConnections.AssociatedPhysicalConnection[0].PhysicalConnectionId

		vbr_id := data.VbrId

		ids = append(ids, physical_connection_id+"_"+vbr_id)
	}

	d.SetId(dataResourceIdHash(ids))
	if err := d.Set("vbr_pconn_associations", datas); err != nil {
		return err
	}
	if err := d.Set("ids", ids); err != nil {
		return err
	}

	return nil

}
