package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product CEN Resouce TransitRouterRouteEntry
// generated by datasource_main.go2.jinja2
import (
	"fmt"

	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/errmsgs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func dataSourceAlibabacloudStackCenTransitRouterRouterTableAssociations() *schema.Resource {
	return &schema.Resource{
		Read: dataSourceAlibabacloudStackCenTransitRouterRouterTableAssociationsRead,
		Schema: map[string]*schema.Schema{
			"ids": {
				Type:     schema.TypeList,
				Optional: true,
				Elem:     &schema.Schema{Type: schema.TypeString},
				Computed: true,
				MinItems: 1,
			},
			"transit_router_route_table_id": {
				Type:        schema.TypeString,
				Required:    true,
				Description: "ID of the route.",
			},

			"transit_router_route_associations": {
				Type:     schema.TypeList,
				Computed: true,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"id": {
							Type:     schema.TypeString,
							Computed: true,
						},
						"transit_router_attachment_id": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "The ID of the transit router attachment.",
						},
						"transit_router_route_table_id": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "The ID of the transit router route table.",
						},
						"resource_id": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "The ID of the resource.",
						},
						"resource_type": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "The type of the resource.",
						},
						"status": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "The status of the association.",
						},
					},
				},
			},
		},
	}
}

func dataSourceAlibabacloudStackCenTransitRouterRouterTableAssociationsRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	cencen_instanceservice := CenService{client}
	id := d.Get("transit_router_route_table_id").(string)
	response, err := cencen_instanceservice.DoCbnDescribeTransitRouterRouteTableAssociationsRequest(id)
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg, "alibabacloudstack_cen_transit_router_route_tables", errmsgs.AlibabacloudStackSdkGoERROR)
	}
	idsMap := getIdsStringFilter(d)
	var ids []string
	datas := make([]interface{}, 0)
	for _, data := range response.TransitRouterAssociations {
		if len(idsMap) > 0 {
			key := fmt.Sprintf("%s:%s", id, data.TransitRouterAttachmentId)
			if _, ok := idsMap[key]; !ok {
				continue
			}
		}

		i := map[string]interface{}{
			"id":                            fmt.Sprintf("%s:%s", data.TransitRouterRouteTableId, data.TransitRouterAttachmentId),
			"transit_router_attachment_id":  data.TransitRouterAttachmentId,
			"transit_router_route_table_id": data.TransitRouterRouteTableId,
			"resource_id":                   data.ResourceId,
			"resource_type":                 data.ResourceType,
			"status":                        data.Status,
		}
		datas = append(datas, i)

		ids = append(ids, fmt.Sprintf("%s:%s", data.TransitRouterRouteTableId, data.TransitRouterAttachmentId))
	}

	d.SetId(dataResourceIdHash(ids))
	if err := d.Set("transit_router_route_associations", datas); err != nil {
		return err
	}
	if err := d.Set("ids", ids); err != nil {
		return err
	}

	return nil
}
