package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product polardb Resouce Account
// generated by datasource_main.go2.jinja2
import (
	"encoding/json"
	"fmt"
	"regexp"

	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/errmsgs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
)

func dataSourceAlibabacloudStackPolardbClusterAccounts() *schema.Resource {
	return &schema.Resource{
		Read: dataSourceAlibabacloudStackPolardbClusterAccountsRead,
		Schema: map[string]*schema.Schema{
			"ids": {
				Type:     schema.TypeList,
				Optional: true,
				Elem:     &schema.Schema{Type: schema.TypeString},
				Computed: true,
				ForceNew: true,
				MinItems: 1,
			},

			"account_name": {
				Type:     schema.TypeString,
				Optional: true,
			},

			"db_cluster_id": {
				Type:     schema.TypeString,
				Required: true,
			},

			"name_regex": {
				Type:          schema.TypeString,
				Optional:      true,
				ValidateFunc:  validation.StringIsValidRegExp,
				Deprecated:    "Field 'name_regex' is deprecated and will be removed in a future release. Please use new field 'description_regex' instead.",
				ConflictsWith: []string{"description_regex"},
			},
			"description_regex": {
				Type:          schema.TypeString,
				Optional:      true,
				ValidateFunc:  validation.StringIsValidRegExp,
				ConflictsWith: []string{"name_regex"},
			},

			"accounts": {
				Type:     schema.TypeList,
				Computed: true,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"id": {
							Type:     schema.TypeString,
							Computed: true,
						},

						"account_description": {
							Type:     schema.TypeString,
							Computed: true,
						},

						"account_name": {
							Type:     schema.TypeString,
							Computed: true,
						},

						"account_type": {
							Type:     schema.TypeString,
							Computed: true,
						},

						"database_privileges": {
							Type:     schema.TypeList,
							Computed: true,

							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{

									"privilege": {
										Type:     schema.TypeString,
										Computed: true,
									},
									"db_name": {
										Type:     schema.TypeString,
										Computed: true,
									},
								},
							},
						},

						"account_lock_state": {
							Type:     schema.TypeString,
							Computed: true,
						},

						"status": {
							Type:     schema.TypeString,
							Computed: true,
						},
					},
				},
			},
		},
	}
}

func dataSourceAlibabacloudStackPolardbClusterAccountsRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	db_cluster_id := d.Get("db_cluster_id").(string)
	request := client.NewCommonRequest("GET", "polardb", "2017-08-01", "DescribeAccounts", "")
	response := make(map[string]interface{})
	request.QueryParams["DBClusterId"] = db_cluster_id

	bresponse, err := client.ProcessCommonRequest(request)
	addDebug(request.GetActionName(), bresponse, request, request.QueryParams)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_polardb_cluster_accounts", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}

	err = json.Unmarshal(bresponse.GetHttpContentBytes(), &response)
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
			"alibabacloudstack_polardb_cluster_accounts", "DescribeAccounts", errmsgs.AlibabacloudStackSdkGoERROR)
	}
	accounts, ok := response["Accounts"].([]interface{})
	if !ok {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
			"alibabacloudstack_polardb_cluster_accounts", "DescribeAccounts", errmsgs.AlibabacloudStackSdkGoERROR)
	}

	idsMap := getIdsStringFilter(d)
	var ids []string
	datas := make([]interface{}, 0)
	for _, data := range accounts {
		account := data.(map[string]interface{})

		account_name := account["AccountName"].(string)

		if v, ok := d.GetOk("account_name"); ok && v.(string) != account_name {
			continue
		}

		if description_regex, ok := connectivity.GetResourceDataOk(d, "description_regex", "name_regex"); ok {
			r := regexp.MustCompile(description_regex.(string))
			if !r.MatchString(account_name) {
				continue
			}
		}

		dbid := fmt.Sprintf("%s:%s", db_cluster_id, account_name)

		if len(idsMap) > 0 {
			if _, exist := idsMap[dbid]; !exist {
				continue
			}
		}
		dbPrivileges := account["DatabasePrivileges"].([]interface{})

		var databasePrivileges []map[string]interface{}
		for _, dbPrivilege := range dbPrivileges {
			privilege := dbPrivilege.(map[string]interface{})
			p := map[string]interface{}{
				"privilege": privilege["AccountPrivilege"],
				"db_name":   privilege["DBName"],
			}
			databasePrivileges = append(databasePrivileges, p)
		}
		i := map[string]interface{}{

			"id": dbid,

			"account_description": account["AccountDescription"],

			"account_name": account["AccountName"],

			"account_type": account["AccountType"],

			"status": account["AccountStatus"],

			"account_lock_state": account["AccountLockState"],

			"database_privileges": databasePrivileges,
		}
		datas = append(datas, i)

		ids = append(ids, dbid)
	}

	d.SetId(dataResourceIdHash(ids))
	if err := d.Set("accounts", datas); err != nil {
		return err
	}
	if err := d.Set("ids", ids); err != nil {
		return err
	}

	return nil

}
