package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product DRDS Resouce Account
// generated by datasource_main.go2.jinja2
import (
	"encoding/json"
	"fmt"

	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/errmsgs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
)

func dataSourceAlibabacloudStackDrdsAccounts() *schema.Resource {
	return &schema.Resource{
		Read: dataSourceAlibabacloudStackDrdsAccountsRead,
		Schema: map[string]*schema.Schema{
			"ids": {
				Type:     schema.TypeList,
				Elem:     &schema.Schema{Type: schema.TypeString},
				Computed: true,
			},
			"names": {
				Type:     schema.TypeList,
				Optional: true,
				Elem:     &schema.Schema{Type: schema.TypeString},
				Computed: true,
				ForceNew: true,
				MinItems: 1,
			},

			"account_type": {
				// TypeInt
				Type:         schema.TypeInt,
				Optional: true,
				Default:  -1,
				ValidateFunc: validation.IntInSlice([]int{0, 1}),
			},

			"instance_id": {
				Type:     schema.TypeString,
				Required: true,
			},

			"accounts": {
				Type:     schema.TypeList,
				Computed: true,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"id": {
							Type:     schema.TypeString,
							Computed: true,
						},

						"account_type": {
							// TypeInt
							Type:     schema.TypeInt,
							Computed: true,
						},

						"db_privileges": {
							// TypeList
							Type:     schema.TypeList,
							Computed: true,

							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{

									"db_name": {
										// TypeString
										Type:     schema.TypeString,
										Computed: true,
									},

									"privilege": {
										// TypeString
										Type:     schema.TypeString,
										Computed: true,
									},
								},
							},
						},

						"description": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"drds_account_name": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"host": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"instance_id": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},
					},
				},
			},
		},
	}
}

func dataSourceAlibabacloudStackDrdsAccountsRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	drdsService :=DrdsService{client}

	if _,  err := drdsService.DescribeDrdsInstance(d.Get("instance_id").(string)); err != nil {
		// 需要先判断drds_instance_id，不存在时直接返回空
		ids := []string{}
		datas := []interface{}{}
		d.SetId(dataResourceIdHash(ids))
		if err := d.Set("accounts", datas); err != nil {
			return err
		}
		if err := d.Set("ids", ids); err != nil {
			return err
		}
		if err := d.Set("names", ids); err != nil {
			return err
		}
		return nil
	}
	
	
	// api: Drds - 2019-01-23 - DescribeInstanceAccounts
	request := client.NewCommonRequest("POST", "Drds", "2019-01-23", "DescribeInstanceAccounts", "")
	DrdsDescribeinstanceaccountsResponse := DrdsDescribeinstanceaccountsResponse{}

	//调用request_params_handler

	request.QueryParams["DrdsInstanceId"] = d.Get("instance_id").(string)

	bresponse, err := client.ProcessCommonRequest(request)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_drds_account", "DescribeInstanceAccounts", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}

	err = json.Unmarshal(bresponse.GetHttpContentBytes(), &DrdsDescribeinstanceaccountsResponse)
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
			"alibabacloudstack_drds_account", "DescribeInstanceAccounts", errmsgs.AlibabacloudStackSdkGoERROR)
	}

	filterNames := map[string]string{}
	if vs, ok := d.GetOk("names"); ok {
		for _, v := range vs.([]interface{}) {
			filterNames[v.(string)] = ""
		}
	}

	accountType := d.Get("account_type")

	ids := []string{}
	names := []string{}
	datas := make([]interface{}, 0)
	for _, data := range DrdsDescribeinstanceaccountsResponse.InstanceAccounts.InstanceAccount {

		if len(filterNames) > 0 {
			if _, exist := filterNames[data.AccountName]; !exist {
				continue
			}
		}

		if accountType != -1 && accountType != data.AccountType {
			continue
		}
		id := fmt.Sprintf("%s:%s@%s", d.Get("instance_id").(string), data.AccountName, data.Host)
		dbPrivileges := []map[string]string{}
		for _, d := range data.DbPrivileges.DbPrivilege {
			dbPrivileges = append(dbPrivileges, map[string]string{
				"db_name":   d.DbName,
				"privilege": d.Privilege,
			})
		}
		i := map[string]interface{}{
			"id":                id,
			"account_type":      data.AccountType,
			"description":       data.Description,
			"drds_account_name": data.AccountName,
			"host":              data.Host,
			"instance_id":       d.Get("instance_id").(string),
			"db_privileges":     dbPrivileges,
		}
		datas = append(datas, i)
		ids = append(ids, id)
		names = append(names, data.AccountName)
	}

	d.SetId(dataResourceIdHash(ids))
	if err := d.Set("accounts", datas); err != nil {
		return err
	}
	if err := d.Set("ids", ids); err != nil {
		return err
	}
	if err := d.Set("names", names); err != nil {
		return err
	}
	return nil

}
