package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product RDS Resouce DbProxy
// generated by datasource_main.go2.jinja2
import (
	"encoding/json"
	"log"

	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/errmsgs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func dataSourceAlibabacloudStackPolardbProxies() *schema.Resource {
	return &schema.Resource{
		Read: dataSourceAlibabacloudStackPolardbProxiesRead,
		Schema: map[string]*schema.Schema{
			"ids": {
				Type:     schema.TypeList,
				Optional: true,
				Elem:     &schema.Schema{Type: schema.TypeString},
				Computed: true,
				MinItems: 1,
			},
			"db_instance_id": {
				Type:     schema.TypeString,
				Required: true,
			},

			"db_proxies": {
				Type:     schema.TypeList,
				Computed: true,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"id": {
							Type:     schema.TypeString,
							Computed: true,
						},

						"db_proxy_connect_string_items": {
							// TypeList
							Type:     schema.TypeList,
							Computed: true,

							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{

									"db_proxy_connect_string": {
										// TypeString
										Type:     schema.TypeString,
										Computed: true,
									},

									"db_proxy_connect_string_net_type": {
										// TypeString
										Type:     schema.TypeString,
										Computed: true,
									},

									"db_proxy_connect_string_net_work_type": {
										// TypeString
										Type:     schema.TypeInt,
										Computed: true,
									},

									"db_proxy_connect_string_port": {
										// TypeString
										Type:     schema.TypeString,
										Computed: true,
									},

									"db_proxy_endpoint_id": {
										// TypeString
										Type:     schema.TypeInt,
										Computed: true,
									},
								},
							},
						},

						"db_proxy_instance_current_minor_version": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"db_proxy_instance_latest_minor_version": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"db_proxy_instance_name": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"db_proxy_instance_num": {
							// TypeInt
							Type:     schema.TypeInt,
							Computed: true,
						},

						"db_proxy_instance_status": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"db_proxy_endpoint_items": {
							// TypeList
							Type:     schema.TypeList,
							Computed: true,

							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{

									"db_proxy_endpoint_aliases": {
										// TypeString
										Type:     schema.TypeString,
										Computed: true,
									},

									"db_proxy_endpoint_name": {
										// TypeString
										Type:     schema.TypeString,
										Computed: true,
									},

									"db_proxy_endpoint_type": {
										// TypeString
										Type:     schema.TypeString,
										Computed: true,
									},

									"db_proxy_read_write_mode": {
										// TypeString
										Type:     schema.TypeString,
										Computed: true,
									},
								},
							},
						},

						"db_proxy_instance_type": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"db_proxy_service_status": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"instance_network_type": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"persistent_connection_status": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},
					},
				},
			},
		},
	}
}

func dataSourceAlibabacloudStackPolardbProxiesRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	request := client.NewCommonRequest("GET", "polardb", "2024-01-30", "DescribeDBProxy", "")
	polardbDescribedbproxyResponseObj := PolardbDescribedbproxyResponse{}

	if v, ok := d.GetOk("db_instance_id"); ok {
		request.QueryParams["DBInstanceId"] = v.(string)
	}

	bresponse, err := client.ProcessCommonRequest(request)
	addDebug(request.GetActionName(), bresponse, request, request.QueryParams)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_polardb_proxy", "DescribeDBProxy", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}

	err = json.Unmarshal(bresponse.GetHttpContentBytes(), &polardbDescribedbproxyResponseObj)
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
			"alibabacloudstack_polardb_proxy", "DescribeDBProxy", errmsgs.AlibabacloudStackSdkGoERROR)
	}

	var ids []string
	datas := make([]interface{}, 0)
	db_proxy_connect_string_items := make([]map[string]interface{}, 0)
	for _, item := range polardbDescribedbproxyResponseObj.DBProxyConnectStringItems.DBProxyConnectStringItems {
		db_proxy_connect_string_items = append(db_proxy_connect_string_items, map[string]interface{}{
			"db_proxy_connect_string":               item.DBProxyConnectString,
			"db_proxy_connect_string_port":          item.DBProxyConnectStringPort,
			"db_proxy_connect_string_net_type":      item.DBProxyConnectStringNetType,
			"db_proxy_connect_string_net_work_type": item.DBProxyConnectStringNetWorkType,
			"db_proxy_endpoint_id":                  item.DBProxyEndpointId,
		})
	}

	db_proxy_endpoint_items := make([]map[string]interface{}, 0)
	for _, item := range polardbDescribedbproxyResponseObj.DBProxyEndpointItems.DBProxyEndpointItems {
		db_proxy_endpoint_items = append(db_proxy_endpoint_items, map[string]interface{}{
			"db_proxy_endpoint_name":    item.DBProxyEndpointName,
			"db_proxy_endpoint_type":    item.DBProxyEndpointType,
			"db_proxy_endpoint_aliases": item.DBProxyEndpointAliases,
			"db_proxy_read_write_mode":  item.DBProxyReadWriteMode,
		})
	}
	log.Printf("[DEBUG] db_proxy_endpoint_items: %#v", db_proxy_endpoint_items)
	log.Printf("[DEBUG] db_proxy_connect_string_items: %#v", db_proxy_connect_string_items)
	i := map[string]interface{}{
		"db_proxy_instance_current_minor_version": polardbDescribedbproxyResponseObj.DBProxyInstanceCurrentMinorVersion,

		"db_proxy_instance_latest_minor_version": polardbDescribedbproxyResponseObj.DBProxyInstanceLatestMinorVersion,

		"db_proxy_connect_string_items": db_proxy_connect_string_items,

		"db_proxy_instance_num": polardbDescribedbproxyResponseObj.DBProxyInstanceNum,

		"db_proxy_instance_status": polardbDescribedbproxyResponseObj.DBProxyInstanceStatus,

		"db_proxy_instance_type": polardbDescribedbproxyResponseObj.DBProxyInstanceType,

		"db_proxy_service_status": polardbDescribedbproxyResponseObj.DBProxyServiceStatus,

		"db_proxy_endpoint_items": db_proxy_endpoint_items,
	}
	datas = append(datas, i)

	db_instance_id := d.Get("db_instance_id").(string)

	ids = append(ids, db_instance_id)

	d.SetId(dataResourceIdHash(ids))
	if err := d.Set("db_proxies", datas); err != nil {
		return err
	}
	if err := d.Set("ids", ids); err != nil {
		return err
	}

	return nil

}
