package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product VPC Resouce DhcpOptionsSet
// generated by datasource_main.go2.jinja2
import (
	"encoding/json"
	"fmt"
	"regexp"

	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/errmsgs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
)

func dataSourceAlibabacloudStackVpcDhcpOptionsSets() *schema.Resource {
	return &schema.Resource{
		Read: dataSourceAlibabacloudStackVpcDhcpOptionsSetsRead,
		Schema: map[string]*schema.Schema{
			"ids": {
				Type:     schema.TypeList,
				Optional: true,
				Elem:     &schema.Schema{Type: schema.TypeString},
				Computed: true,
				MinItems: 1,
			},
			"name_regex": {
				Type:          schema.TypeString,
				Optional:      true,
				ValidateFunc:  validation.StringIsValidRegExp,
				Deprecated:    "Field 'name_regex' is deprecated and will be removed in a future release. Please use new field 'description_regex' instead.",
				ConflictsWith: []string{"description_regex"},
			},
			"description_regex": {
				Type:          schema.TypeString,
				Optional:      true,
				ValidateFunc:  validation.StringIsValidRegExp,
				ConflictsWith: []string{"name_regex"},
			},

			"domain_name": {
				Type:     schema.TypeString,
				Optional: true,
			},
			"dhcp_options_set_name": {
				Type:     schema.TypeString,
				Optional: true,
			},

			"dhcp_options_sets": {
				Type:     schema.TypeList,
				Computed: true,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"id": {
							Type:     schema.TypeString,
							Computed: true,
						},

						"associate_vpcs": {
							// TypeList
							Type:     schema.TypeList,
							Computed: true,

							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{

									"associate_status": {
										// TypeString
										Type:     schema.TypeString,
										Computed: true,
									},

									"vpc_id": {
										// TypeString
										Type:     schema.TypeString,
										Computed: true,
									},
								},
							},
						},

						"dhcp_options_set_description": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"dhcp_options_set_id": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"dhcp_options_set_name": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"domain_name": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"domain_name_servers": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"status": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},
					},
				},
			},
		},
	}
}

func dataSourceAlibabacloudStackVpcDhcpOptionsSetsRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)

	// api: Vpc - 2016-04-28 - ListDhcpOptionsSets
	request := client.NewCommonRequest("POST", "Vpc", "2016-04-28", "ListDhcpOptionsSets", "")
	VpcListdhcpoptionssetsResponseObj := VpcListdhcpoptionssetsResponse{}

	//调用request_params_handler

	if v, ok := d.GetOk("dhcp_options_set_id"); ok {
		request.QueryParams["DhcpOptionsSetId"] = fmt.Sprintf("[\"%v\"]", v.(string))
	}

	if v, ok := d.GetOk("dhcp_options_set_name"); ok {
		request.QueryParams["DhcpOptionsSetName"] = v.(string)
	}

	if v, ok := d.GetOk("domain_name"); ok {
		request.QueryParams["DomainName"] = v.(string)
	}

	bresponse, err := client.ProcessCommonRequest(request)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_vpc_dhcp_options_set", "ListDhcpOptionsSets", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}

	err = json.Unmarshal(bresponse.GetHttpContentBytes(), &VpcListdhcpoptionssetsResponseObj)
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
			"alibabacloudstack_vpc_dhcp_options_set", "ListDhcpOptionsSets", errmsgs.AlibabacloudStackSdkGoERROR)
	}
	idsMap := make(map[string]string)
	if v, ok := d.GetOk("ids"); ok {
		for _, vv := range v.([]interface{}) {
			idsMap[Trim(vv.(string))] = Trim(vv.(string))
		}
	}

	var ids []string
	datas := make([]interface{}, 0)
	vpcservice := VpcService{client}
	for _, data := range VpcListdhcpoptionssetsResponseObj.DhcpOptionsSets {

		if description_regex, ok := connectivity.GetResourceDataOk(d, "description_regex", "name_regex"); ok {
			r := regexp.MustCompile(description_regex.(string))
			if !r.MatchString(data.DhcpOptionsSetName) {
				continue
			}
		}

		if len(idsMap) > 0 {
			if _, exist := idsMap[data.DhcpOptionsSetId]; !exist {
				continue
			}
		}
		dhcp_options_set, err := vpcservice.DoVpcGetdhcpoptionssetRequest(data.DhcpOptionsSetId)
		if err != nil {
			return err
		}
		associate_vpcs := make([]map[string]interface{}, 0)
		for _, vpc := range dhcp_options_set.AssociateVpcs {
			associate_vpcs = append(associate_vpcs, map[string]interface{}{
				"associate_status": vpc.AssociateStatus,
				"vpc_id":           vpc.VpcId,
			})
		}
		i := map[string]interface{}{

			"id": data.DhcpOptionsSetId,

			"dhcp_options_set_description": data.DhcpOptionsSetDescription,

			"dhcp_options_set_id": data.DhcpOptionsSetId,

			"dhcp_options_set_name": data.DhcpOptionsSetName,

			"domain_name": data.DhcpOptions.DomainName,

			"domain_name_servers": data.DhcpOptions.DomainNameServers,

			"status": data.Status,

			"associate_vpcs": associate_vpcs,
		}
		datas = append(datas, i)

		dhcp_options_set_id := data.DhcpOptionsSetId

		ids = append(ids, dhcp_options_set_id)
	}

	d.SetId(dataResourceIdHash(ids))
	if err := d.Set("dhcp_options_sets", datas); err != nil {
		return err
	}
	if err := d.Set("ids", ids); err != nil {
		return err
	}

	return nil

}

type VpcListdhcpoptionssetsResponse struct {
	DhcpOptionsSets []struct {
		Tags struct {
			Tag []struct {
				Key   string `json:"Key"`
				Value string `json:"Value"`
			} `json:"Tag"`
		} `json:"Tags"`
		DhcpOptionsSetDescription string `json:"DhcpOptionsSetDescription"`
		Status                    string `json:"Status"`
		DhcpOptionsSetId          string `json:"DhcpOptionsSetId"`
		DhcpOptionsSetName        string `json:"DhcpOptionsSetName"`
		AssociateVpcCount         int    `json:"AssociateVpcCount"`
		OwnerId                   int    `json:"OwnerId"`
		ResourceGroupId           string `json:"ResourceGroupId"`
		DhcpOptions               struct {
			DomainNameServers string `json:"DomainNameServers"`
			DomainName        string `json:"DomainName"`
			LeaseTime         string `json:"LeaseTime"`
			Ipv6LeaseTime     string `json:"Ipv6LeaseTime"`
		} `json:"DhcpOptions"`
	} `json:"DhcpOptionsSets"`
	RequestId  string `json:"RequestId"`
	NextToken  string `json:"NextToken"`
	TotalCount string `json:"TotalCount"`
}
