package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product CEN Resouce TransitRouterRouteEntry
// generated by datasource_main.go2.jinja2
import (
	"fmt"
	"log"
	"regexp"

	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/errmsgs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func dataSourceAlibabacloudStackCenTransitRouterRouteEntries() *schema.Resource {
	return &schema.Resource{
		Read: dataSourceAlibabacloudStackCenTransitRouterRouteEntriesRead,
		Schema: map[string]*schema.Schema{
			"ids": {
				Type:     schema.TypeList,
				Optional: true,
				Elem:     &schema.Schema{Type: schema.TypeString},
				Computed: true,
				MinItems: 1,
			},
			"transit_router_route_table_id": {
				Type:        schema.TypeString,
				Required:    true,
				Description: "ID of the route table.",
			},
			"name_regex": {
				Type:     schema.TypeString,
				Optional: true,
			},
			"description_regex": {
				Type:     schema.TypeString,
				Optional: true,
			},

			"transit_router_route_entries": {
				Type:     schema.TypeList,
				Computed: true,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"id": {
							Type:     schema.TypeString,
							Computed: true,
						},
						"create_time": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "Creation time of the route entry.",
						},
						"status": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "Current status of the route entry.",
						},
						"transit_router_route_entry_description": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "Description of the route entry.",
						},
						"transit_router_route_entry_destination_cidr_block": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "Destination CIDR block of the route entry.",
						},
						"transit_router_route_entry_id": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "ID of the route entry.",
						},
						"transit_router_route_entry_name": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "Name of the route entry.",
						},
						"transit_router_route_entry_next_hop_id": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "Next hop ID of the route entry.",
						},
						"transit_router_route_entry_next_hop_type": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "Next hop type of the route entry.",
						},
						"transit_router_route_entry_type": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "Type of the route entry.",
						},
						"operational_mode": {
							Type:        schema.TypeBool,
							Computed:    true,
							Description: "operational_mode.",
						},
						"transit_router_route_entry_status": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "Status of the route entry.",
						},
					},
				},
			},
		},
	}
}

func dataSourceAlibabacloudStackCenTransitRouterRouteEntriesRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	cencen_instanceservice := CenService{client}
	id := d.Get("transit_router_route_table_id").(string)
	response, err := cencen_instanceservice.DoCbnDescribeTransitRouterRouteEntriesRequest(id + ":")
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg, "alibabacloudstack_cen_ceninstance", errmsgs.AlibabacloudStackSdkGoERROR)
	}
	idsMap := getIdsStringFilter(d)
	var ids []string
	datas := make([]interface{}, 0)
	for _, data := range response.TransitRouterRouteEntries {
		if len(idsMap) > 0 {
			key := fmt.Sprintf("%s:%s", id, data.TransitRouterRouteEntryId)
			if _, ok := idsMap[key]; !ok {
				continue
			}
		}
		if descriptionRegex, ok := d.GetOk("description_regex"); ok {
			r := regexp.MustCompile(descriptionRegex.(string))
			if !r.MatchString(data.TransitRouterRouteEntryDescription) {
				continue
			}
		}

		if nameRegex, ok := d.GetOk("name_regex"); ok {
			r := regexp.MustCompile(nameRegex.(string))
			if !r.MatchString(data.TransitRouterRouteEntryName) {
				continue
			}
		}
		i := map[string]interface{}{
			"transit_router_route_entry_id":                     data.TransitRouterRouteEntryId,
			"transit_router_route_entry_name":                   data.TransitRouterRouteEntryName,
			"transit_router_route_entry_description":            data.TransitRouterRouteEntryDescription,
			"transit_router_route_entry_type":                   data.TransitRouterRouteEntryType,
			"transit_router_route_entry_status":                 data.TransitRouterRouteEntryStatus,
			"transit_router_route_entry_next_hop_type":          data.TransitRouterRouteEntryNextHopType,
			"transit_router_route_entry_next_hop_id":            data.TransitRouterRouteEntryNextHopId,
			"transit_router_route_entry_destination_cidr_block": data.TransitRouterRouteEntryDestinationCidrBlock,
			"create_time":      data.CreateTime,
			"operational_mode": data.OperationalMode,
		}
		datas = append(datas, i)

		route_entry_id := data.TransitRouterRouteEntryId

		ids = append(ids, route_entry_id)
	}

	d.SetId(dataResourceIdHash(ids))
	log.Printf("[DEBUG]:transit_router_route_entries: %#v", datas)
	if err := d.Set("transit_router_route_entries", datas); err != nil {
		return err
	}
	if err := d.Set("ids", ids); err != nil {
		return err
	}

	return nil
}
