package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product MongoDB Resouce Account
// generated by datasource_main.go2.jinja2
import (
	"encoding/json"
	"regexp"

	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/errmsgs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func dataSourceAlibabacloudStackMongodbAccounts() *schema.Resource {
	return &schema.Resource{
		Read: dataSourceAlibabacloudStackMongodbAccountsRead,
		Schema: map[string]*schema.Schema{
			"ids": {
				Type:     schema.TypeList,
				Optional: true,
				Elem:     &schema.Schema{Type: schema.TypeString},
				Computed: true,
				MinItems: 1,
			},
			"account_name_regex": {
				Type:     schema.TypeString,
				Optional: true,
			},
			"instance_id": {
				Type:     schema.TypeString,
				Required: true,
			},

			"accounts": {
				Type:     schema.TypeList,
				Computed: true,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"id": {
							Type:     schema.TypeString,
							Computed: true,
						},

						"account_name": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"character_type": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"instance_id": {
							// TypeString
							Type:     schema.TypeString,
							Required: true,
							ForceNew: true,
						},

						"status": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},
						"account_type": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},
					},
				},
			},
		},
	}
}

func dataSourceAlibabacloudStackMongodbAccountsRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)

	// api: Dds - 2022-11-21 - DescribeAccounts
	request := client.NewCommonRequest("POST", "Dds", "2022-11-21", "DescribeAccounts", "")
	DdsDescribeaccountsResponseObj := DdsDescribeaccountsResponse{}

	//调用request_params_handler

	idsMap := make(map[string]string)
	if v, ok := d.GetOk("ids"); ok {
		for _, vv := range v.([]interface{}) {
			if vv == nil {
				continue
			}
			idsMap[vv.(string)] = vv.(string)
		}
	}

	request.QueryParams["DBInstanceId"] = d.Get("instance_id").(string)

	bresponse, err := client.ProcessCommonRequest(request)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_mongo_db_account", "DescribeAccounts", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}

	err = json.Unmarshal(bresponse.GetHttpContentBytes(), &DdsDescribeaccountsResponseObj)
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
			"alibabacloudstack_mongo_db_account", "DescribeAccounts", errmsgs.AlibabacloudStackSdkGoERROR)
	}

	var ids []string
	datas := make([]interface{}, 0)
	for _, data := range DdsDescribeaccountsResponseObj.Accounts.Account {
		if len(idsMap) > 0 {
			if _, ok := idsMap[data.AccountName+":"+data.DBInstanceId]; !ok {
				continue
			}
		}
		if nameRegex, ok := d.GetOk("account_name_regex"); ok {
			r := regexp.MustCompile(nameRegex.(string))
			if !r.MatchString(data.AccountName) {
				continue
			}
		}
		i := map[string]interface{}{
			"account_name": data.AccountName,

			"character_type": data.CharacterType,

			"instance_id": data.DBInstanceId,

			"status":       data.AccountStatus,
			"account_type": data.AccountType,
		}
		datas = append(datas, i)

		account_name := data.AccountName

		instance_id := data.DBInstanceId

		ids = append(ids, account_name+":"+instance_id)
	}

	d.SetId(dataResourceIdHash(ids))
	if err := d.Set("accounts", datas); err != nil {
		return err
	}
	if err := d.Set("ids", ids); err != nil {
		return err
	}

	return nil

}
