package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product ECS Resouce Invocation
// generated by datasource_main.go2.jinja2
import (
	"encoding/json"

	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/errmsgs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func dataSourceAlibabacloudStackEcsInvocations() *schema.Resource {
	return &schema.Resource{
		Read: dataSourceAlibabacloudStackEcsInvocationsRead,
		Schema: map[string]*schema.Schema{
			"ids": {
				Type:     schema.TypeList,
				Optional: true,
				Elem:     &schema.Schema{Type: schema.TypeString},
				Computed: true,
				MinItems: 1,
			},

			"command_id": {
				Type:     schema.TypeString,
				Optional: true,
			},

			"command_name": {
				Type:     schema.TypeString,
				Optional: true,
			},

			"instance_id": {
				Type:     schema.TypeString,
				Optional: true,
			},

			"timed": {
				Type:     schema.TypeBool,
				Optional: true,
			},

			"invocation_id": {
				Type:     schema.TypeString,
				Optional: true,
			},

			"invocations": {
				Type:     schema.TypeList,
				Computed: true,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"id": {
							Type:     schema.TypeString,
							Computed: true,
						},

						"command_id": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"create_time": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"frequency": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"instance_ids": {
							Type:     schema.TypeList,
							Elem:     &schema.Schema{Type: schema.TypeString},
							Computed: true,
						},
						"invocation_id": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"repeat_mode": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},
						
						"parameters": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"resource_type": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"tags": {
							// TypeList
							Type:     schema.TypeList,
							Computed: true,

							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{

									"tag_key": {
										// TypeString
										Type:     schema.TypeString,
										Computed: true,
									},

									"tag_value": {
										// TypeString
										Type:     schema.TypeString,
										Computed: true,
									},
								},
							},
						},

						"timed": {
							// TypeBool
							Type:     schema.TypeBool,
							Computed: true,
						},

						"username": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"windows_password_name": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},
					},
				},
			},
		},
	}
}

func dataSourceAlibabacloudStackEcsInvocationsRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)

	// api: Ecs - 2014-05-26 - DescribeInvocations
	request := client.NewCommonRequest("GET", "Ecs", "2014-05-26", "DescribeInvocations", "")
	EcsDescribeinvocationsResponseObj := EcsDescribeinvocationsResponse{}

	// Call request_params_handler

	if v, ok := d.GetOk("command_id"); ok {
		request.QueryParams["CommandId"] = v.(string)
	}

	if v, ok := d.GetOk("command_name"); ok {
		request.QueryParams["CommandName"] = v.(string)
	}

	if v, ok := d.GetOk("instance_id"); ok {
		request.QueryParams["InstanceId"] = v.(string)
	}

	if v, ok := d.GetOk("invocation_id"); ok {
		request.QueryParams["InvokeId"] = v.(string)
	}

	bresponse, err := client.ProcessCommonRequest(request)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_ecs_invocation", "DescribeInvocations", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}

	err = json.Unmarshal(bresponse.GetHttpContentBytes(), &EcsDescribeinvocationsResponseObj)
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
			"alibabacloudstack_ecs_invocation", "DescribeInvocations", errmsgs.AlibabacloudStackSdkGoERROR)
	}

	var ids []string
	datas := make([]interface{}, 0)
	for _, data := range EcsDescribeinvocationsResponseObj.Invocations.Invocation {
		instance_ids := []string{}
		for _, instance := range data.InvokeInstances.InvokeInstance {
			instance_ids = append(instance_ids, instance.InstanceId)
		}
		i := map[string]interface{}{
			"id": data.InvokeId,

			"command_id": data.CommandId,

			"create_time": data.CreationTime,

			"frequency": data.Frequency,

			"instance_ids": instance_ids,

			"invocation_id": data.InvokeId,

			"parameters": data.Parameters,

			"repeat_mode": data.RepeatMode,

			"timed": data.Timed,

			"username": data.Username,
		}
		datas = append(datas, i)

		invocation_id := data.InvokeId

		ids = append(ids, invocation_id)
	}

	d.SetId(dataResourceIdHash(ids))
	if err := d.Set("invocations", datas); err != nil {
		return err
	}
	if err := d.Set("ids", ids); err != nil {
		return err
	}

	return nil

}
