package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product SLB Resouce AccessLog
// generated by datasource_main.go2.jinja2
import (
	"encoding/json"
	"fmt"
	"regexp"

	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/errmsgs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
)

func dataSourceAlibabacloudStackSlbAccessLogs() *schema.Resource {
	return &schema.Resource{
		Read: dataSourceAlibabacloudStackSlbAccessLogsRead,
		Schema: map[string]*schema.Schema{
			"ids": {
				Type:     schema.TypeList,
				Optional: true,
				Elem:     &schema.Schema{Type: schema.TypeString},
				Computed: true,
				MinItems: 1,
			},

			"load_balancer_id": {
				Type:     schema.TypeString,
				Optional: true,
			},
			"log_store_regex": {
				Type:         schema.TypeString,
				Optional:     true,
				ValidateFunc: validation.StringIsValidRegExp,
			},
			"access_logs": {
				Type:     schema.TypeList,
				Computed: true,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"id": {
							Type:     schema.TypeString,
							Computed: true,
						},
						// No API interface
						// "listener_extended_attributes": {
						// 	// TypeList
						// 	Type:     schema.TypeList,
						// 	Computed: true,

						// 	Elem: &schema.Resource{
						// 		Schema: map[string]*schema.Schema{

						// 			"kv_attributes": {
						// 				// TypeList
						// 				Type:     schema.TypeList,
						// 				Computed: true,

						// 				Elem: &schema.Resource{
						// 					Schema: map[string]*schema.Schema{

						// 						"key": {
						// 							// TypeString
						// 							Type:     schema.TypeString,
						// 							Computed: true,
						// 						},

						// 						"value": {
						// 							// TypeString
						// 							Type:     schema.TypeString,
						// 							Computed: true,
						// 						},
						// 					},
						// 				},
						// 			},

						// 			"listener_port": {
						// 				// TypeInt
						// 				Type:     schema.TypeInt,
						// 				Computed: true,
						// 			},

						// 			"protocol": {
						// 				// TypeString
						// 				Type:     schema.TypeString,
						// 				Computed: true,
						// 			},

						// 			"record_customized_headers": {
						// 				// TypeString
						// 				Type:     schema.TypeString,
						// 				Computed: true,
						// 			},
						// 		},
						// 	},
						// },

						"load_balancer_id": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"log_project": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"log_store": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"log_type": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},
						// No API support for this attribute
						// "role_name": {
						// 	// TypeString
						// 	Type:     schema.TypeString,
						// 	Computed: true,
						// },
					},
				},
			},
		},
	}
}

func dataSourceAlibabacloudStackSlbAccessLogsRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)

	// api: Slb - 2014-05-15 - DescribeAccessLogsDownloadAttribute
	request := client.NewCommonRequest("POST", "Slb", "2014-05-15", "DescribeAccessLogsDownloadAttribute", "")
	SlbDescribeaccesslogsdownloadattributeResponseObj := SlbDescribeaccesslogsdownloadattributeResponse{}

	// Call request_params_handler

	if v, ok := d.GetOk("load_balancer_id"); ok {
		request.QueryParams["LoadBalancerId"] = v.(string)
	}

	request.QueryParams["LogType"] = "layer7"

	bresponse, err := client.ProcessCommonRequest(request)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_slb_access_log", "DescribeAccessLogsDownloadAttribute", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}

	err = json.Unmarshal(bresponse.GetHttpContentBytes(), &SlbDescribeaccesslogsdownloadattributeResponseObj)
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
			"alibabacloudstack_slb_access_log", "DescribeAccessLogsDownloadAttribute", errmsgs.AlibabacloudStackSdkGoERROR)
	}

	idsMap := make(map[string]string)
	if v, ok := d.GetOk("ids"); ok {
		for _, vv := range v.([]interface{}) {
			idsMap[Trim(vv.(string))] = Trim(vv.(string))
		}
	}

	var ids []string
	datas := make([]interface{}, 0)
	for _, data := range SlbDescribeaccesslogsdownloadattributeResponseObj.LogsDownloadAttributes.LogsDownloadAttribute {

		if description_regex, ok := connectivity.GetResourceDataOk(d, "description_regex", "log_store_regex"); ok {
			r := regexp.MustCompile(description_regex.(string))
			if !r.MatchString(data.LogStore) {
				continue
			}
		}
		id := fmt.Sprintf("%s:%s:%s", data.LoadBalancerId, data.LogProject, data.LogStore)
		if len(idsMap) > 0 {
			if _, exist := idsMap[id]; !exist {
				continue
			}
		}
		i := map[string]interface{}{

			"id": id,

			"load_balancer_id": data.LoadBalancerId,

			"log_project": data.LogProject,

			"log_store": data.LogStore,

			"log_type": data.LogType,
		}
		datas = append(datas, i)

		load_balancer_id := data.LoadBalancerId

		ids = append(ids, load_balancer_id)
	}

	d.SetId(dataResourceIdHash(ids))
	if err := d.Set("access_logs", datas); err != nil {
		return err
	}
	if err := d.Set("ids", ids); err != nil {
		return err
	}

	return nil

}
