package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product ACM Resouce Configuration
// generated by datasource_main.go2.jinja2
import (
	"encoding/json"

	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/errmsgs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func dataSourceAlibabacloudStackAcmConfigurations() *schema.Resource {
	return &schema.Resource{
		Read: dataSourceAlibabacloudStackAcmConfigurationsRead,
		Schema: map[string]*schema.Schema{
			"ids": {
				Type:     schema.TypeList,
				Optional: true,
				Elem:     &schema.Schema{Type: schema.TypeString},
				Computed: true,
				MinItems: 1,
			},

			"data_id": {
				Type:     schema.TypeString,
				Required: true,
			},

			"group": {
				Type:     schema.TypeString,
				Required: true,
			},

			"app_name": {
				Type:     schema.TypeString,
				Optional: true,
			},

			"namespace_id": {
				Type:     schema.TypeString,
				Optional: true,
			},

			"configurations": {
				Type:     schema.TypeList,
				Computed: true,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"id": {
							Type:     schema.TypeString,
							Computed: true,
						},

						"app_name": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"content": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"data_id": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"desc": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"group": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"message_digest": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"namespace_id": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"tags": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"type": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"ud_version": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},
					},
				},
			},
		},
	}
}

func dataSourceAlibabacloudStackAcmConfigurationsRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)

	// api: acm - 2020-02-06 - DescribeConfigurations
	request := client.NewCommonRequest("GET", "acm", "2020-02-06", "DescribeConfigurations", "")
	AcmDescribeconfigurationsResponseObj := AcmDescribeconfigurationsResponse{}

	//调用request_params_handler

	if v, ok := d.GetOk("app_name"); ok {
		request.QueryParams["AppName"] = v.(string)
	}

	if v, ok := d.GetOk("data_id"); ok {
		request.QueryParams["DataId"] = v.(string)
	}

	if v, ok := d.GetOk("group"); ok {
		request.QueryParams["Group"] = v.(string)
	}

	if v, ok := d.GetOk("namespace_id"); ok {
		request.QueryParams["NamespaceId"] = v.(string)
	}

	bresponse, err := client.ProcessCommonRequest(request)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_acm_configuration", "DescribeConfigurations", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}

	err = json.Unmarshal(bresponse.GetHttpContentBytes(), &AcmDescribeconfigurationsResponseObj)
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
			"alibabacloudstack_acm_configuration", "DescribeConfigurations", errmsgs.AlibabacloudStackSdkGoERROR)
	}

	var ids []string
	datas := make([]interface{}, 0)
	for _, data := range AcmDescribeconfigurationsResponseObj.Configurations.Configuration {
		i := map[string]interface{}{
			"app_name": data.AppName,

			"data_id": data.DataId,

			"group": data.Group,

			"namespace_id": data.NamespaceId,

			"message_digest": data.Md5,

			"ud_version": data.UdVersion,
		}
		datas = append(datas, i)

		data_id := data.DataId

		ids = append(ids, data_id)
	}

	d.SetId(dataResourceIdHash(ids))
	if err := d.Set("configurations", datas); err != nil {
		return err
	}
	if err := d.Set("ids", ids); err != nil {
		return err
	}

	return nil

}
