package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product CEN Resouce TransitRouterRouteEntry
// generated by datasource_main.go2.jinja2
import (
	"fmt"
	"regexp"

	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/errmsgs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func dataSourceAlibabacloudStackCenTransitRouterMulticastDomains() *schema.Resource {
	return &schema.Resource{
		Read: dataSourceAlibabacloudStackCenTransitRouterMulticastDomainsRead,
		Schema: map[string]*schema.Schema{
			"ids": {
				Type:     schema.TypeList,
				Optional: true,
				Elem:     &schema.Schema{Type: schema.TypeString},
				Computed: true,
				MinItems: 1,
			},
			"transit_router_route_id": {
				Type:        schema.TypeString,
				Required:    true,
				Description: "ID of the route.",
			},
			"name_regex": {
				Type:     schema.TypeString,
				Optional: true,
			},
			"description_regex": {
				Type:     schema.TypeString,
				Optional: true,
			},

			"transit_router_multicast_domains": {
				Type:     schema.TypeList,
				Computed: true,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"id": {
							Type:     schema.TypeString,
							Computed: true,
						},
						"transit_router_multicast_domain_name": {
							Type:     schema.TypeString,
							Computed: true,
						},
						"transit_router_multicast_domain_description": {
							Type:     schema.TypeString,
							Computed: true,
						},
						"status": {
							Type:     schema.TypeString,
							Computed: true,
						},
						"transit_router_id": {
							Type:     schema.TypeString,
							Computed: true,
						},
					},
				},
			},
		},
	}
}

func dataSourceAlibabacloudStackCenTransitRouterMulticastDomainsRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	cencen_instanceservice := CenService{client}
	id := d.Get("transit_router_route_id").(string)
	response, err := cencen_instanceservice.DoCbnDescribeTransitRouterMuliticastDomainsRequest(id + ":")
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg, "alibabacloudstack_cen_transit_router_multicast_domains", errmsgs.AlibabacloudStackSdkGoERROR)
	}
	idsMap := make(map[string]string)
	if v, ok := d.GetOk("ids"); ok {
		for _, vv := range v.([]interface{}) {
			if vv == nil {
				continue
			}
			idsMap[vv.(string)] = vv.(string)
		}
	}
	var ids []string
	datas := make([]interface{}, 0)
	for _, data := range response.TransitRouterMulticastDomains {
		if len(idsMap) > 0 {
			key := fmt.Sprintf("%s:%s", id, data.TransitRouterMulticastDomainId)
			if _, ok := idsMap[key]; !ok {
				continue
			}
		}
		if descriptionRegex, ok := d.GetOk("description_regex"); ok {
			r := regexp.MustCompile(descriptionRegex.(string))
			if !r.MatchString(data.TransitRouterMulticastDomainDescription) {
				continue
			}
		}

		if nameRegex, ok := d.GetOk("name_regex"); ok {
			r := regexp.MustCompile(nameRegex.(string))
			if !r.MatchString(data.TransitRouterMulticastDomainName) {
				continue
			}
		}

		i := map[string]interface{}{
			"id":                                   data.TransitRouterMulticastDomainId,
			"transit_router_multicast_domain_name": data.TransitRouterMulticastDomainName,
			"transit_router_multicast_domain_description": data.TransitRouterMulticastDomainDescription,
			"transit_router_id":                           data.TransitRouterId,
			"status":                                      data.Status,
		}
		datas = append(datas, i)

		ids = append(ids, data.TransitRouterMulticastDomainId)
	}

	d.SetId(dataResourceIdHash(ids))
	if err := d.Set("transit_router_multicast_domains", datas); err != nil {
		return err
	}
	if err := d.Set("ids", ids); err != nil {
		return err
	}

	return nil
}
