package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product POLARDB Resouce DBInstance
// generated by datasource_main.go2.jinja2
import (
	"log"

	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/errmsgs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func dataSourceAlibabacloudStackPolardbClusterBackupPolicies() *schema.Resource {
	return &schema.Resource{
		Read: dataSourceAlibabacloudStackPolardbClusterBackupPoliciesRead,
		Schema: map[string]*schema.Schema{
			"db_cluster_id": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
			},
			"data_level1_backup_frequency": {
				Type:     schema.TypeString,
				Computed: true,
			},
			"data_level1_backup_period": {
				Type:     schema.TypeString,
				Computed: true,
			},
			"data_level1_backup_time": {
				Type:     schema.TypeString,
				Computed: true,
			},
			"data_level1_backup_retention_period": {
				Type:     schema.TypeInt,
				Computed: true,
			},
			"data_level2_backup_retention_period": {
				Type:     schema.TypeInt,
				Computed: true,
			},
			"backup_retention_policy_on_cluster_deletion": {
				Type:     schema.TypeString,
				Computed: true,
			},
			"log_backup_retention_period": {
				Type:     schema.TypeInt,
				Computed: true,
			},
			"preferred_backup_time": {
				Type:     schema.TypeString,
				Computed: true,
			},
			"preferred_backup_period": {
				Type:     schema.TypeString,
				Computed: true,
			},
			"backup_retention_period": {
				Type:     schema.TypeInt,
				Computed: true,
			},
			"backup_frequency": {
				Type:     schema.TypeString,
				Computed: true,
			},
			"preferred_next_backup_time": {
				Type:     schema.TypeString,
				Computed: true,
			},
			"data_level2_backup_period": {
				Type:     schema.TypeString,
				Computed: true,
			},
			"data_level2_backup_another_region_region": {
				Type:     schema.TypeString,
				Computed: true,
			},
			"data_level2_backup_another_region_retention_period": {
				Type:     schema.TypeInt,
				Computed: true,
			},
			"log_backup_another_region_region": {
				Type:     schema.TypeString,
				Computed: true,
			},
			"log_backup_another_region_retention_period": {
				Type:     schema.TypeInt,
				Computed: true,
			},
			"enable_backup_log": {
				Type:     schema.TypeInt,
				Computed: true,
			},
		},
	}
}

func dataSourceAlibabacloudStackPolardbClusterBackupPoliciesRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	polardbService := PolardbService{client}
	db_cluster_id := d.Get("db_cluster_id").(string)
	object, err := polardbService.DescribePolardbClusterBackupPolicy(db_cluster_id)
	if err != nil {
		if errmsgs.NotFoundError(err) {
			log.Printf("[DEBUG] Data source alibabacloudstack_polardb_cluster_backup_policies polardbService.DescribePolardbClusterBackupPolicy Failed!!! %s", err)
			d.SetId("")
			return nil
		}
		return errmsgs.WrapError(err)
	}
	d.SetId(db_cluster_id)
	d.Set("data_level1_backup_frequency", object["DataLevel1BackupFrequency"])
	d.Set("data_level1_backup_period", object["DataLevel1BackupPeriod"])
	d.Set("data_level1_backup_time", object["DataLevel1BackupTime"])

	d.Set("data_level1_backup_retention_period", object["DataLevel1BackupRetentionPeriod"])
	d.Set("data_level2_backup_retention_period", object["DataLevel2BackupRetentionPeriod"])

	d.Set("backup_retention_policy_on_cluster_deletion", object["BackupRetentionPolicyOnClusterDeletion"])
	d.Set("preferred_backup_time", object["PreferredBackupTime"])
	d.Set("preferred_backup_period", object["PreferredBackupPeriod"])
	d.Set("backup_retention_period", object["BackupRetentionPeriod"])

	d.Set("backup_frequency", object["BackupFrequency"])
	d.Set("preferred_next_backup_time", object["PreferredNextBackupTime"])
	d.Set("data_level2_backup_period", object["DataLevel2BackupPeriod"])
	d.Set("data_level2_backup_another_region_region", object["DataLevel2BackupAnotherRegionRegion"])
	d.Set("data_level2_backup_another_region_retention_period", object["DataLevel2BackupAnotherRegionRetentionPeriod"])
	logObject, err := polardbService.DescribePolardbClusterLogBackupPolicy(d.Id())
	if err != nil {
		return errmsgs.WrapError(err)
	}
	d.Set("log_backup_retention_period", logObject["LogBackupRetentionPeriod"])
	d.Set("log_backup_another_region_region", logObject["LogBackupAnotherRegionRegion"])
	d.Set("log_backup_another_region_retention_period", logObject["LogBackupAnotherRegionRetentionPeriod"])
	d.Set("enable_backup_log", logObject["LogBackupAnotherRegionRetentionPeriod"])
	return nil
}
