package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product ECS Resouce SnapshotGroup
// generated by datasource_main.go2.jinja2
import (
	"encoding/json"
	"fmt"
	"regexp"

	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/errmsgs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
)

func dataSourceAlibabacloudStackEcsSnapshotGroups() *schema.Resource {
	return &schema.Resource{
		Read: dataSourceAlibabacloudStackEcsSnapshotGroupsRead,
		Schema: map[string]*schema.Schema{
			"ids": {
				Type:     schema.TypeList,
				Optional: true,
				Elem:     &schema.Schema{Type: schema.TypeString},
				Computed: true,
				MinItems: 1,
			},
			"name_regex": {
				Type:          schema.TypeString,
				Optional:      true,
				ValidateFunc:  validation.StringIsValidRegExp,
				Deprecated:    "Field 'name_regex' is deprecated and will be removed in a future release. Please use new field 'description_regex' instead.",
				ConflictsWith: []string{"description_regex"},
			},
			"description_regex": {
				Type:          schema.TypeString,
				Optional:      true,
				ValidateFunc:  validation.StringIsValidRegExp,
				ConflictsWith: []string{"name_regex"},
			},

			"instance_id": {
				Type:     schema.TypeString,
				Optional: true,
			},

			"snapshot_group_name": {
				Type:     schema.TypeString,
				Optional: true,
			},

			"snapshot_groups": {
				Type:     schema.TypeList,
				Computed: true,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"id": {
							Type:     schema.TypeString,
							Computed: true,
						},

						"create_time": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"description": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},
						"snapshots": {
							Type:     schema.TypeSet,
							Computed: true,
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{

									"snapshot_id": {
										// TypeString
										Type:     schema.TypeString,
										Computed: true,
									},
									"progress": {
										// TypeString
										Type:     schema.TypeString,
										Computed: true,
									},
									"available": {
										Type:     schema.TypeBool,
										Computed: true,
									},
									"source_disk_type": {
										// TypeString
										Type:     schema.TypeString,
										Computed: true,
									},
									"source_disk_id": {
										// TypeString
										Type:     schema.TypeString,
										Computed: true,
									},
									"instant_access": {
										Type:     schema.TypeBool,
										Computed: true,
									},
									"instant_access_retention_days": {
										// TypeInt
										Type:     schema.TypeInt,
										Computed: true,
									},
								},
							},
						},
						"instance_id": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},
						"snapshot_group_id": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"snapshot_group_name": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"status": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},
					},
				},
			},
		},
	}
}

func dataSourceAlibabacloudStackEcsSnapshotGroupsRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)

	// api: Ecs - 2014-05-26 - DescribeSnapshotGroups
	request := client.NewCommonRequest("POST", "Ecs", "2014-05-26", "DescribeSnapshotGroups", "")
	EcsDescribesnapshotgroupsResponseObj := EcsDescribesnapshotgroupsResponse{}

	// Call request_params_handler

	if v, ok := d.GetOk("instance_id"); ok {
		request.QueryParams["InstanceId"] = v.(string)
	}

	if v, ok := d.GetOk("snapshot_group_id"); ok {
		request.QueryParams["SnapshotGroupId[*]"] = fmt.Sprintf("[\"%s\"]", v.(string))
	}

	if v, ok := d.GetOk("snapshot_group_name"); ok {
		request.QueryParams["Name"] = v.(string)
	}

	if v, ok := d.GetOk("status"); ok {
		request.QueryParams["Status[*]"] = fmt.Sprintf("[\"%s\"]", v.(string))
	}

	bresponse, err := client.ProcessCommonRequest(request)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_ecs_snapshot_group", "DescribeSnapshotGroups", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}

	err = json.Unmarshal(bresponse.GetHttpContentBytes(), &EcsDescribesnapshotgroupsResponseObj)
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
			"alibabacloudstack_ecs_snapshot_group", "DescribeSnapshotGroups", errmsgs.AlibabacloudStackSdkGoERROR)
	}

	idsMap := getIdsStringFilter(d)

	var ids []string
	datas := make([]interface{}, 0)
	for _, data := range EcsDescribesnapshotgroupsResponseObj.SnapshotGroups.SnapshotGroup {

		if description_regex, ok := connectivity.GetResourceDataOk(d, "description_regex", "name_regex"); ok {
			r := regexp.MustCompile(description_regex.(string))
			if !r.MatchString(data.Name) {
				continue
			}
		}

		if len(idsMap) > 0 {
			if _, exist := idsMap[data.SnapshotGroupId]; !exist {
				continue
			}
		}
		snapshots := make([]map[string]interface{}, 0)
		if len(data.Snapshots.Snapshot) > 0 {
			for _, snapshot := range data.Snapshots.Snapshot {
				snapshots = append(snapshots, map[string]interface{}{
					"snapshot_id":      snapshot.SnapshotId,
					"progress":         snapshot.Progress,
					"available":        snapshot.Available,
					"source_disk_type": snapshot.SourceDiskType,
					"source_disk_id":   snapshot.SourceDiskId,
					"instant_access":   snapshot.InstantAccess,
				})
			}
		}
		i := map[string]interface{}{
			"id": data.SnapshotGroupId,

			"snapshot_group_id": data.SnapshotGroupId,

			"create_time": data.CreationTime,

			"description": data.Description,

			"instance_id": data.InstanceId,

			"snapshot_group_name": data.Name,

			"status": data.Status,

			"snapshots": snapshots,
		}

		datas = append(datas, i)

		snapshot_group_id := data.SnapshotGroupId

		ids = append(ids, snapshot_group_id)
	}

	d.SetId(dataResourceIdHash(ids))
	if err := d.Set("snapshot_groups", datas); err != nil {
		return err
	}
	if err := d.Set("ids", ids); err != nil {
		return err
	}

	return nil

}

