package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product ECS Resouce DedicatedHostCluster
// generated by datasource_main.go2.jinja2
import (
	"encoding/json"
	"regexp"

	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/errmsgs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func dataSourceAlibabacloudStackEcsDedicatedHostClusters() *schema.Resource {
	return &schema.Resource{
		Read: dataSourceAlibabacloudStackEcsDedicatedHostClustersRead,
		Schema: map[string]*schema.Schema{
			"ids": {
				Type:     schema.TypeList,
				Optional: true,
				Elem:     &schema.Schema{Type: schema.TypeString},
				Computed: true,
				ForceNew: true,
				MinItems: 1,
			},

			"dedicated_host_cluster_name_regex": {
				Type:     schema.TypeString,
				Optional: true,
			},
			"dedicated_host_cluster_name": {
				Type:     schema.TypeString,
				Optional: true,
			},

			"output_file": {
				Type:     schema.TypeString,
				Optional: true,
			},

			"dedicated_host_clusters": {
				Type:     schema.TypeList,
				Computed: true,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"id": {
							Type:     schema.TypeString,
							Computed: true,
						},

						"dedicated_host_cluster_id": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"dedicated_host_cluster_name": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"description": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"zone_id": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},
					},
				},
			},
		},
	}
}

func dataSourceAlibabacloudStackEcsDedicatedHostClustersRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)

	// api: Ecs - 2014-05-26 - DescribeDedicatedHostClusters
	request := client.NewCommonRequest("POST", "Ecs", "2014-05-26", "DescribeDedicatedHostClusters", "")
	EcsDescribededicatedhostclustersResponse := EcsDescribededicatedhostclustersResponse{}

	// Call request_params_handler

	if v, ok := d.GetOk("dedicated_host_cluster_name"); ok {
		request.QueryParams["DedicatedHostClusterName"] = v.(string)
	}

	bresponse, err := client.ProcessCommonRequest(request)
	addDebug(request.GetActionName(), bresponse, request, request.QueryParams)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_ecs_dedicated_host_cluster", "DescribeDedicatedHostClusters", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}

	err = json.Unmarshal(bresponse.GetHttpContentBytes(), &EcsDescribededicatedhostclustersResponse)
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
			"alibabacloudstack_ecs_dedicated_host_cluster", "DescribeDedicatedHostClusters", errmsgs.AlibabacloudStackSdkGoERROR)
	}
	idsMap := getIdsStringFilter(d)

	var ids []string
	datas := make([]interface{}, 0)
	for _, data := range EcsDescribededicatedhostclustersResponse.DedicatedHostClusters.DedicatedHostCluster {
		if dedicated_host_cluster_name_regex, ok := connectivity.GetResourceDataOk(d, "dedicated_host_cluster_name_regex"); ok {
			r := regexp.MustCompile(dedicated_host_cluster_name_regex.(string))
			if !r.MatchString(data.DedicatedHostClusterName) {
				continue
			}
		}

		if len(idsMap) > 0 {
			if _, exist := idsMap[data.DedicatedHostClusterId]; !exist {
				continue
			}
		}
		i := map[string]interface{}{
			"dedicated_host_cluster_id": data.DedicatedHostClusterId,

			"dedicated_host_cluster_name": data.DedicatedHostClusterName,

			"description": data.Description,

			"zone_id": data.ZoneId,
		}
		datas = append(datas, i)

		dedicated_host_cluster_id := data.DedicatedHostClusterId

		ids = append(ids, dedicated_host_cluster_id)
	}

	d.SetId(dataResourceIdHash(ids))
	if err := d.Set("dedicated_host_clusters", datas); err != nil {
		return err
	}
	if err := d.Set("ids", ids); err != nil {
		return err
	}

	// create a json file in current directory and write data source to it.
	if output, ok := d.GetOk("output_file"); ok && output.(string) != "" {
		writeToFile(output.(string), datas)
	}
	return nil

}
