package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product VPC Resouce DhcpOptionsSet
// generated by datasource_main.go2.jinja2
import (
	"encoding/json"

	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/errmsgs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func dataSourceAlibabacloudStackVpcDhcpOptionsSets() *schema.Resource {
	return &schema.Resource{
		Read: dataSourceAlibabacloudStackVpcDhcpOptionsSetsRead,
		Schema: map[string]*schema.Schema{
			"ids": {
				Type:     schema.TypeList,
				Optional: true,
				Elem:     &schema.Schema{Type: schema.TypeString},
				Computed: true,
				MinItems: 1,
			},

			"domain_name": {
				Type:     schema.TypeString,
				Optional: true,
			},
			"dhcp_options_set_name": {
				Type:     schema.TypeString,
				Optional: true,
			},

			"next_token": {
				Type:     schema.TypeString,
				Optional: true,
			},

			"resource_group_id": {
				Type:     schema.TypeString,
				Optional: true,
			},

			"region_id": {
				Type:     schema.TypeString,
				Required: true,
			},

			"dhcp_options_sets": {
				Type:     schema.TypeList,
				Computed: true,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"id": {
							Type:     schema.TypeString,
							Computed: true,
						},

						"all": {
							// TypeBool
							Type:     schema.TypeBool,
							Computed: true,
						},

						"associate_vpcs": {
							// TypeList
							Type:     schema.TypeList,
							Computed: true,

							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{

									"associate_status": {
										// TypeString
										Type:     schema.TypeString,
										Computed: true,
									},

									"vpc_id": {
										// TypeString
										Type:     schema.TypeString,
										Computed: true,
									},
								},
							},
						},

						"dhcp_options_set_description": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"dhcp_options_set_id": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"dhcp_options_set_name": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"domain_name": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"domain_name_servers": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"dry_run": {
							// TypeBool
							Type:     schema.TypeBool,
							Computed: true,
						},

						"resource_type": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"status": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"tags": {
							// TypeList
							Type:     schema.TypeList,
							Computed: true,

							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{

									"tag_key": {
										// TypeString
										Type:     schema.TypeString,
										Computed: true,
									},

									"tag_value": {
										// TypeString
										Type:     schema.TypeString,
										Computed: true,
									},
								},
							},
						},
					},
				},
			},
		},
	}
}

func dataSourceAlibabacloudStackVpcDhcpOptionsSetsRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)

	// api: Vpc - 2016-04-28 - ListDhcpOptionsSets
	request := client.NewCommonRequest("POST", "Vpc", "2016-04-28", "ListDhcpOptionsSets", "")
	VpcListdhcpoptionssetsResponseObj := VpcListdhcpoptionssetsResponse{}

	//调用request_params_handler

	if v, ok := d.GetOk("dhcp_options_set_id"); ok {
		request.QueryParams["DhcpOptionsSetId[*]"] = v.(string)
	}

	if v, ok := d.GetOk("dhcp_options_set_name"); ok {
		request.QueryParams["DhcpOptionsSetName"] = v.(string)
	}

	if v, ok := d.GetOk("domain_name"); ok {
		request.QueryParams["DomainName"] = v.(string)
	}

	bresponse, err := client.ProcessCommonRequest(request)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_vpc_dhcp_options_set", "ListDhcpOptionsSets", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}

	err = json.Unmarshal(bresponse.GetHttpContentBytes(), &VpcListdhcpoptionssetsResponseObj)
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
			"alibabacloudstack_vpc_dhcp_options_set", "ListDhcpOptionsSets", errmsgs.AlibabacloudStackSdkGoERROR)
	}

	var ids []string
	datas := make([]interface{}, 0)
	for _, data := range VpcListdhcpoptionssetsResponseObj.DhcpOptionsSets.DhcpOptionsSet {
		i := map[string]interface{}{
			"dhcp_options_set_description": data.DhcpOptionsSetDescription,

			"dhcp_options_set_id": data.DhcpOptionsSetId,

			"dhcp_options_set_name": data.DhcpOptionsSetName,

			"domain_name": data.DhcpOptions.DomainName,

			"domain_name_servers": data.DhcpOptions.DomainNameServers,

			"next_token": data,

			"status": data.Status,
		}
		datas = append(datas, i)

		dhcp_options_set_id := data.DhcpOptionsSetId

		ids = append(ids, dhcp_options_set_id)
	}

	d.SetId(dataResourceIdHash(ids))
	if err := d.Set("dhcp_options_sets", datas); err != nil {
		return err
	}
	if err := d.Set("ids", ids); err != nil {
		return err
	}

	return nil

}

type VpcListdhcpoptionssetsResponse struct {
	DhcpOptionsSets struct {
		DhcpOptionsSet []struct {
			Tags struct {
				Tag []struct {
					Key   string `json:"Key"`
					Value string `json:"Value"`
				} `json:"Tag"`
			} `json:"Tags"`
			DhcpOptionsSetDescription string `json:"DhcpOptionsSetDescription"`
			Status                    string `json:"Status"`
			DhcpOptionsSetId          string `json:"DhcpOptionsSetId"`
			DhcpOptionsSetName        string `json:"DhcpOptionsSetName"`
			AssociateVpcCount         int    `json:"AssociateVpcCount"`
			OwnerId                   int    `json:"OwnerId"`
			ResourceGroupId           string `json:"ResourceGroupId"`

			DhcpOptions struct {
				DomainNameServers string `json:"DomainNameServers"`
				DomainName        string `json:"DomainName"`
				LeaseTime         string `json:"LeaseTime"`
				Ipv6LeaseTime     string `json:"Ipv6LeaseTime"`
			} `json:"DhcpOptions"`
		} `json:"DhcpOptionsSet"`
	} `json:"DhcpOptionsSets"`
	RequestId  string `json:"RequestId"`
	NextToken  string `json:"NextToken"`
	TotalCount string `json:"TotalCount"`
}
