package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product VPNGateway Resouce VpnPbrRouteEntry
// generated by datasource_main.go2.jinja2
import (
	"encoding/json"
	"fmt"

	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/errmsgs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func dataSourceAlibabacloudStackVpngatewayVpnPbrRouteEntries() *schema.Resource {
	return &schema.Resource{
		Read: dataSourceAlibabacloudStackVpngatewayVpnPbrRouteEntriesRead,
		Schema: map[string]*schema.Schema{
			"ids": {
				Type:     schema.TypeList,
				Optional: true,
				Elem:     &schema.Schema{Type: schema.TypeString},
				Computed: true,
				MinItems: 1,
			},

			"vpn_gateway_id": {
				Type:     schema.TypeString,
				Required: true,
			},

			"vpn_pbr_route_entries": {
				Type:     schema.TypeList,
				Computed: true,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"id": {
							Type:     schema.TypeString,
							Computed: true,
						},

						"create_time": {
							// TypeInt
							Type:     schema.TypeInt,
							Computed: true,
						},

						"description": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"next_hop": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},
						// Interface does not have next_hop_tunnel_id, overlay_mode, publish_vpc attributes
						// "next_hop_tunnel_id": {
						// 	TypeString
						// 	Type:     schema.TypeString,
						// 	Computed: true,
						// },
						
						// "overlay_mode": {
						// 	// TypeString
						// 	Type:     schema.TypeString,
						// 	Computed: true,
						// },

						// "publish_vpc": {
						// 	// TypeBool
						// 	Type:     schema.TypeBool,
						// 	Computed: true,
						// },

						"route_dest": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"route_source": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"status": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"vpn_gateway_id": {
							// TypeString
							Type:     schema.TypeString,
							Computed: true,
						},

						"weight": {
							// TypeInt
							Type:     schema.TypeInt,
							Computed: true,
						},
					},
				},
			},
		},
	}
}

func dataSourceAlibabacloudStackVpngatewayVpnPbrRouteEntriesRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)

	// api: Vpc - 2016-04-28 - DescribeVpnPbrRouteEntries
	request := client.NewCommonRequest("POST", "Vpc", "2016-04-28", "DescribeVpnPbrRouteEntries", "")
	VpcDescribevpnpbrrouteentriesResponseObj := VpcDescribevpnpbrrouteentriesResponse{}
	request.QueryParams["VpnGatewayId"] = d.Get("vpn_gateway_id").(string)
	if v, ok := d.GetOk("region_id"); ok {
		request.QueryParams["RegionId"] = v.(string)
	}

	bresponse, err := client.ProcessCommonRequest(request)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_vpn_gateway_vpn_pbr_route_entry", "DescribeVpnPbrRouteEntries", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}

	err = json.Unmarshal(bresponse.GetHttpContentBytes(), &VpcDescribevpnpbrrouteentriesResponseObj)
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
			"alibabacloudstack_vpn_gateway_vpn_pbr_route_entry", "DescribeVpnPbrRouteEntries", errmsgs.AlibabacloudStackSdkGoERROR)
	}

	var ids []string
	datas := make([]interface{}, 0)
	for _, data := range VpcDescribevpnpbrrouteentriesResponseObj.VpnPbrRouteEntries.VpnPbrRouteEntry {

		next_hop := data.NextHop

		route_dest := data.RouteDest

		route_source := data.RouteSource

		vpn_gateway_id := data.VpnInstanceId

		weight := data.Weight

		id := fmt.Sprintf("%s_%s_%s_%s_%d", next_hop, route_dest, route_source, vpn_gateway_id, weight)

		i := map[string]interface{}{
			"id": id,

			"create_time": data.CreateTime,

			"next_hop": data.NextHop,

			// "next_hop_tunnel_id": data.NextHopTunnelId,

			"route_dest": data.RouteDest,

			"route_source": data.RouteSource,

			"status": data.State,

			"vpn_gateway_id": data.VpnInstanceId,

			"weight": data.Weight,
		}
		datas = append(datas, i)
		ids = append(ids, id)
	}

	d.SetId(dataResourceIdHash(ids))
	if err := d.Set("vpn_pbr_route_entries", datas); err != nil {
		return err
	}
	if err := d.Set("ids", ids); err != nil {
		return err
	}

	return nil

}
