package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product CEN Resouce CenInstance
import (
	"fmt"
	"strings"

	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/errmsgs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func resourceAlibabacloudStackCenTransitMulticastDomainAssociation() *schema.Resource {
	resource := &schema.Resource{
		Schema: map[string]*schema.Schema{
			"status": {
				Type:     schema.TypeString,
				Computed: true,
			},
			"transit_router_attachment_id": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
			},
			"transit_router_multicast_domain_id": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
			},
			"vswitch_id": {
				Type:     schema.TypeString,
				Required: true,
			},
		},
	}
	setResourceFunc(resource, resourceAlibabacloudStackCenTransitRouterMulticastDomainAssociationCreate,
		resourceAlibabacloudStackCenTransitRouterMulticastDomainAssociationRead,
		resourceAlibabacloudStackCenTransitRouterMulticastDomainAssociationUpdate,
		resourceAlibabacloudStackCenTransitRouterMulticastDomainAssociationDelete)
	return resource
}

func resourceAlibabacloudStackCenTransitRouterMulticastDomainAssociationCreate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	cencen_instanceservice := CenService{client}
	// api: Cbn - 2017-09-12 - CreateTransitRouterMulticastDomainAssociation
	request := client.NewCommonRequest("POST", "Cbn", "2017-09-12", "AssociateTransitRouterMulticastDomain", "")
	attachment_id := d.Get("transit_router_attachment_id").(string)
	domain_id := d.Get("transit_router_multicast_domain_id").(string)
	vswitch_id := d.Get("vswitch_id").(string)
	request.QueryParams["TransitRouterAttachmentId"] = attachment_id
	request.QueryParams["TransitRouterMulticastDomainId"] = domain_id
	request.QueryParams["VSwitchIds.1"] = vswitch_id
	bresponse, err := client.ProcessCommonRequest(request)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_cen_transit_router_multicast_domain_association", "AssociateTransitRouterMulticastDomain", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}

	d.SetId(fmt.Sprintf("%s:%s:%s", attachment_id, domain_id, vswitch_id))
	err = cencen_instanceservice.WaitForTransitRouterMulticastDomainAssociation(d.Id(), Associated, 120)
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,
			"alibabacloudstack_cen_transit_router_multicast_domain_association", "AssociateTransitRouterMulticastDomain", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, err)

	}
	return nil
}

func resourceAlibabacloudStackCenTransitRouterMulticastDomainAssociationUpdate(d *schema.ResourceData, meta interface{}) error {
	return nil
}

func resourceAlibabacloudStackCenTransitRouterMulticastDomainAssociationRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	cencen_instanceservice := CenService{client}
	parts := strings.Split(d.Id(), ":")
	attachment_id := parts[0]
	domain_id := parts[1]
	vswitch_id := parts[2]
	response, err := cencen_instanceservice.DoCbnDescribeTransitRouterMuliticastDomainAssociationsRequest(d.Id())
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg, "alibabacloudstack_cen_transit_router_multicast_domain_association", errmsgs.AlibabacloudStackSdkGoERROR)
	}
	for _, v := range response.TransitRouterMulticastAssociations {
		if v.TransitRouterAttachmentId == attachment_id && v.VSwitchId == vswitch_id && v.TransitRouterMulticastDomainId == domain_id {
			d.Set("status", v.Status)
			d.Set("transit_router_attachment_id", v.TransitRouterAttachmentId)
			d.Set("transit_router_multicast_domain_id", v.TransitRouterMulticastDomainId)
			d.Set("vswitch_id", v.VSwitchId)
			break
		}
	}

	return nil
}

func resourceAlibabacloudStackCenTransitRouterMulticastDomainAssociationDelete(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	// api: Cbn - 2017-09-12 - DeleteCen
	request := client.NewCommonRequest("POST", "Cbn", "2017-09-12", "DisassociateTransitRouterMulticastDomain", "")
	cencen_instanceservice := CenService{client}
	parts := strings.Split(d.Id(), ":")
	attachment_id := parts[0]
	domain_id := parts[1]
	vswitch_id := parts[2]
	request.QueryParams["TransitRouterAttachmentId"] = attachment_id
	request.QueryParams["TransitRouterMulticastDomainId"] = domain_id
	request.QueryParams["VSwitchIds.1"] = vswitch_id

	bresponse, err := client.ProcessCommonRequest(request)
	addDebug(request.GetActionName(), bresponse, request, request.QueryParams)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_cen_transit_router_multicast_domain_association", "DisassociateTransitRouterMulticastDomain", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}
	err = cencen_instanceservice.WaitForTransitRouterMulticastDomainAssociation(d.Id(), Deleted, 120)
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,
			"alibabacloudstack_cen_transit_router_multicast_domain_association", "DisassociateTransitRouterMulticastDomain", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, err)

	}

	return nil
}
