package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product DRDS Resouce Account
import (
	"encoding/json"
	"fmt"

	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/errmsgs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func resourceAlibabacloudStackDrdsAccount() *schema.Resource {
	return &schema.Resource{
		Create: resourceAlibabacloudStackDrdsAccountCreate,
		Read:   resourceAlibabacloudStackDrdsAccountRead,
		Update: resourceAlibabacloudStackDrdsAccountUpdate,
		Delete: resourceAlibabacloudStackDrdsAccountDelete,
		Importer: &schema.ResourceImporter{
			State: schema.ImportStatePassthrough,
		},
		Schema: map[string]*schema.Schema{

			"account_type": {
				Type:     schema.TypeInt,
				Optional: true,
				Computed: true,
			},

			"db_privileges": {
				Type:     schema.TypeList,
				Required: true,

				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{

						"db_name": {
							Type:     schema.TypeString,
							Optional: true,
						},

						"privilege": {
							Type:     schema.TypeString,
							Optional: true,
						},
					},
				},
			},

			"description": {
				Type:     schema.TypeString,
				Optional: true,
			},

			"drds_account_name": {
				Type:     schema.TypeString,
				Required: true,
			},

			"host": {
				Type:     schema.TypeString,
				Optional: true,
				Computed: true,
			},

			"instance_id": {
				Type:     schema.TypeString,
				Required: true,
			},

			"password": {
				Type:     schema.TypeString,
				Required: true,
			},
		},
	}
}

func resourceAlibabacloudStackDrdsAccountCreate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)

	// api: Drds - 2019-01-23 - CreateInstanceAccount
	request := client.NewCommonRequest("POST", "Drds", "2019-01-23", "CreateInstanceAccount", "")
	DrdsCreateinstanceaccountResponse := DrdsCreateinstanceaccountResponse{}

	//调用request_params_handler

	if v, ok := d.GetOk("db_privileges"); ok {
		db_privilegesList := v.([]interface{})
		db_privilegesValues := make([]map[string]interface{}, 0)
		for _, item := range db_privilegesList {
			itemMap := item.(map[string]interface{})
			item_data := make(map[string]interface{})

			if v, ok := itemMap["db_name"]; ok && v != "" {
				item_data["DbPrivilege[*].DbName"] = v.(string)
			}

			if v, ok := itemMap["privilege"]; ok && v != "" {
				item_data["DbPrivilege[*].Privilege"] = v.(string)
			}

			db_privilegesValues = append(db_privilegesValues, item_data)
		}
		data, _ := json.Marshal(db_privilegesValues)
		request.QueryParams["DbPrivileges"] = string(data)
	}

	if v, ok := d.GetOk("drds_account_name"); ok {
		request.QueryParams["AccountName"] = v.(string)
	} else {
		return fmt.Errorf("DrdsAccountName is required")
	}

	if v, ok := d.GetOk("instance_id"); ok {
		request.QueryParams["DrdsInstanceId"] = v.(string)
	} else {
		return fmt.Errorf("InstanceId is required")
	}

	if v, ok := d.GetOk("password"); ok {
		request.QueryParams["Password"] = v.(string)
	} else {
		return fmt.Errorf("Password is required")
	}

	bresponse, err := client.ProcessCommonRequest(request)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_drds_account", "CreateInstanceAccount", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}

	err = json.Unmarshal(bresponse.GetHttpContentBytes(), &DrdsCreateinstanceaccountResponse)
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
			"alibabacloudstack_drds_account", "CreateInstanceAccount", errmsgs.AlibabacloudStackSdkGoERROR)
	}

	drds_account_name := d.Get("drds_account_name").(string)

	instance_id := d.Get("instance_id").(string)

	d.SetId(fmt.Sprintf("%s", drds_account_name+"_"+instance_id))
	return resourceAlibabacloudStackDrdsAccountUpdate(d, meta)

}

func resourceAlibabacloudStackDrdsAccountUpdate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)

	// DrdsAccountName

	// InstanceId

	// Password

	// api: Drds - 2019-01-23 - ChangeAccountPassword
	if d.HasChanges("password") {
		request := client.NewCommonRequest("POST", "Drds", "2019-01-23", "ChangeAccountPassword", "")
		DrdsChangeaccountpasswordResponse := DrdsChangeaccountpasswordResponse{}

		if v, ok := d.GetOk("drds_account_name"); ok {
			request.QueryParams["AccountName"] = v.(string)
		} else {
			return fmt.Errorf("DrdsAccountName is required")
		}

		if v, ok := d.GetOk("instance_id"); ok {
			request.QueryParams["DrdsInstanceId"] = v.(string)
		} else {
			return fmt.Errorf("InstanceId is required")
		}

		if v, ok := d.GetOk("password"); ok {
			request.QueryParams["Password"] = v.(string)
		} else {
			return fmt.Errorf("Password is required")
		}

		bresponse, err := client.ProcessCommonRequest(request)
		if err != nil {
			if bresponse == nil {
				return errmsgs.WrapErrorf(err, "Process Common Request Failed")
			}
			errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
			return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,
				"alibabacloudstack_drds_account", "ChangeAccountPassword", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
		}

		err = json.Unmarshal(bresponse.GetHttpContentBytes(), &DrdsChangeaccountpasswordResponse)
		if err != nil {
			return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
				"alibabacloudstack_drds_account", "ChangeAccountPassword", errmsgs.AlibabacloudStackSdkGoERROR)
		}

	}

	// Description

	// DrdsAccountName

	// InstanceId

	// api: Drds - 2019-01-23 - ModifyAccountDescription
	if d.HasChanges("description") {
		request := client.NewCommonRequest("POST", "Drds", "2019-01-23", "ModifyAccountDescription", "")
		DrdsModifyaccountdescriptionResponse := DrdsModifyaccountdescriptionResponse{}

		if v, ok := d.GetOk("description"); ok {
			request.QueryParams["Description"] = v.(string)
		} else {
			return fmt.Errorf("Description is required")
		}

		if v, ok := d.GetOk("drds_account_name"); ok {
			request.QueryParams["AccountName"] = v.(string)
		} else {
			return fmt.Errorf("DrdsAccountName is required")
		}

		if v, ok := d.GetOk("instance_id"); ok {
			request.QueryParams["DrdsInstanceId"] = v.(string)
		} else {
			return fmt.Errorf("InstanceId is required")
		}

		bresponse, err := client.ProcessCommonRequest(request)
		if err != nil {
			if bresponse == nil {
				return errmsgs.WrapErrorf(err, "Process Common Request Failed")
			}
			errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
			return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,
				"alibabacloudstack_drds_account", "ModifyAccountDescription", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
		}

		err = json.Unmarshal(bresponse.GetHttpContentBytes(), &DrdsModifyaccountdescriptionResponse)
		if err != nil {
			return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
				"alibabacloudstack_drds_account", "ModifyAccountDescription", errmsgs.AlibabacloudStackSdkGoERROR)
		}

	}

	// DbPrivileges

	// DrdsAccountName

	// InstanceId

	// api: Drds - 2019-01-23 - ModifyAccountPrivilege
	if d.HasChanges("db_privileges") {
		request := client.NewCommonRequest("POST", "Drds", "2019-01-23", "ModifyAccountPrivilege", "")
		DrdsModifyaccountprivilegeResponse := DrdsModifyaccountprivilegeResponse{}

		if v, ok := d.GetOk("db_privileges"); ok {
			db_privilegesList := v.([]interface{})
			db_privilegesValues := make([]map[string]interface{}, 0)
			for _, item := range db_privilegesList {
				itemMap := item.(map[string]interface{})
				item_data := make(map[string]interface{})

				if v, ok := itemMap["db_name"]; ok && v != "" {
					item_data["DbPrivilege[*].DbName"] = v.(string)
				}

				if v, ok := itemMap["privilege"]; ok && v != "" {
					item_data["DbPrivilege[*].Privilege"] = v.(string)
				}

				db_privilegesValues = append(db_privilegesValues, item_data)
			}
			data, _ := json.Marshal(db_privilegesValues)
			request.QueryParams["DbPrivileges"] = string(data)
		}

		if v, ok := d.GetOk("drds_account_name"); ok {
			request.QueryParams["AccountName"] = v.(string)
		} else {
			return fmt.Errorf("DrdsAccountName is required")
		}

		if v, ok := d.GetOk("instance_id"); ok {
			request.QueryParams["DrdsInstanceId"] = v.(string)
		} else {
			return fmt.Errorf("InstanceId is required")
		}

		bresponse, err := client.ProcessCommonRequest(request)
		if err != nil {
			if bresponse == nil {
				return errmsgs.WrapErrorf(err, "Process Common Request Failed")
			}
			errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
			return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,
				"alibabacloudstack_drds_account", "ModifyAccountPrivilege", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
		}

		err = json.Unmarshal(bresponse.GetHttpContentBytes(), &DrdsModifyaccountprivilegeResponse)
		if err != nil {
			return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
				"alibabacloudstack_drds_account", "ModifyAccountPrivilege", errmsgs.AlibabacloudStackSdkGoERROR)
		}

	}

	return resourceAlibabacloudStackDrdsAccountRead(d, meta)
}

func resourceAlibabacloudStackDrdsAccountRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	drdsaccountservice := DrdsService{client}
	response, err := drdsaccountservice.DoDrdsDescribeinstanceaccountsRequest(d.Id())
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg, "alibabacloudstack_drds_account", errmsgs.AlibabacloudStackSdkGoERROR)
	}
	data := response.InstanceAccounts.InstanceAccount[0]
	d.Set("account_type", data.AccountType)

	d.Set("description", data.Description)

	d.Set("drds_account_name", data.AccountName)

	d.Set("host", data.Host)

	return nil
}

func resourceAlibabacloudStackDrdsAccountDelete(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	// api: Drds - 2019-01-23 - RemoveInstanceAccount
	request := client.NewCommonRequest("POST", "Drds", "2019-01-23", "RemoveInstanceAccount", "")
	DrdsRemoveinstanceaccountResponse := DrdsRemoveinstanceaccountResponse{}

	//调用request_params_handler

	if v, ok := d.GetOk("drds_account_name"); ok {
		request.QueryParams["AccountName"] = v.(string)
	} else {
		return fmt.Errorf("DrdsAccountName is required")
	}

	if v, ok := d.GetOk("instance_id"); ok {
		request.QueryParams["DrdsInstanceId"] = v.(string)
	} else {
		return fmt.Errorf("InstanceId is required")
	}

	bresponse, err := client.ProcessCommonRequest(request)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_drds_account", "RemoveInstanceAccount", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}

	err = json.Unmarshal(bresponse.GetHttpContentBytes(), &DrdsRemoveinstanceaccountResponse)
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
			"alibabacloudstack_drds_account", "RemoveInstanceAccount", errmsgs.AlibabacloudStackSdkGoERROR)
	}

	return nil
}

type DrdsCreateinstanceaccountResponse struct {
	RequestId string `json:"RequestId"`
	Success   bool   `json:"Success"`
}

type DrdsChangeaccountpasswordResponse struct {
	RequestId string `json:"RequestId"`
	Success   bool   `json:"Success"`
}
type DrdsModifyaccountdescriptionResponse struct {
	RequestId string `json:"RequestId"`
	Success   bool   `json:"Success"`
}
type DrdsModifyaccountprivilegeResponse struct {
	RequestId string `json:"RequestId"`
	Success   bool   `json:"Success"`
}

type DrdsRemoveinstanceaccountResponse struct {
	RequestId string `json:"RequestId"`
	Success   bool   `json:"Success"`
}
