package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product CEN Resouce CenInstance
import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/errmsgs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func resourceAlibabacloudStackCenTransitMulticastDomain() *schema.Resource {
	resource := &schema.Resource{
		Schema: map[string]*schema.Schema{
			"status": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The status of the multicast domain.",
			},
			"transit_router_id": {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: "The ID of the transit router.",
			},
			"transit_router_multicast_domain_description": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "The description of the transit router multicast domain.",
			},
			"transit_router_multicast_domain_id": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The ID of the transit router multicast domain.",
			},
			"transit_router_multicast_domain_name": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "The name of the transit router multicast domain.",
			},
			"tags": {
				Type:     schema.TypeSet,
				Optional: true,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"tag_key": {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "The key of the tag.",
						},
						"tag_value": {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "The value of the tag.",
						},
					},
				},
				Description: "The tags of the transit router multicast domain.",
			},
		},
	}
	setResourceFunc(resource, resourceAlibabacloudStackCenTransitRouterMulticastDomainCreate,
		resourceAlibabacloudStackCenTransitRouterMulticastDomainRead,
		resourceAlibabacloudStackCenTransitRouterMulticastDomainUpdate,
		resourceAlibabacloudStackCenTransitRouterMulticastDomainDelete)
	return resource
}

func resourceAlibabacloudStackCenTransitRouterMulticastDomainCreate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	cencen_instanceservice := CenService{client}
	// api: Cbn - 2017-09-12 - CreateTransitRouterMulticastDomain
	request := client.NewCommonRequest("POST", "Cbn", "2017-09-12", "CreateTransitRouterMulticastDomain", "")
	CbnCreateTransitRouterMulticastDomainResponseObj := CbnCreateTransitRouterMulticastDomainResponse{}
	request.QueryParams["TransitRouterId"] = d.Get("transit_router_id").(string)
	if v, ok := d.GetOk("transit_router_multicast_domain_name"); ok {
		request.QueryParams["TransitRouterMulticastDomainName"] = v.(string)
	}
	if v, ok := d.GetOk("transit_router_multicast_domain_description"); ok {
		request.QueryParams["TransitRouterMulticastDomainDescription"] = v.(string)
	}
	bresponse, err := client.ProcessCommonRequest(request)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_cen_transit_router_multicast_domain", "CreateTransitRouterMulticastDomain", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}

	err = json.Unmarshal(bresponse.GetHttpContentBytes(), &CbnCreateTransitRouterMulticastDomainResponseObj)
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
			"alibabacloudstack_cen_transit_router_multicast_domain", "CreateTransitRouterMulticastDomain", errmsgs.AlibabacloudStackSdkGoERROR)
	}

	transit_router_multicast_domain_id := CbnCreateTransitRouterMulticastDomainResponseObj.TransitRouterMulticastDomainId

	d.SetId(fmt.Sprintf("%s:%s", d.Get("transit_router_id").(string), transit_router_multicast_domain_id))
	err = cencen_instanceservice.WaitForTransitRouterMulticastDomain(d.Id(), Active, 120)
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,
			"alibabacloudstack_cen_transit_router_multicast_domain", "CreateTransitRouterMulticastDomain", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, err)

	}
	return nil
}

func resourceAlibabacloudStackCenTransitRouterMulticastDomainUpdate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	// api: Cbn - 2017-09-12 - ModifyCenAttribute
	if d.HasChanges("transit_router_multicast_domain_name", "transit_router_multicast_domain_description") {
		request := client.NewCommonRequest("POST", "Cbn", "2017-09-12", "ModifyTransitRouterMulticastDomain", "")
		// CbnModifycenattributeResponseObj := CbnModifycenattributeResponse{}

		if v, ok := d.GetOk("transit_router_multicast_domain_name"); ok {
			request.QueryParams["TransitRouterRouteTableName"] = v.(string)
		}
		if v, ok := d.GetOk("transit_router_multicast_domain_description"); ok {
			request.QueryParams["TransitRouterRouteTableDescription"] = v.(string)
		}
		parts := strings.Split(d.Id(), ":")
		domain_id := parts[1]
		request.QueryParams["TransitRouterMulticastDomainId"] = domain_id
		bresponse, err := client.ProcessCommonRequest(request)
		addDebug(request.GetActionName(), bresponse, request, request.QueryParams)
		if err != nil {
			if bresponse == nil {
				return errmsgs.WrapErrorf(err, "Process Common Request Failed")
			}
			errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
			return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,
				"alibabacloudstack_cen_transit_router_multicast_domain", "ModifyTransitRouterMulticastDomain", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
		}
	}
	return nil
}

func resourceAlibabacloudStackCenTransitRouterMulticastDomainRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	cencen_instanceservice := CenService{client}
	response, err := cencen_instanceservice.DoCbnDescribeTransitRouterMuliticastDomainsRequest(d.Id())
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg, "alibabacloudstack_cen_transit_router_multicast_domain", errmsgs.AlibabacloudStackSdkGoERROR)
	}
	parts := strings.Split(d.Id(), ":")
	domain_id := parts[1]
	for _, v := range response.TransitRouterMulticastDomains {
		if v.TransitRouterMulticastDomainId == domain_id {
			d.Set("status", v.Status)
			d.Set("transit_router_multicast_domain_id", v.TransitRouterMulticastDomainId)
			if v.TransitRouterMulticastDomainName != "" {
				d.Set("transit_router_multicast_domain_name", v.TransitRouterMulticastDomainName)
			}
			if v.TransitRouterMulticastDomainDescription != "" {
				d.Set("transit_router_multicast_domain_description", v.TransitRouterMulticastDomainDescription)
			}
			d.Set("transit_router_id", v.TransitRouterId)
			break
		}
	}

	return nil
}

func resourceAlibabacloudStackCenTransitRouterMulticastDomainDelete(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	// api: Cbn - 2017-09-12 - DeleteCen
	request := client.NewCommonRequest("POST", "Cbn", "2017-09-12", "DeleteTransitRouterMulticastDomain", "")
	// CbnDeletecenResponseObj := CbnDeletecenResponse{}
	parts := strings.Split(d.Id(), ":")
	domain_id := parts[1]
	request.QueryParams["TransitRouterMulticastDomainId"] = domain_id

	bresponse, err := client.ProcessCommonRequest(request)
	addDebug(request.GetActionName(), bresponse, request, request.QueryParams)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_cen_transit_router_multicast_domain", "DeleteTransitRouterMulticastDomain", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}

	return nil
}

type CbnCreateTransitRouterMulticastDomainResponse struct {
	TransitRouterMulticastDomainId string `json:"TransitRouterMulticastDomainId"`
	RequestId                      string `json:"RequestId"`
}
