package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product DRDS Resouce polardbx_instance
import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func resourceAlibabacloudStackPolardbxReadonlyInstance() *schema.Resource {
	resource := resourceAlibabacloudStackPolardbxInstance()
	resource.Schema["primary_db_instance_id"]= &schema.Schema{
		Type:     schema.TypeString,
		Required: true,
		ForceNew: true,
	}
	return resource
}

