package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product DRDS Resouce Account
import (
	"fmt"
	"log"

	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/errmsgs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
)

func resourceAlibabacloudStackPolardbxAccountDatabaseBinding() *schema.Resource {
	resource := &schema.Resource{
		Schema: map[string]*schema.Schema{

			"instance_id": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
			},

			"account_name": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
			},
			"db_privileges": {
				Type:     schema.TypeSet,
				Required: true,
				MinItems: 1,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"db_name": {
							Type:     schema.TypeString,
							Required: true,
						},
						"privilege": {
							Type:         schema.TypeString,
							Required:     true,
							ValidateFunc: validation.StringInSlice([]string{"ReadOnly", "ReadWrite", "DMLOnly", "DDLOnly"}, false),
						},
					},
				},
			},
		},
	}
	setResourceFunc(resource, resourceAlibabacloudStackPolardbxAccountDatabaseBindingCreate, resourceAlibabacloudStackPolardbxAccountDatabaseBindingRead, resourceAlibabacloudStackPolardbxAccountDatabaseBindingUpdate, resourceAlibabacloudStackPolardbxAccountDatabaseBindingDelete)
	return resource
}

func resourceAlibabacloudStackPolardbxAccountDatabaseBindingCreate(d *schema.ResourceData, meta interface{}) error {
	accountName := d.Get("account_name").(string)
	instanceID := d.Get("instance_id").(string)
	id := fmt.Sprintf("%s:%s", instanceID, accountName)
	log.Printf("[DEBUG] alibabacloudstack_polardbx_account_database_binding id:%s $#########################################", id)
	d.SetId(id)
	return nil
}

func resourceAlibabacloudStackPolardbxAccountDatabaseBindingUpdate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	privileges := d.Get("db_privileges").(*schema.Set).List()
	Polardbxservice := PolardbXService{client}
	return Polardbxservice.PolardbxAccountDatabaseBinding(d.Id(), privileges)
}

func resourceAlibabacloudStackPolardbxAccountDatabaseBindingRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	Polardbxservice := PolardbXService{client}
	privilege, err := Polardbxservice.DescribePolardbXAccountDBPrivilege(d.Id())
	if err != nil {
		return errmsgs.WrapError(err)
	}
	var instanceId, AccountName string
	if parts, err := ParseResourceId(d.Id(), 2); err != nil {
		return err
	} else {
		instanceId = parts[0]
		AccountName = parts[1]
	}
	d.Set("instance_id", instanceId)
	d.Set("account_name", AccountName)
	d.Set("db_privileges", privilege)
	return nil
}

func resourceAlibabacloudStackPolardbxAccountDatabaseBindingDelete(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	db_privileges := d.Get("db_privileges").(*schema.Set).List()
	if len(db_privileges) == 0 {
		return nil
	}
	db_privilege := db_privileges[0].(map[string]interface{})
	db_name := db_privilege["db_name"].(string)
	Polardbxservice := PolardbXService{client}
	privilege_data := []interface{}{
		map[string]interface{}{
			"db_name":   db_name,
			"privilege": "none",
		},
	}
	return Polardbxservice.PolardbxAccountDatabaseBinding(d.Id(), privilege_data)
}
