package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product DRDS Resouce Account
import (
	"fmt"
	"time"

	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/errmsgs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func resourceAlibabacloudStackPolardbxSuperAccount() *schema.Resource {
	resource := &schema.Resource{
		Schema: map[string]*schema.Schema{

			"instance_id": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
			},

			"admin_account_name": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
			},

			"admin_account_description": {
				Type:     schema.TypeString,
				Optional: true,
				Computed: true,
			},

			"admin_account_password": {
				Type:      schema.TypeString,
				Required:  true,
				Sensitive: true,
			},

			"security_account_name": {
				Type:         schema.TypeString,
				Optional:     true,
				RequiredWith: []string{"audit_account_name"},
			},

			"security_account_description": {
				Type:     schema.TypeString,
				Optional: true,
				Computed: true,
			},

			"security_account_password": {
				Type:         schema.TypeString,
				Optional:     true,
				Sensitive:    true,
				RequiredWith: []string{"security_account_name"},
			},

			"audit_account_name": {
				Type:         schema.TypeString,
				Optional:     true,
				RequiredWith: []string{"security_account_name"},
			},

			"audit_account_description": {
				Type:         schema.TypeString,
				Optional:     true,
				Computed:     true,
				RequiredWith: []string{"audit_account_name"},
			},

			"audit_account_password": {
				Type:         schema.TypeString,
				Optional:     true,
				Sensitive:    true,
				RequiredWith: []string{"audit_account_name"},
			},

			"three_roles": {
				Type:     schema.TypeBool,
				Computed: true,
			},
		},
	}
	setResourceFunc(resource, resourceAlibabacloudStackPolardbxSuperAccountCreate, resourceAlibabacloudStackPolardbxSuperAccountRead, resourceAlibabacloudStackPolardbxSuperAccountUpdate, resourceAlibabacloudStackPolardbxSuperAccountDelete)
	return resource
}

func resourceAlibabacloudStackPolardbxSuperAccountCreate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	polardbxService := PolardbXService{client}

	instanceId := d.Get("instance_id").(string)

	reqQuery := map[string]interface{}{
		"DBInstanceName":     instanceId,
		"AccountName":        d.Get("admin_account_name").(string),
		"AccountType":        "Super",
		"AccountPassword":    d.Get("admin_account_password").(string),
		"AccountDescription": d.Get("admin_account_description").(string),
	}
	if _, err := client.DoTeaRequest("POST", "polardbx", "2020-02-02", "CreateSuperAccount", "", nil, reqQuery, nil); err != nil {
		return err
	}

	if _, ok := d.GetOk("security_account_name"); ok {
		reqQuery := map[string]interface{}{
			"SecurityAccountName":        d.Get("security_account_name").(string),
			"SecurityAccountPassword":    d.Get("security_account_password").(string),
			"SecurityAccountDescription": d.Get("security_account_description").(string),
			"AuditAccountName":           d.Get("audit_account_name").(string),
			"AuditAccountPassword":       d.Get("audit_account_password").(string),
			"AuditAccountDescription":    d.Get("audit_account_description").(string),
			"DBInstanceName":             instanceId,
		}
		if _, err := client.DoTeaRequest("POST", "polardbx", "2020-02-02", "EnableRightsSeparation", "", nil, reqQuery, nil); err != nil {
			return err
		}
		stateConf := BuildStateConf([]string{"CONFIG_SWITCHING"}, []string{"Running"}, d.Timeout(schema.TimeoutUpdate), 10*time.Second, polardbxService.PolardbxDescribedbinstanceStateRefreshFunc(instanceId, []string{"Failed"}))
		if _, err := stateConf.WaitForState(); err != nil {
			if errmsgs.NotFoundError(err) {
				return nil
			}
			return errmsgs.WrapErrorf(err, errmsgs.IdMsg, d.Id())
		}
	}

	d.SetId(instanceId)
	return nil

}

func resourceAlibabacloudStackPolardbxSuperAccountUpdate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	polardbxService := PolardbXService{client}

	instanceId := d.Id()

	if d.IsNewResource() {
		return nil
	}

	if d.HasChange("admin_account_name") {
		return fmt.Errorf("admin_account_name can not be changed")
	}

	if d.HasChanges("admin_account_description") {
		if err := polardbxService.ModifyAccountDescription(instanceId, d.Get("admin_account_name").(string), d.Get("admin_account_description").(string)); err != nil {
			return err
		}
	}

	if d.HasChanges("admin_account_password") {
		if err := polardbxService.ModifyAccountPassword(instanceId, d.Get("admin_account_name").(string), d.Get("admin_account_password").(string)); err != nil {
			return err
		}
	}

	if d.HasChanges("security_account_name", "audit_account_name") {
		old_s, new_s := d.GetChange("security_account_name")
		old_a, new_a := d.GetChange("audit_account_name")
		if old_s != "" || old_a != "" {
			reqQuery := map[string]interface{}{
				"DBInstanceName":     instanceId,
				"DbaAccountName":     d.Get("admin_account_name").(string),
				"DbaAccountPassword": d.Get("admin_account_password").(string),
			}
			if _, err := client.DoTeaRequest("POST", "polardbx", "2020-02-02", "DisableRightsSeparation", "", nil, reqQuery, nil); err != nil {
				return err
			}
			stateConf := BuildStateConf([]string{"CONFIG_SWITCHING"}, []string{"Running"}, d.Timeout(schema.TimeoutUpdate), 10*time.Second, polardbxService.PolardbxDescribedbinstanceStateRefreshFunc(instanceId, []string{"Failed"}))
			if _, err := stateConf.WaitForState(); err != nil {
				if errmsgs.NotFoundError(err) {
					return nil
				}
				return errmsgs.WrapErrorf(err, errmsgs.IdMsg, d.Id())
			}
		}

		if new_s != "" || new_a != "" {
			reqQuery := map[string]interface{}{
				"SecurityAccountName":        d.Get("security_account_name").(string),
				"SecurityAccountPassword":    d.Get("security_account_password").(string),
				"SecurityAccountDescription": d.Get("security_account_description").(string),
				"AuditAccountName":           d.Get("audit_account_name").(string),
				"AuditAccountPassword":       d.Get("audit_account_password").(string),
				"AuditAccountDescription":    d.Get("audit_account_description").(string),
				"DBInstanceName":             instanceId,
			}
			if _, err := client.DoTeaRequest("POST", "polardbx", "2020-02-02", "EnableRightsSeparation", "", nil, reqQuery, nil); err != nil {
				return err
			}
			stateConf := BuildStateConf([]string{"CONFIG_SWITCHING"}, []string{"Running"}, d.Timeout(schema.TimeoutUpdate), 10*time.Second, polardbxService.PolardbxDescribedbinstanceStateRefreshFunc(instanceId, []string{"Failed"}))
			if _, err := stateConf.WaitForState(); err != nil {
				if errmsgs.NotFoundError(err) {
					return nil
				}
				return errmsgs.WrapErrorf(err, errmsgs.IdMsg, d.Id())
			}
		}
	} else if v, ok := d.GetOk("security_account_name"); ok && v.(string) != "" {
		if d.HasChange("security_account_password") {
			if err := polardbxService.ModifyAccountPassword(instanceId, d.Get("security_account_name").(string), d.Get("security_account_password").(string)); err != nil {
				return err
			}
		}
		if d.HasChange("audit_account_password") {
			if err := polardbxService.ModifyAccountPassword(instanceId, d.Get("audit_account_name").(string), d.Get("audit_account_password").(string)); err != nil {
				return err
			}
		}
		if d.HasChanges("security_account_description") {
			if err := polardbxService.ModifyAccountDescription(instanceId, d.Get("security_account_name").(string), d.Get("security_account_description").(string)); err != nil {
				return err
			}
		}
		if d.HasChanges("audit_account_description") {
			if err := polardbxService.ModifyAccountDescription(instanceId, d.Get("audit_account_name").(string), d.Get("audit_account_description").(string)); err != nil {
				return err
			}
		}
	}

	return nil
}

func resourceAlibabacloudStackPolardbxSuperAccountRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	polardbxService := PolardbXService{client}
	d.Set("instance_id", d.Id())
	if accounts, err := polardbxService.DoPolardbxDescribeSuperAccountRequest(d.Id()); err != nil {
		return err
	} else {
		d.Set("admin_account_name", accounts[0].AccountName)
		d.Set("admin_account_description", accounts[0].AccountDescription)
		if len(accounts) == 1 {
			d.Set("three_roles", false)
		} else {
			d.Set("three_roles", true)
			d.Set("security_account_name", accounts[1].AccountName)
			d.Set("security_account_description", accounts[1].AccountDescription)
			d.Set("audit_account_name", accounts[2].AccountName)
			d.Set("audit_account_description", accounts[2].AccountDescription)
		}
	}

	return nil
}

func resourceAlibabacloudStackPolardbxSuperAccountDelete(d *schema.ResourceData, meta interface{}) error {
	return nil
}
