package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product PolarDB Resouce Backup
import (
	"encoding/json"
	"fmt"
	"strconv"
	"time"

	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/errmsgs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func resourceAlibabacloudStackPolardbxBackup() *schema.Resource {
	resource := &schema.Resource{
		Schema: map[string]*schema.Schema{
			"backup_model": {
				Type:     schema.TypeInt,
				Computed: true,
			},

			"backup_set_size": {
				Type:     schema.TypeInt,
				Computed: true,
			},

			"backup_type": {
				Type:     schema.TypeInt,
				Optional: true,
				ForceNew: true,
				Default:  0,
			},

			"backup_set_id": {
				Type:     schema.TypeInt,
				Computed: true,
			},

			"status": {
				Type:     schema.TypeInt,
				Computed: true,
			},

			"instance_id": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
			},

			"end_time": {
				Type:     schema.TypeString,
				Computed: true,
			},

			"begin_time": {
				Type:     schema.TypeString,
				Computed: true,
			},
		},
	}
	setResourceFunc(resource, resourceAlibabacloudStackPolardbxBackupCreate,
		resourceAlibabacloudStackPolardbxBackupRead,
		nil,
		resourceAlibabacloudStackPolardbxBackupDelete)
	return resource
}

func resourceAlibabacloudStackPolardbxBackupCreate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	instance_id := d.Get("instance_id").(string)
	polardbx_service := PolardbXService{client}
	task_exists, err := polardbx_service.CheckPolarDbXBackupTaskExists(instance_id)
	if err != nil {
		return err
	}
	if task_exists {
		return errmsgs.WrapError(errmsgs.Error("There are already backup tasks in progress."))
	}
	// api: polardb - 2017-08-01 - CreateBackup
	request := client.NewCommonRequest("POST", "polardbx", "2020-02-02", "CreateBackup", "")
	PolardbXCreatebackupResponseObj := PolardbXCreatebackupResponse{}

	//调用request_params_handler

	request.QueryParams["DBInstanceName"] = instance_id
	request.QueryParams["BackupType"] = fmt.Sprint(d.Get("backup_type").(int))
	bresponse, err := client.ProcessCommonRequest(request)
	addDebug(request.GetActionName(), bresponse, request, request.QueryParams)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_polardbx_backup", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}

	err = json.Unmarshal(bresponse.GetHttpContentBytes(), &PolardbXCreatebackupResponseObj)
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
			"alibabacloudstack_polardbx_backup", "CreateBackup", errmsgs.AlibabacloudStackSdkGoERROR)
	}
	db_instance_id := d.Get("instance_id").(string)
	backup_set_id := PolardbXCreatebackupResponseObj.Data.BackupSetId
	buckup_id := fmt.Sprintf("%s:%d", db_instance_id, backup_set_id)
	d.SetId(buckup_id)
	stateConf := BuildStateConf([]string{"0"}, []string{"1"}, d.Timeout(schema.TimeoutCreate), 10*time.Second, polardbx_service.DescribePolarDbXBackupStateRefreshFunc(buckup_id, []string{"2"}))
	if _, err := stateConf.WaitForState(); err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.IdMsg, d.Id())
	}
	return nil
}

func resourceAlibabacloudStackPolardbxBackupRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	polardbx_service := PolardbXService{client}
	var instanceId string
	if parts, err := ParseResourceId(d.Id(), 2); err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg, "alibabacloudstack_polardbx_backup", errmsgs.AlibabacloudStackSdkGoERROR)
	} else {
		instanceId = parts[0]
	}
	data, err := polardbx_service.DescribePolarDbXBackup(d.Id())
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg, "alibabacloudstack_polardbx_backup", errmsgs.AlibabacloudStackSdkGoERROR)
	}
	d.Set("backup_model", data.BackupModel)
	d.Set("instance_id", instanceId)
	backup_set_id, _ := strconv.Atoi(data.BackupSetId)
	d.Set("backup_set_id", backup_set_id)
	d.Set("backup_type", data.BackupType)
	d.Set("backup_set_size", data.BackupSetSize)
	d.Set("status", data.Status)
	d.Set("end_time", TimeStampFormat(data.EndTime))
	d.Set("begin_time", TimeStampFormat(data.BeginTime))
	return nil
}

func resourceAlibabacloudStackPolardbxBackupDelete(d *schema.ResourceData, meta interface{}) error {
	return nil
}

type PolardbXCreatebackupResponse struct {
	RequestId string `json:"RequestId"`
	Data      struct {
		BackupSetId int `json:"BackupSetId"`
	} `json:"Data"`
}

func TimeStampFormat(timestamp int) string {
	loc, _ := time.LoadLocation("Asia/Shanghai")
	tLocal := time.Unix(0, int64(timestamp*1000000)).In(loc)
	dateTimeStrLocal := tLocal.Format("2006-01-02 15:04:05 MST")
	return dateTimeStrLocal
}
