package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product CEN Resouce CenInstance
import (
	"encoding/json"
	"fmt"
	"log"
	"time"

	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/errmsgs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func resourceAlibabacloudStackCenCeninstance() *schema.Resource {
	resource := &schema.Resource{
		Schema: map[string]*schema.Schema{
			"cen_bandwidth_package_ids": {
				Type:     schema.TypeList,
				Elem:     &schema.Schema{Type: schema.TypeString},
				Computed: true,
			},
			"cen_id": {
				Type:     schema.TypeString,
				Computed: true,
			},
			"cen_instance_name": {
				Type:     schema.TypeString,
				Optional: true,
			},
			"create_time": {
				Type:     schema.TypeString,
				Computed: true,
			},
			"description": {
				Type:     schema.TypeString,
				Optional: true,
			},
			"protection_level": {
				Type:     schema.TypeString,
				Optional: true,
				Default:  "REDUCED",
			},
			"status": {
				Type:     schema.TypeString,
				Optional: true,
				Computed: true,
			},
			"transit_router_name": {
				Type:     schema.TypeString,
				Optional: true,
			},
			"transit_router_description": {
				Type:     schema.TypeString,
				Optional: true,
			},
			"transit_router_cidrs": {
				Type:     schema.TypeSet,
				Optional: true,
				Elem:     &schema.Schema{Type: schema.TypeString},
			},
			"transit_router_id": {
				Type:     schema.TypeString,
				Computed: true,
			},
			"tags": tagsSchema(),
		},
	}
	setResourceFunc(resource, resourceAlibabacloudStackCenCeninstanceCreate,
		resourceAlibabacloudStackCenCeninstanceRead,
		resourceAlibabacloudStackCenCeninstanceUpdate,
		resourceAlibabacloudStackCenCeninstanceDelete)
	return resource
}

func resourceAlibabacloudStackCenCeninstanceCreate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)

	// api: Cbn - 2017-09-12 - CreateCen
	request := client.NewCommonRequest("POST", "Cbn", "2017-09-12", "CreateCen", "")
	CbnCreatecenResponseObj := CbnCreatecenResponse{}

	if v, ok := d.GetOk("cen_instance_name"); ok {
		request.QueryParams["Name"] = v.(string)
	}

	if v, ok := d.GetOk("description"); ok {
		request.QueryParams["Description"] = v.(string)
	}

	if v, ok := d.GetOk("protection_level"); ok {
		request.QueryParams["ProtectionLevel"] = v.(string)
	}

	tags := d.Get("tags").(map[string]interface{})
	if tags != nil && len(tags) > 0 {
		Tags := make([]map[string]string, 0, len(tags))
		for k, v := range tags {
			Tag := map[string]string{
				"Key":   k,
				"Value": v.(string),
			}
			Tags = append(Tags, Tag)
		}
		request_byte, _ := json.Marshal(Tags)
		requeststring := string(request_byte)
		request.QueryParams["Tags"] = requeststring
	}

	bresponse, err := client.ProcessCommonRequest(request)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_cen_cen_instance", "CreateCen", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}

	err = json.Unmarshal(bresponse.GetHttpContentBytes(), &CbnCreatecenResponseObj)
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
			"alibabacloudstack_cen_cen_instance", "CreateCen", errmsgs.AlibabacloudStackSdkGoERROR)
	}

	cen_id := CbnCreatecenResponseObj.CenId

	d.SetId(fmt.Sprintf("%s", cen_id))
	return nil
}

func resourceAlibabacloudStackCenCeninstanceUpdate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	cencen_instanceservice := CenService{client}
	// api: Cbn - 2017-09-12 - ModifyCenAttribute
	if d.HasChanges("cen_instance_name", "description") {
		request := client.NewCommonRequest("POST", "Cbn", "2017-09-12", "ModifyCenAttribute", "")
		// CbnModifycenattributeResponseObj := CbnModifycenattributeResponse{}

		request.QueryParams["CenId"] = d.Id()

		if v, ok := d.GetOk("cen_instance_name"); ok {
			request.QueryParams["Name"] = v.(string)
		}

		if v, ok := d.GetOk("description"); ok {
			request.QueryParams["Description"] = v.(string)
		}

		bresponse, err := client.ProcessCommonRequest(request)
		addDebug(request.GetActionName(), bresponse, request, request.QueryParams)
		if err != nil {
			if bresponse == nil {
				return errmsgs.WrapErrorf(err, "Process Common Request Failed")
			}
			errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
			return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,
				"alibabacloudstack_cen_cen_instance", "ModifyCenAttribute", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
		}
	}
	if d.HasChanges("transit_router_name", "transit_router_description", "transit_router_cidrs") {
		response_transitrouter, err := cencen_instanceservice.DoCbnDescribeTransitRoutersRequest(d.Id())
		if err != nil {
			return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg, "alibabacloudstack_cen_ceninstance", errmsgs.AlibabacloudStackSdkGoERROR)
		}
		if len(response_transitrouter.TransitRouters) == 0 {
			request := client.NewCommonRequest("POST", "Cbn", "2017-09-12", "CreateTransitRouter", "")
			request.QueryParams["CenId"] = d.Id()
			bresponse, err := client.ProcessCommonRequest(request)
			addDebug(request.GetActionName(), bresponse, request, request.QueryParams)
			if err != nil {
				if bresponse == nil {
					return errmsgs.WrapErrorf(err, "Process Common Request Failed")
				}
				errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
				return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,
					"alibabacloudstack_cen_cen_instance", "CreateTransitRouter", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
			}
			if err := cencen_instanceservice.WaitForTransitRouterInstance(d.Id(), Active, 120); err != nil {
				return errmsgs.WrapError(err)
			}
			// cencen_instanceservice.WaitForTransitRouterInstance(d.Id())
		}
		transitrouter_id := ""
		for i := 0; i < 10; i++ {
			response_transitrouter, err = cencen_instanceservice.DoCbnDescribeTransitRoutersRequest(d.Id())
			if err != nil {
				return errmsgs.WrapErrorf(err, "DoCbnDescribeTransitRoutersRequest")
			}
			if len(response_transitrouter.TransitRouters) > 0 {
				transitrouter_id = response_transitrouter.TransitRouters[0].TransitRouterId
				break
			}
			time.Sleep(time.Duration(2) * time.Second)
		}
		cidrs_map := make(map[string]string)
		for _, cidr := range response_transitrouter.TransitRouters[0].TransitRouterCidrList {
			cidrs_map[cidr.Cidr] = cidr.TransitRouterCidrId
		}
		if err != nil {
			return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg, "alibabacloudstack_cen_ceninstance", errmsgs.AlibabacloudStackSdkGoERROR)
		}
		log.Printf("cidrs_map: %v", cidrs_map)
		if d.HasChanges("transit_router_name", "transit_router_description") {
			request := client.NewCommonRequest("POST", "Cbn", "2017-09-12", "UpdateTransitRouter", "")
			request.QueryParams["TransitRouterId"] = transitrouter_id
			if v, ok := d.GetOk("transit_router_description"); ok {
				request.QueryParams["TransitRouterDescription"] = v.(string)
			}
			if v, ok := d.GetOk("transit_router_name"); ok {
				request.QueryParams["TransitRouterName"] = v.(string)
			}
			bresponse, err := client.ProcessCommonRequest(request)
			addDebug(request.GetActionName(), bresponse, request, request.QueryParams)
			if err != nil {
				if bresponse == nil {
					return errmsgs.WrapErrorf(err, "Process Common Request Failed")
				}
				errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
				return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,
					"alibabacloudstack_cen_cen_instance", "UpdateTransitRouter", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
			}
		}
		if d.HasChange("transit_router_cidrs") {
			request_remove := client.NewCommonRequest("POST", "Cbn", "2017-09-12", "DeleteTransitRouterCidr", "")
			request_add := client.NewCommonRequest("POST", "Cbn", "2017-09-12", "CreateTransitRouterCidr", "")
			request_remove.QueryParams["TransitRouterId"] = transitrouter_id
			request_add.QueryParams["TransitRouterId"] = transitrouter_id
			old, new := d.GetChange("transit_router_cidrs")
			log.Printf("[DEBUG] old:%v, new:%v", old, new)
			for _, v := range old.(*schema.Set).List() {
				log.Printf("[DEBUG] value: %v", v)
				log.Printf("[DEBUG] cidrs_map: %v", cidrs_map)
				cidr_id := cidrs_map[v.(string)]
				request_remove.QueryParams["TransitRouterCidrId"] = cidr_id
				bresponse, err := client.ProcessCommonRequest(request_remove)
				addDebug(request_remove.GetActionName(), bresponse, request_remove, request_remove.QueryParams)
				if err != nil {
					if bresponse == nil {
						return errmsgs.WrapErrorf(err, "Process Common Request Failed")
					}
					errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
					return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,
						"alibabacloudstack_cen_cen_instance", "DeleteTransitRouterCidr", request_remove.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
				}

			}
			for _, v := range new.(*schema.Set).List() {
				log.Printf("[DEBUG] new value: %v", v)
				log.Printf("[DEBUG] new cidrs_map: %v", cidrs_map)
				request_add.QueryParams["Cidr"] = v.(string)
				bresponse, err := client.ProcessCommonRequest(request_add)
				addDebug(request_add.GetActionName(), bresponse, request_add, request_add.QueryParams)
				if err != nil {
					if bresponse == nil {
						return errmsgs.WrapErrorf(err, "Process Common Request Failed")
					}
					errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
					return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,
						"alibabacloudstack_cen_cen_instance", "CreateTransitRouterCidr", request_add.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
				}

			}

		}
	}
	return nil
}

func resourceAlibabacloudStackCenCeninstanceRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	cencen_instanceservice := CenService{client}
	response, err := cencen_instanceservice.DoCbnDescribecensRequest(d.Id())
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg, "alibabacloudstack_cen_ceninstance", errmsgs.AlibabacloudStackSdkGoERROR)
	}
	data := response.Cens.Cen[0]
	d.Set("cen_id", data.CenId)
	if data.Name != "" {
		d.Set("cen_instance_name", data.Name)
	}
	if data.Description != "" {
		d.Set("description", data.Name)
	}
	d.Set("create_time", data.CreationTime)
	d.Set("protection_level", data.ProtectionLevel)
	d.Set("status", data.Status)
	bandwidth_package_ids := []string{}

	for _, v := range data.CenBandwidthPackageIds.CenBandwidthPackageId {
		bandwidth_package_ids = append(bandwidth_package_ids, v)
	}
	d.Set("cen_bandwidth_package_ids", bandwidth_package_ids)
	response_transitrouter, err := cencen_instanceservice.DoCbnDescribeTransitRoutersRequest(d.Id())
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg, "alibabacloudstack_cen_ceninstance", errmsgs.AlibabacloudStackSdkGoERROR)
	}
	if len(response_transitrouter.TransitRouters) > 0 {
		data := response_transitrouter.TransitRouters[0]
		d.Set("transit_router_id", data.TransitRouterId)
		if data.TransitRouterName != "" {
			d.Set("transit_router_name", data.TransitRouterName)
		}
		if data.TransitRouterDescription != "" {
			d.Set("transit_router_description", data.TransitRouterDescription)
		}
		if len(data.TransitRouterCidrList) > 0 {
			cidrs := []string{}
			for _, cidr := range data.TransitRouterCidrList {
				cidrs = append(cidrs, cidr.Cidr)
			}
			d.Set("transit_router_cidrs", cidrs)
		}
	}

	return nil
}

func resourceAlibabacloudStackCenCeninstanceDelete(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	// api: Cbn - 2017-09-12 - DeleteCen
	request := client.NewCommonRequest("POST", "Cbn", "2017-09-12", "DeleteCen", "")
	// CbnDeletecenResponseObj := CbnDeletecenResponse{}

	request.QueryParams["CenId"] = d.Id()

	bresponse, err := client.ProcessCommonRequest(request)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_cen_cen_instance", "DeleteCen", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}

	return nil
}

type CbnCreatecenResponse struct {
	CenId     string `json:"CenId"`
	RequestId string `json:"RequestId"`
}

type CbnCreatecenchildinstancerouteentrytocenResponse struct {
	RequestId string `json:"RequestId"`
}

type CbnDeletecenchildinstancerouteentrytocenResponse struct {
	RequestId string `json:"RequestId"`
}

type CbnDisablecenvbrhealthcheckResponse struct {
	RequestId string `json:"RequestId"`
}

type CbnEnablecenchildinstanceipv6Response struct {
	RequestId string `json:"RequestId"`
}

type CbnModifycenattributeResponse struct {
	RequestId string `json:"RequestId"`
}

type CbnMoveresourcegroupResponse struct {
	RequestId string `json:"RequestId"`
}

type CbnSetceninterregionbandwidthlimitResponse struct {
	RequestId string `json:"RequestId"`
}

type CbnTagresourcesResponse struct {
	RequestId string `json:"RequestId"`
}

type CbnUntagresourcesResponse struct {
	RequestId string `json:"RequestId"`
}

type CbnDeletecenResponse struct {
	RequestId string `json:"RequestId"`
}
