package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product RDS Resouce DbProxy
import (
	"fmt"
	"strconv"
	"strings"
	"time"

	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/errmsgs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
)

func resourceAlibabacloudStackRdsDbproxy() *schema.Resource {
	resource := &schema.Resource{
		Timeouts: &schema.ResourceTimeout{
			Create: schema.DefaultTimeout(40 * time.Minute),
			Update: schema.DefaultTimeout(40 * time.Minute),
			Delete: schema.DefaultTimeout(20 * time.Minute),
		},
		Schema: map[string]*schema.Schema{

			"db_instance_id": {
				Type:     schema.TypeString,
				Required: true,
			},
			"db_proxy_connect_string": {
				Type:     schema.TypeString,
				Optional: true,
				Computed: true,
			},
			"db_proxy_connect_string_port": {
				Type:     schema.TypeString,
				Optional: true,
				Computed: true,
			},

			"db_proxy_instance_current_minor_version": {
				Type:     schema.TypeString,
				Computed: true,
			},

			"db_proxy_instance_latest_minor_version": {
				Type:     schema.TypeString,
				Computed: true,
			},

			"db_proxy_instance_num": {
				Type:         schema.TypeInt,
				Optional:     true,
				ValidateFunc: validation.IntBetween(1, 60),
			},

			"db_proxy_instance_status": {
				Type:     schema.TypeString,
				Optional: true,
				Computed: true,
			},
			"db_proxy_endpoint_aliases": {
				Type:     schema.TypeString,
				Optional: true,
				Computed: true,
			},

			"db_proxy_endpoint_name": {
				Type:     schema.TypeString,
				Optional: true,
				Computed: true,
			},

			"db_proxy_endpoint_type": {
				Type:     schema.TypeString,
				Optional: true,
				Computed: true,
			},
			"db_proxy_read_write_mode": {
				Type:     schema.TypeString,
				Optional: true,
				Computed: true,
			},
			"db_proxy_instance_type": {
				Type:     schema.TypeString,
				Computed: true,
			},

			"db_proxy_service_status": {
				Type:     schema.TypeString,
				Computed: true,
			},

			"effective_specific_time": {
				Type:     schema.TypeString,
				Optional: true,
			},

			"effective_time": {
				Type:         schema.TypeString,
				Optional:     true,
				Default:      "Immediate",
				ValidateFunc: validation.StringInSlice([]string{"Immediate", "MaintainTime", "SpecificTime"}, false),
			},

			//			"instance_network_type": {
			//				Type:         schema.TypeString,
			//				Optional:     true,
			//				ValidateFunc: validation.StringInSlice([]string{"Classic", "VPC", "Public"}, false),
			//			},

			"connection_persist": {
				Type:         schema.TypeString,
				Optional:     true,
				Computed:     true,
				ValidateFunc: validation.StringInSlice([]string{"0", "1", "2"}, false),
			},
			"causal_consist_read": {
				Type:         schema.TypeString,
				Optional:     true,
				Computed:     true,
				ValidateFunc: validation.StringInSlice([]string{"0", "1", "2"}, false),
			},

			//			"persistent_connection_status": {
			//				Type:         schema.TypeString,
			//				Optional:     true,
			//				ValidateFunc: validation.StringInSlice([]string{"Enabled", "Disabled"}, false),
			//			},
		},
	}
	setResourceFunc(resource, resourceAlibabacloudStackRdsDbproxyCreate,
		resourceAlibabacloudStackRdsDbproxyRead,
		resourceAlibabacloudStackRdsDbproxyUpdate,
		resourceAlibabacloudStackRdsDbproxyDelete)
	return resource
}

func resourceAlibabacloudStackRdsDbproxyCreate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	//	rdsService := RdsService{client}

	db_instance_id := d.Get("db_instance_id").(string)
	// api: Rds - 2014-08-15 - ModifyDBProxy
	request := client.NewCommonRequest("POST", "Rds", "2014-08-15", "ModifyDBProxy", "")

	request.QueryParams["ConfigDBProxyService"] = "Startup"

	request.QueryParams["DBInstanceId"] = db_instance_id

	if v, ok := d.GetOk("db_proxy_instance_num"); ok {
		request.QueryParams["DBProxyInstanceNum"] = strconv.Itoa(v.(int))
	}

	//	if instance, err := rdsService.DescribeDBInstance(db_instance_id); err != nil {
	//		return err
	//	} else {
	//		request.QueryParams["InstanceNetworkType"] = instance.InstanceNetworkType
	//	}

	bresponse, err := client.ProcessCommonRequest(request)
	addDebug(request.GetActionName(), bresponse, request, request.QueryParams)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_rds_db_proxy", "ModifyDBProxy", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}

	d.SetId(db_instance_id)
	rdsdb_proxyservice := RdsService{client}
	stateConf := BuildStateConf([]string{"Creating"}, []string{"Running"}, d.Timeout(schema.TimeoutUpdate), 10*time.Second, rdsdb_proxyservice.RdsProxyStateRefreshFunc(db_instance_id, []string{""}))
	if _, err := stateConf.WaitForState(); err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.IdMsg, d.Id())
	}
	return nil

}

func resourceAlibabacloudStackRdsDbproxyUpdate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	rdsService := RdsService{client}

	// api: Rds - 2014-08-15 - ModifyDBProxy
	//	if d.HasChanges("persistent_connection_status") {
	//		request := client.NewCommonRequest("POST", "Rds", "2014-08-15", "ModifyDBProxy", "")
	//
	//		request.QueryParams["ConfigDBProxyService"] = "Modify"
	//		request.QueryParams["DBInstanceId"] = d.Id()
	//		if v, ok := d.GetOk("persistent_connection_status"); ok {
	//			request.QueryParams["PersistentConnectionStatus"] = v.(string)
	//		}
	//
	//		bresponse, err := client.ProcessCommonRequest(request)
	//		addDebug(request.GetActionName(), bresponse, request, request.QueryParams)
	//		if err != nil {
	//			if bresponse == nil {
	//				return errmsgs.WrapErrorf(err, "Process Common Request Failed")
	//			}
	//			errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
	//			return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,
	//				"alibabacloudstack_rds_db_proxy", "ModifyDBProxy", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	//		}
	//
	//	}
	var dBProxyEndpoint DBProxyEndpoint
	if v, err := rdsService.DoDescribeDBProxyEndpointRequest(d.Id()); err != nil {
		return err
	} else {
		dBProxyEndpoint = *v
	}

	if v, ok := d.GetOk("connection_persist"); ok && d.HasChanges("connection_persist") {
		request := client.NewCommonRequest("POST", "Rds", "2014-08-15", "ModifyDBProxyEndpoint", "")

		request.QueryParams["ConfigDBProxyService"] = "Modify"
		request.QueryParams["DBInstanceId"] = d.Id()
		request.QueryParams["DBProxyEndpointId"] = dBProxyEndpoint.DBProxyEndpointId
		request.QueryParams["ConfigDBProxyFeatures"] = fmt.Sprintf("ConnectionPersist:%s;", v.(string))
		if v, ok := d.GetOk("persistent_connection_status"); ok {
			request.QueryParams["PersistentConnectionStatus"] = v.(string)
		}

		bresponse, err := client.ProcessCommonRequest(request)
		addDebug(request.GetActionName(), bresponse, request, request.QueryParams)
		if err != nil {
			if bresponse == nil {
				return errmsgs.WrapErrorf(err, "Process Common Request Failed")
			}
			errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
			return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,
				"alibabacloudstack_rds_db_proxy", "ModifyDBProxyEndpoint", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
		}

	}

	if v, ok := d.GetOk("causal_consist_read"); ok && d.HasChanges("causal_consist_read") {
		request := client.NewCommonRequest("POST", "Rds", "2014-08-15", "ModifyDBProxyEndpoint", "")

		request.QueryParams["ConfigDBProxyService"] = "Modify"
		request.QueryParams["DBInstanceId"] = d.Id()
		request.QueryParams["DBProxyEndpointId"] = dBProxyEndpoint.DBProxyEndpointId
		request.QueryParams["ConfigDBProxyFeatures"] = fmt.Sprintf("CausalConsistRead:%s;", v.(string))
		if v, ok := d.GetOk("persistent_connection_status"); ok {
			request.QueryParams["PersistentConnectionStatus"] = v.(string)
		}

		bresponse, err := client.ProcessCommonRequest(request)
		addDebug(request.GetActionName(), bresponse, request, request.QueryParams)
		if err != nil {
			if bresponse == nil {
				return errmsgs.WrapErrorf(err, "Process Common Request Failed")
			}
			errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
			return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,
				"alibabacloudstack_rds_db_proxy", "ModifyDBProxyEndpoint", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
		}

	}

	// DBInstanceId

	// DBProxyConnectStringItems

	// api: Rds - 2014-08-15 - ModifyDBProxyEndpointAddress
	if d.HasChanges("db_proxy_connect_string_port") {
		request := client.NewCommonRequest("POST", "Rds", "2014-08-15", "ModifyDBProxyEndpointAddress", "")

		request.QueryParams["DBInstanceId"] = d.Id()
		request.QueryParams["DBProxyEndpointId"] = dBProxyEndpoint.DBProxyEndpointId
		request.QueryParams["DBProxyNewConnectStringPort"] = d.Get("db_proxy_connect_string_port").(string)
		bresponse, err := client.ProcessCommonRequest(request)
		addDebug(request.GetActionName(), bresponse, request, request.QueryParams)
		if err != nil {
			if bresponse == nil {
				return errmsgs.WrapErrorf(err, "Process Common Request Failed")
			}
			errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
			return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,
				"alibabacloudstack_rds_db_proxy", "ModifyDBProxyEndpointAddress", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
		}
		rdsdb_proxyservice := RdsService{client}
		stateConf := BuildStateConf([]string{"NET_MODIFYING"}, []string{"Running"}, d.Timeout(schema.TimeoutUpdate), 10*time.Second, rdsdb_proxyservice.RdsProxyStateRefreshFunc(d.Id(), []string{}))
		if _, err := stateConf.WaitForState(); err != nil {
			return errmsgs.WrapErrorf(err, errmsgs.IdMsg, d.Id())
		}
	}
	
	// Cannot be modified simultaneously with db_proxy_connect_string
	if d.HasChanges("db_proxy_connect_string") {
		request := client.NewCommonRequest("POST", "Rds", "2014-08-15", "ModifyDBProxyEndpointAddress", "")

		request.QueryParams["DBInstanceId"] = d.Id()
		request.QueryParams["DBProxyEndpointId"] = dBProxyEndpoint.DBProxyEndpointId
		request.QueryParams["DBProxyNewConnectString"] = d.Get("db_proxy_connect_string").(string)

		bresponse, err := client.ProcessCommonRequest(request)
		addDebug(request.GetActionName(), bresponse, request, request.QueryParams)
		if err != nil {
			if bresponse == nil {
				return errmsgs.WrapErrorf(err, "Process Common Request Failed")
			}
			errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
			return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,
				"alibabacloudstack_rds_db_proxy", "ModifyDBProxyEndpointAddress", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
		}
		rdsdb_proxyservice := RdsService{client}
		stateConf := BuildStateConf([]string{"NET_MODIFYING"}, []string{"Running"}, d.Timeout(schema.TimeoutUpdate), 10*time.Second, rdsdb_proxyservice.RdsProxyStateRefreshFunc(d.Id(), []string{}))
		if _, err := stateConf.WaitForState(); err != nil {
			return errmsgs.WrapErrorf(err, errmsgs.IdMsg, d.Id())
		}
	}

	// api: Rds - 2014-08-15 - ModifyDBProxyInstance
	if !d.IsNewResource() && d.HasChanges("db_proxy_instance_num", "effective_specific_time", "effective_time") {
		request := client.NewCommonRequest("POST", "Rds", "2014-08-15", "ModifyDBProxyInstance", "")

		request.QueryParams["DBInstanceId"] = d.Id()

		request.QueryParams["DBProxyInstanceNum"] = strconv.Itoa(d.Get("db_proxy_instance_num").(int))

		request.QueryParams["DBProxyInstanceType"] = d.Get("db_proxy_instance_type").(string)

		request.QueryParams["EffectiveTime"] = d.Get("effective_time").(string)
		if request.QueryParams["EffectiveTime"] == "SpecificTime" {
			if v, ok := d.GetOk("effective_specific_time"); ok {
				request.QueryParams["EffectiveSpecificTime"] = v.(string)
			} else {
				return fmt.Errorf("effective_specific_time is necessary while effective_time is SpecificTime")
			}
		}

		bresponse, err := client.ProcessCommonRequest(request)
		addDebug(request.GetActionName(), bresponse, request, request.QueryParams)
		if err != nil {
			if bresponse == nil {
				return errmsgs.WrapErrorf(err, "Process Common Request Failed")
			}
			errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
			return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,
				"alibabacloudstack_rds_db_proxy", "ModifyDBProxyInstance", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
		}
		rdsdb_proxyservice := RdsService{client}
		stateConf := BuildStateConf([]string{"DBInstanceClassChanging"}, []string{"Running"}, d.Timeout(schema.TimeoutUpdate), 10*time.Second, rdsdb_proxyservice.RdsProxyStateRefreshFunc(d.Id(), []string{}))
		if _, err := stateConf.WaitForState(); err != nil {
			return errmsgs.WrapErrorf(err, errmsgs.IdMsg, d.Id())
		}
	}

	// DBInstanceId  DBInstanceClassChanging

	return nil
}

func resourceAlibabacloudStackRdsDbproxyRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	rdsdb_proxyservice := RdsService{client}
	response, err := rdsdb_proxyservice.DoRdsDescribedbproxyRequest(d.Id())
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg, "alibabacloudstack_rds_dbproxy", errmsgs.AlibabacloudStackSdkGoERROR)
	}
	data := response

	d.Set("db_proxy_instance_current_minor_version", data.DBProxyInstanceCurrentMinorVersion)

	d.Set("db_proxy_instance_latest_minor_version", data.DBProxyInstanceLatestMinorVersion)

	d.Set("db_proxy_instance_num", data.DBProxyInstanceNum)

	d.Set("db_proxy_instance_status", data.DBProxyInstanceStatus)

	d.Set("db_proxy_service_status", data.DBProxyServiceStatus)

	d.Set("db_proxy_instance_type", data.DBProxyInstanceType)

	if v, err := rdsdb_proxyservice.DoDescribeDBProxyEndpointRequest(d.Id()); err != nil {
		return err
	} else {
		d.Set("db_proxy_connect_string_port", v.DBProxyConnectStringPort)
		d.Set("db_proxy_connect_string", v.DBProxyConnectString)
		for _, feature := range strings.Split(v.DBProxyFeatures, ";") {
			parts := strings.SplitN(feature, ":", 2)
			if len(parts) < 2 {
				continue
			}
			if parts[0] == "ConnectionPersist" {
				d.Set("connection_persist", parts[1])
			} else if parts[0] == "CausalConsistRead" {
				d.Set("causal_consist_read", parts[1])
			}
		}
	}

	for _, item := range data.DBProxyEndpointItems.DBProxyEndpointItems {
		// Only has one items
		d.Set("db_proxy_endpoint_name", item.DBProxyEndpointName)
		d.Set("db_proxy_endpoint_type", item.DBProxyEndpointType)
		d.Set("db_proxy_endpoint_aliases", item.DBProxyEndpointAliases)
		d.Set("db_proxy_read_write_mode", item.DBProxyReadWriteMode)
	}
	return nil
}

func resourceAlibabacloudStackRdsDbproxyDelete(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	//	rdsService := RdsService{client}
	request := client.NewCommonRequest("POST", "Rds", "2014-08-15", "ModifyDBProxy", "")
	request.QueryParams["ConfigDBProxyService"] = "Shutdown"

	request.QueryParams["DBInstanceId"] = d.Get("db_instance_id").(string)

	if v, ok := d.GetOk("db_proxy_instance_num"); ok {
		request.QueryParams["DBProxyInstanceNum"] = strconv.Itoa(v.(int))
	}
	//	if instance, err := rdsService.DescribeDBInstance(d.Id()); err != nil {
	//		return err
	//	} else {
	//		request.QueryParams["InstanceNetworkType"] = instance.InstanceNetworkType
	//	}

	bresponse, err := client.ProcessCommonRequest(request)
	addDebug(request.GetActionName(), bresponse, request, request.QueryParams)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_rds_db_proxy", "ModifyDBProxy", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}
	rdsdb_proxyservice := RdsService{client}
	stateConf := BuildStateConf([]string{"Deleting"}, []string{""}, d.Timeout(schema.TimeoutUpdate), 1*time.Second, rdsdb_proxyservice.RdsProxyStateRefreshFunc(d.Id(), []string{}))
	if _, err := stateConf.WaitForState(); err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.IdMsg, d.Id())
	}
	return nil
}
