package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product MongoDB Resouce ShardingNetworkPublicAddress
import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/errmsgs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func resourceAlibabacloudStackMongodbShardingInstanceCsNodeAddress() *schema.Resource {
	resource := &schema.Resource{
		Schema: map[string]*schema.Schema{
			"db_instance_id": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
			},
			"node_id": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
			},
			"enable_public_connection": {
				Type:     schema.TypeBool,
				Optional: true,
				Default:  false,
			},
			"enable_private_connection": {
				Type:     schema.TypeBool,
				Optional: true,
				Default:  false,
			},
			//Computed
			"public_connect_string": {
				Type:     schema.TypeString,
				Computed: true,
			},
			"private_connect_string": {
				Type:     schema.TypeString,
				Computed: true,
			},
			"public_connect_port": {
				Type:     schema.TypeInt,
				Computed: true,
			},
			"private_connect_port": {
				Type:     schema.TypeInt,
				Computed: true,
			},
		},
		CustomizeDiff: func(_ context.Context, d *schema.ResourceDiff, _ interface{}) error {
			if !d.Get("enable_private_connection").(bool) && d.Get("enable_public_connection").(bool) {
				return fmt.Errorf("can not enable public connection with out private connection")
			}
			nodeId := d.Get("node_id").(string)
			if nodeId != "" && !strings.HasPrefix(nodeId, "dds-") {
				return fmt.Errorf("node %s is not a config service node", nodeId)
			}
			return nil
		},
	}
	setResourceFunc(resource, resourceAlibabacloudStackMongodbShardingInstanceCsNodeAddressCreate,
		resourceAlibabacloudStackMongodbShardingInstanceCsNodeAddressRead,
		resourceAlibabacloudStackMongodbShardingInstanceCsNodeAddressUpdate,
		resourceAlibabacloudStackMongodbShardingInstanceCsNodeAddressDelete)
	return resource
}

func resourceAlibabacloudStackMongodbShardingInstanceCsNodeAddressCreate(d *schema.ResourceData, meta interface{}) error {
	id := fmt.Sprintf("%s:%s", d.Get("db_instance_id"), d.Get("node_id"))
	d.SetId(id)
	return nil
}

func resourceAlibabacloudStackMongodbShardingInstanceCsNodeAddressUpdate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	ddsService := MongoDBService{client}

	parts := strings.SplitN(d.Id(), ":", 2)
	instanceId := parts[0]
	nodeId := parts[1]

	stateConf := BuildStateConf(MongoDBChangingStatus, []string{"Running"},
		d.Timeout(schema.TimeoutUpdate), 15*time.Second, ddsService.MongoDbInstanceStateRefreshFunc(instanceId, []string{"failed"}))
	if _, err := stateConf.WaitForState(); err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.IdMsg, d.Id())
	}

	statusNow, err := ddsService.DescribeShardingInstanceNode(d.Id())
	if err != nil {
		return err
	}
	if d.Get("enable_private_connection").(bool) != statusNow["enable_private_connection"].(bool) && d.Get("enable_private_connection").(bool) {
		if err := ddsService.SwtichNodeConnection("AllocateNodePrivateNetworkAddress", instanceId, nodeId); err != nil {
			return err
		}
		if _, err := stateConf.WaitForState(); err != nil {
			return errmsgs.WrapErrorf(err, errmsgs.IdMsg, d.Id())
		}
		existedConf := BuildStateConf([]string{"Disable"}, []string{"Enable"},
			d.Timeout(schema.TimeoutUpdate), 15*time.Second, ddsService.MongoDbInstanceNodeAddressStateRefreshFunc(d.Id(), "private"))
		if _, err := existedConf.WaitForState(); err != nil {
			return errmsgs.WrapErrorf(err, errmsgs.IdMsg, d.Id())
		}
	}
	if d.Get("enable_public_connection").(bool) != statusNow["enable_public_connection"].(bool) && d.Get("enable_public_connection").(bool) {

		if err := ddsService.SwtichNodeConnection("AllocatePublicNetworkAddress", instanceId, nodeId); err != nil {
			return err
		}
		if _, err := stateConf.WaitForState(); err != nil {
			return errmsgs.WrapErrorf(err, errmsgs.IdMsg, d.Id())
		}
		existedConf := BuildStateConf([]string{"Disable"}, []string{"Enable"},
			d.Timeout(schema.TimeoutUpdate), 15*time.Second, ddsService.MongoDbInstanceNodeAddressStateRefreshFunc(d.Id(), "public"))
		if _, err := existedConf.WaitForState(); err != nil {
			return errmsgs.WrapErrorf(err, errmsgs.IdMsg, d.Id())
		}
	}
	if d.Get("enable_public_connection").(bool) != statusNow["enable_public_connection"].(bool) && !d.Get("enable_public_connection").(bool) {
		if err := ddsService.SwtichNodeConnection("ReleasePublicNetworkAddress", instanceId, nodeId); err != nil {
			return err
		}
		if _, err := stateConf.WaitForState(); err != nil {
			return errmsgs.WrapErrorf(err, errmsgs.IdMsg, d.Id())
		}
		existedConf := BuildStateConf([]string{"Enable"}, []string{"Disable"},
			d.Timeout(schema.TimeoutUpdate), 15*time.Second, ddsService.MongoDbInstanceNodeAddressStateRefreshFunc(d.Id(), "public"))
		if _, err := existedConf.WaitForState(); err != nil {
			return errmsgs.WrapErrorf(err, errmsgs.IdMsg, d.Id())
		}
	}
	if d.Get("enable_private_connection").(bool) != statusNow["enable_private_connection"].(bool) && !d.Get("enable_private_connection").(bool) {
		if err := ddsService.SwtichNodeConnection("ReleaseNodePrivateNetworkAddress", instanceId, nodeId); err != nil {
			return err
		}
		if _, err := stateConf.WaitForState(); err != nil {
			return errmsgs.WrapErrorf(err, errmsgs.IdMsg, d.Id())
		}
		existedConf := BuildStateConf([]string{"Enable"}, []string{"Disable"},
			d.Timeout(schema.TimeoutUpdate), 15*time.Second, ddsService.MongoDbInstanceNodeAddressStateRefreshFunc(d.Id(), "private"))
		if _, err := existedConf.WaitForState(); err != nil {
			return errmsgs.WrapErrorf(err, errmsgs.IdMsg, d.Id())
		}
	}
	return nil
}

func resourceAlibabacloudStackMongodbShardingInstanceCsNodeAddressRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	ddsService := MongoDBService{client}

	parts := strings.SplitN(d.Id(), ":", 2)
	instanceId := parts[0]
	nodeId := parts[1]

	statusNow, err := ddsService.DescribeShardingInstanceNode(d.Id())
	if err != nil {
		return err
	}
	d.Set("db_instance_id", instanceId)
	d.Set("node_id", nodeId)
	d.Set("enable_public_connection", statusNow["enable_public_connection"])
	d.Set("enable_private_connection", statusNow["enable_private_connection"])
	d.Set("public_connect_string", statusNow["public_connect_string"])
	d.Set("private_connect_string", statusNow["private_connect_string"])
	d.Set("public_connect_port", statusNow["public_connect_port"])
	d.Set("private_connect_port", statusNow["private_connect_port"])

	return nil
}

func resourceAlibabacloudStackMongodbShardingInstanceCsNodeAddressDelete(d *schema.ResourceData, meta interface{}) error {
	return nil
}
