package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product DRDS Resouce Account
import (
	"encoding/json"
	"fmt"

	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/errmsgs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
)

func resourceAlibabacloudStackDrdsAccount() *schema.Resource {
	resource := &schema.Resource{
		Schema: map[string]*schema.Schema{

			"instance_id": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
			},

			"drds_account_name": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
			},

			"host": {
				Type:     schema.TypeString,
				Computed: true,
			},

			"description": {
				Type:     schema.TypeString,
				Optional: true,
			},

			"account_type": {
				Type:     schema.TypeInt,
				Computed: true,
			},
			"password": {
				Type:      schema.TypeString,
				Required:  true,
				Sensitive: true,
			},

			"db_privileges": {
				Type:     schema.TypeSet,
				Required: true,
				MinItems: 1,

				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"db_name": {
							Type:     schema.TypeString,
							Required: true,
						},
						"privilege": {
							Type:         schema.TypeString,
							Required:     true,
							ValidateFunc: validation.StringInSlice([]string{"R", "RW", "DDL", "DML"}, false),
						},
					},
				},
			},
		},
	}
	setResourceFunc(resource, resourceAlibabacloudStackDrdsAccountCreate, resourceAlibabacloudStackDrdsAccountRead, resourceAlibabacloudStackDrdsAccountUpdate, resourceAlibabacloudStackDrdsAccountDelete)
	return resource
}

func resourceAlibabacloudStackDrdsAccountCreate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)

	reqQuery := map[string]interface{}{
		"DrdsInstanceId": d.Get("instance_id").(string),
		"AccountName":    d.Get("drds_account_name").(string),
		"Password":       d.Get("password").(string),
	}

	dbPrivileges := []map[string]string{}
	for _, d := range d.Get("db_privileges").(*schema.Set).List() {
		dbPrivilege := d.(map[string]interface{})
		dbPrivileges = append(dbPrivileges, map[string]string{
			"DbName":    dbPrivilege["db_name"].(string),
			"Privilege": dbPrivilege["privilege"].(string),
		})
	}
	reqQuery["DbPrivilege"] = dbPrivileges

	_, err := client.DoTeaRequest("POST", "Drds", "2019-01-23", "CreateInstanceAccount", "", nil, reqQuery, nil)
	if err != nil {
		return err
	}

	d.SetId(fmt.Sprintf("%s:%s@%%", d.Get("instance_id").(string), d.Get("drds_account_name").(string)))
	return nil

}

func resourceAlibabacloudStackDrdsAccountUpdate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)

	var instanceId, drdsAccountName string
	if parts, err := ParseResourceId(d.Id(), 2); err != nil {
		return err
	} else {
		instanceId = parts[0]
		drdsAccountName = parts[1]
	}
	// Description

	// DrdsAccountName

	// InstanceId

	// api: Drds - 2019-01-23 - ModifyAccountDescription
	if d.HasChanges("description") && d.Get("description").(string) != "" {
		request := client.NewCommonRequest("POST", "Drds", "2019-01-23", "ModifyAccountDescription", "")
		DrdsModifyaccountdescriptionResponse := DrdsModifyaccountdescriptionResponse{}

		request.QueryParams["Description"] = d.Get("description").(string)
		request.QueryParams["AccountName"] = drdsAccountName
		request.QueryParams["DrdsInstanceId"] = instanceId

		bresponse, err := client.ProcessCommonRequest(request)
		if err != nil {
			if bresponse == nil {
				return errmsgs.WrapErrorf(err, "Process Common Request Failed")
			}
			errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
			return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,
				"alibabacloudstack_drds_account", "ModifyAccountDescription", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
		}

		err = json.Unmarshal(bresponse.GetHttpContentBytes(), &DrdsModifyaccountdescriptionResponse)
		if err != nil {
			return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
				"alibabacloudstack_drds_account", "ModifyAccountDescription", errmsgs.AlibabacloudStackSdkGoERROR)
		}

	}

	if d.IsNewResource() {
		return nil
	}

	// DrdsAccountName

	// InstanceId

	// Password

	// api: Drds - 2019-01-23 - ChangeAccountPassword
	if d.HasChanges("password") {
		request := client.NewCommonRequest("POST", "Drds", "2019-01-23", "ChangeAccountPassword", "")
		DrdsChangeaccountpasswordResponse := DrdsChangeaccountpasswordResponse{}

		request.QueryParams["AccountName"] = drdsAccountName
		request.QueryParams["DrdsInstanceId"] = instanceId

		request.QueryParams["Password"] = d.Get("password").(string)

		bresponse, err := client.ProcessCommonRequest(request)
		if err != nil {
			if bresponse == nil {
				return errmsgs.WrapErrorf(err, "Process Common Request Failed")
			}
			errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
			return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,
				"alibabacloudstack_drds_account", "ChangeAccountPassword", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
		}

		err = json.Unmarshal(bresponse.GetHttpContentBytes(), &DrdsChangeaccountpasswordResponse)
		if err != nil {
			return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
				"alibabacloudstack_drds_account", "ChangeAccountPassword", errmsgs.AlibabacloudStackSdkGoERROR)
		}

	}

	// DbPrivileges

	// DrdsAccountName

	// InstanceId

	// api: Drds - 2019-01-23 - ModifyAccountPrivilege
	if d.HasChanges("db_privileges") {
		reqQuery := map[string]interface{}{
			"DrdsInstanceId": d.Get("instance_id").(string),
			"AccountName":    d.Get("drds_account_name").(string),
			"Password":       d.Get("password").(string),
		}

		dbPrivileges := []map[string]string{}
		for _, d := range d.Get("db_privileges").(*schema.Set).List() {
			dbPrivilege := d.(map[string]interface{})
			dbPrivileges = append(dbPrivileges, map[string]string{
				"DbName":    dbPrivilege["db_name"].(string),
				"Privilege": dbPrivilege["privilege"].(string),
			})
		}
		reqQuery["DbPrivilege"] = dbPrivileges

		_, err := client.DoTeaRequest("POST", "Drds", "2019-01-23", "ModifyAccountPrivilege", "", nil, reqQuery, nil)
		if err != nil {
			return err
		}
	}

	return nil
}

func resourceAlibabacloudStackDrdsAccountRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	drdsaccountservice := DrdsService{client}
	account, err := drdsaccountservice.DescribeDrdsAccount(d.Id())
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg, "alibabacloudstack_drds_account", errmsgs.AlibabacloudStackSdkGoERROR)
	}
	if parts, err := ParseResourceId(d.Id(), 2); err != nil {
		return err
	} else {
		d.Set("instance_id", parts[0])
	}

	d.Set("description", account.Description)
	d.Set("drds_account_name", account.AccountName)

	dbPrivileges := []map[string]string{}
	for _, d := range account.DbPrivileges.DbPrivilege {
		dbPrivileges = append(dbPrivileges, map[string]string{
			"db_name":   d.DbName,
			"privilege": d.Privilege,
		})
	}

	d.Set("db_privileges", dbPrivileges)

	d.Set("host", account.Host)
	d.Set("account_type", account.AccountType)

	return nil
}

func resourceAlibabacloudStackDrdsAccountDelete(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	// api: Drds - 2019-01-23 - RemoveInstanceAccount
	request := client.NewCommonRequest("POST", "Drds", "2019-01-23", "RemoveInstanceAccount", "")
	DrdsRemoveinstanceaccountResponse := DrdsRemoveinstanceaccountResponse{}

	parts, err := ParseResourceId(d.Id(), 2)
	if err != nil {
		return err
	}
	// Call request_params_handler
	request.QueryParams["DrdsInstanceId"] = parts[0]
	request.QueryParams["AccountName"] = parts[1]

	bresponse, err := client.ProcessCommonRequest(request)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_drds_account", "RemoveInstanceAccount", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}

	err = json.Unmarshal(bresponse.GetHttpContentBytes(), &DrdsRemoveinstanceaccountResponse)
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
			"alibabacloudstack_drds_account", "RemoveInstanceAccount", errmsgs.AlibabacloudStackSdkGoERROR)
	}

	return nil
}

type DrdsCreateinstanceaccountResponse struct {
	RequestId string `json:"RequestId"`
	Success   bool   `json:"Success"`
}

type DrdsChangeaccountpasswordResponse struct {
	RequestId string `json:"RequestId"`
	Success   bool   `json:"Success"`
}
type DrdsModifyaccountdescriptionResponse struct {
	RequestId string `json:"RequestId"`
	Success   bool   `json:"Success"`
}
type DrdsModifyaccountprivilegeResponse struct {
	RequestId string `json:"RequestId"`
	Success   bool   `json:"Success"`
}

type DrdsRemoveinstanceaccountResponse struct {
	RequestId string `json:"RequestId"`
	Success   bool   `json:"Success"`
}
