package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product CEN Resouce CenInstance
import (
	"encoding/json"
	"fmt"
	"log"
	"strings"
	"time"

	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/errmsgs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func resourceAlibabacloudStackCenTransitRouterVbrAttachment() *schema.Resource {
	resource := &schema.Resource{
		Schema: map[string]*schema.Schema{
			"auto_publish_route_enabled": {
				Type:     schema.TypeBool,
				Computed: true,
			},
			"charge_type": {
				Type:     schema.TypeString,
				Computed: true,
			},
			"cen_id": {
				Type:     schema.TypeString,
				Required: true,
			},
			"creation_time": {
				Type:     schema.TypeString,
				Computed: true,
			},
			"resource_type": {
				Type:     schema.TypeString,
				Computed: true,
			},
			"status": {
				Type:     schema.TypeString,
				Computed: true,
			},
			"tags": {
				Type:     schema.TypeSet,
				Optional: true,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"tag_key": {
							Type:     schema.TypeString,
							Optional: true,
						},
						"tag_value": {
							Type:     schema.TypeString,
							Optional: true,
						},
					},
				},
			},
			"transit_router_attachment_description": {
				Type:     schema.TypeString,
				Optional: true,
			},
			"transit_router_attachment_id": {
				Type:     schema.TypeString,
				Computed: true,
			},
			"transit_router_id": {
				Type:     schema.TypeString,
				Required: true,
			},
			"transit_router_attachment_name": {
				Type:     schema.TypeString,
				Optional: true,
			},
			"route_table_propagation_enabled": {
				Type:     schema.TypeBool,
				Optional: true,
				ForceNew: true,
			},
			"route_table_association_enabled": {
				Type:     schema.TypeBool,
				Optional: true,
				ForceNew: true,
			},
			"vbr_id": {
				Type:     schema.TypeString,
				Required: true,
			},
			"vbr_owner_id": {
				Type:     schema.TypeString,
				Computed: true,
			},
		},
	}
	setResourceFunc(resource, resourceAlibabacloudStackCenTransitRouterVbrAttachmentCreate,
		resourceAlibabacloudStackCenTransitRouterVbrAttachmentRead,
		resourceAlibabacloudStackCenTransitRouterVbrAttachmentUpdate,
		resourceAlibabacloudStackCenTransitRouterVbrAttachmentDelete)
	return resource
}

func resourceAlibabacloudStackCenTransitRouterVbrAttachmentCreate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	cencen_instanceservice := CenService{client}
	// api: Cbn - 2017-09-12 - CreateCen
	request := client.NewCommonRequest("POST", "Cbn", "2017-09-12", "CreateTransitRouterVbrAttachment", "")
	CbnCreateTransitRouterVbrAttachmentResponseObj := CbnCreateTransitRouterVbrAttachmentResponse{}
	request.QueryParams["CenId"] = d.Get("cen_id").(string)
	request.QueryParams["VbrId"] = d.Get("vbr_id").(string)
	request.QueryParams["AutoPublishRouteEnabled"] = "true"
	if v, ok := d.GetOk("route_table_propagation_enabled"); ok {
		request.QueryParams["RouteTablePropagationEnabled"] = fmt.Sprintf("%v", v)
	}
	if v, ok := d.GetOk("route_table_association_enabled"); ok {
		request.QueryParams["RouteTableAssociationEnabled"] = fmt.Sprintf("%v", v)
	}
	bresponse, err := client.ProcessCommonRequest(request)
	addDebug(request.GetActionName(), bresponse, request, request.QueryParams)
	if err != nil {
		for i := 1; i <= 5; i++ {
			bresponse, err = client.ProcessCommonRequest(request)
			addDebug(request.GetActionName(), bresponse, request, request.QueryParams)
			if err != nil {
				time.Sleep(3 * time.Second)
				continue
			}
		}
	}
	err = json.Unmarshal(bresponse.GetHttpContentBytes(), &CbnCreateTransitRouterVbrAttachmentResponseObj)
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
			"alibabacloudstack_cen_transit_router_vbr_attachment", "CreateTransitRouterVbrAttachment", errmsgs.AlibabacloudStackSdkGoERROR)
	}
	attachment_id := CbnCreateTransitRouterVbrAttachmentResponseObj.TransitRouterAttachmentId
	d.SetId(fmt.Sprintf("%s:%s:%s:%s", d.Get("cen_id").(string), d.Get("transit_router_id").(string), attachment_id, d.Get("vbr_id").(string)))
	err = cencen_instanceservice.WaitForAttachmentInstance(d.Id(), Attached, 600)
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
			"alibabacloudstack_cen_transit_router_vbr_attachment", "CreateTransitRouterVbrAttachment", errmsgs.AlibabacloudStackSdkGoERROR)
	}
	return nil
}

func resourceAlibabacloudStackCenTransitRouterVbrAttachmentUpdate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	parts := strings.Split(d.Id(), COLON_SEPARATED)
	attachment_id := parts[2]
	// api: Cbn - 2017-09-12 - ModifyCenAttribute
	if d.HasChanges("transit_router_attachment_name", "transit_router_attachment_description", "zone_mappings") {
		if d.HasChanges("transit_router_attachment_name", "transit_router_attachment_description") {
			request := client.NewCommonRequest("POST", "Cbn", "2017-09-12", "UpdateTransitRouterVpcAttachmentAttribute", "")
			if v, ok := d.GetOk("transit_router_attachment_name"); ok {
				request.QueryParams["TransitRouterAttachmentName"] = v.(string)
			}
			if v, ok := d.GetOk("transit_router_attachment_description"); ok {
				request.QueryParams["TransitRouterAttachmentDescription"] = v.(string)
			}
			request.QueryParams["Status"] = "Attached"
			request.QueryParams["TransitRouterAttachmentId"] = attachment_id
			request.QueryParams["ResourceType"] = "VBR"
			bresponse, err := client.ProcessCommonRequest(request)
			addDebug(request.GetActionName(), bresponse, request, request.QueryParams)
			if err != nil {
				if bresponse == nil {
					return errmsgs.WrapErrorf(err, "Process Common Request Failed")
				}
				errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
				return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,
					"alibabacloudstack_cen_transit_router_vbr_attachment", "UpdateTransitRouterVpcAttachmentAttribute", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
			}
		}
	}
	return nil
}

func resourceAlibabacloudStackCenTransitRouterVbrAttachmentRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	cencen_instanceservice := CenService{client}
	err := cencen_instanceservice.WaitForAttachmentInstance(d.Id(), Attached, 120)
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
			"alibabacloudstack_cen_transit_router_vbr_attachment", "CreateTransitRouterVbrAttachment", errmsgs.AlibabacloudStackSdkGoERROR)
	}
	response, err := cencen_instanceservice.DoCbnDescribeTransitRouterVbrAttachmentsRequest(d.Id())
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg, "alibabacloudstack_cen_transit_router_vbr_attachment", errmsgs.AlibabacloudStackSdkGoERROR)
	}
	parts := strings.Split(d.Id(), ":")
	attachment_id := parts[2]
	for _, v := range response.TransitRouterAttachments {
		if v.TransitRouterAttachmentId == attachment_id {
			d.Set("transit_router_id", v.TransitRouterId)
			d.Set("transit_router_attachment_id", v.TransitRouterAttachmentId)
			d.Set("vbr_id", v.VbrId)
			d.Set("vbr_owner_id", fmt.Sprintf("%d", v.VbrOwnerId))
			d.Set("auto_publish_route_enabled", v.AutoPublishRouteEnabled)
			d.Set("transit_router_attachment_name", v.TransitRouterAttachmentName)
			d.Set("transit_router_attachment_description", v.TransitRouterAttachmentDescription)
			d.Set("resource_type", v.ResourceType)
			d.Set("creation_time", v.CreationTime)
			d.Set("status", v.Status)
			break
		}
	}

	return nil
}

func resourceAlibabacloudStackCenTransitRouterVbrAttachmentDelete(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	cencen_instanceservice := CenService{client}
	parts := strings.Split(d.Id(), ":")
	cen_id := parts[0]
	router_id := parts[1]
	attach_ment_id := parts[2]
	response, err := cencen_instanceservice.DoCbnDescribeTransitRouterRouteTablesRequest(router_id + ":")
	if err != nil {
		return errmsgs.WrapErrorf(err, "DoVpcRouteEntryListRequest")
	}
	table_id := response.TransitRouterRouteTables[0].TransitRouterRouteTableId

	for i := 0; i < 10; i++ {
		response_ass, err := cencen_instanceservice.DoCbnDescribeTransitRouterRouteTableAssociationsRequest(table_id + ":" + attach_ment_id)
		if err != nil {
			return errmsgs.WrapErrorf(err, "ListTransitRouterRouteTableAssociations")
		}
		if len(response_ass.TransitRouterAssociations) == 0 {
			break
		}
		for _, data := range response_ass.TransitRouterAssociations {
			if data.Status == string(Active) {
				request := client.NewCommonRequest("GET", "Cbn", "2017-09-12", "DissociateTransitRouterAttachmentFromRouteTable", "")
				request.QueryParams["TransitRouterAttachmentId"] = data.TransitRouterAttachmentId
				request.QueryParams["TransitRouterRouteTableId"] = data.TransitRouterRouteTableId
				log.Printf("[DEBUG] TransitRouterAttachmentId is %v#", data.TransitRouterAttachmentId)
				bresponse, err := client.ProcessCommonRequest(request)
				if err != nil {
					if bresponse == nil {
						return errmsgs.WrapErrorf(err, "Process Common Request Failed")
					}
					errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
					return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_cen_transit_router_vbr_attachment", "DissociateTransitRouterAttachmentFromRouteTable", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
				}
			}
		}
		time.Sleep(2 * time.Second)
	}

	for i := 0; i < 10; i++ {
		response_pro, err := cencen_instanceservice.DoCbnDescribeTransitRouterRouteTablePropagationsRequest(table_id + ":" + attach_ment_id)
		if err != nil {
			return errmsgs.WrapErrorf(err, "DoVpcRouteEntryListRequest")
		}
		if len(response_pro.TransitRouterPropagations) == 0 {
			break
		}
		for _, data := range response_pro.TransitRouterPropagations {
			if data.Status == string(Active) {
				request := client.NewCommonRequest("GET", "Cbn", "2017-09-12", "DisableTransitRouterRouteTablePropagation", "")
				request.QueryParams["TransitRouterAttachmentId"] = data.TransitRouterAttachmentId
				request.QueryParams["TransitRouterRouteTableId"] = data.TransitRouterRouteTableId
				bresponse, err := client.ProcessCommonRequest(request)
				log.Printf("[DEBUG] DisableTransitRouterRouteTablePropagation is %v#", data.TransitRouterAttachmentId)
				if err != nil {
					if bresponse == nil {
						return errmsgs.WrapErrorf(err, "Process Common Request Failed")
					}
					errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
					return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_cen_transit_router_vbr_attachment", "DisableTransitRouterRouteTablePropagation", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
				}
			}
		}
		time.Sleep(2 * time.Second)
	}
	// api: Cbn - 2017-09-12 - DeleteCen
	request := client.NewCommonRequest("POST", "Cbn", "2017-09-12", "DeleteTransitRouterVbrAttachment", "")
	request.QueryParams["CenId"] = cen_id
	request.QueryParams["TransitRouterAttachmentId"] = attach_ment_id
	bresponse, err := client.ProcessCommonRequest(request)
	addDebug(request.GetActionName(), bresponse, request, request.QueryParams)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_cen_transit_router_vbr_attachment", "DeleteTransitRouterVbrAttachment", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}
	for i := 0; i < 200; i++ {
		response, err := cencen_instanceservice.DoCbnDescribeTransitRouterVbrAttachmentsRequest(d.Id())
		if err != nil {
			return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg, "alibabacloudstack_cen_transit_router_vbr_attachment", errmsgs.AlibabacloudStackSdkGoERROR)
		}
		if len(response.TransitRouterAttachments) == 0 {
			break
		}
		time.Sleep(3 * time.Second)
	}
	return nil
}

type CbnCreateTransitRouterVbrAttachmentResponse struct {
	TransitRouterAttachmentId string `json:"TransitRouterAttachmentId"`
	RequestId                 string `json:"RequestId"`
}
