package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product Rds Resouce Backup
import (
	"fmt"
	"log"
	"strconv"
	"time"

	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/errmsgs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func resourceAlibabacloudStackRdsBackup() *schema.Resource {
	resource := &schema.Resource{
		Schema: map[string]*schema.Schema{

			"backup_db_names": {
				Type:     schema.TypeString,
				Computed: true,
			},

			"backup_download_url": {
				Type:     schema.TypeString,
				Computed: true,
			},

			"backup_id": {
				Type:     schema.TypeInt,
				Computed: true,
			},

			"backup_intranet_download_url": {
				Type:     schema.TypeString,
				Computed: true,
			},

			"backup_method": {
				Type:     schema.TypeString,
				Required: true,
			},

			"backup_mode": {
				Type:     schema.TypeString,
				Computed: true,
			},

			"backup_size": {
				Type:     schema.TypeInt,
				Computed: true,
			},

			"backup_type": {
				Type:     schema.TypeString,
				Computed: true,
			},

			"end_time": {
				Type:     schema.TypeString,
				Computed: true,
			},

			"instance_id": {
				Type:     schema.TypeString,
				Required: true,
			},

			"start_time": {
				Type:     schema.TypeString,
				Computed: true,
			},

			"status": {
				Type:     schema.TypeString,
				Computed: true,
			},
		},
	}
	setResourceFunc(resource, resourceAlibabacloudStackRdsBackupCreate,
		resourceAlibabacloudStackRdsBackupRead,
		resourceAlibabacloudStackRdsBackupUpdate,
		resourceAlibabacloudStackRdsBackupDelete)
	return resource
}

func resourceAlibabacloudStackRdsBackupCreate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	rdsservice := RdsService{client}
	// api: Rds - 2015-01-01 - CreateBackup
	request := client.NewCommonRequest("POST", "Rds", "2014-08-15", "CreateBackup", "")
	rdsCreatebackupResponse := RdsCreatebackupResponse{}

	//调用request_params_handler

	request.QueryParams["BackupMethod"] = d.Get("backup_method").(string)

	request.QueryParams["DBInstanceId"] = d.Get("instance_id").(string)

	bresponse, err := client.ProcessCommonRequest(request)
	addDebug(request.GetActionName(), bresponse, request, request.QueryParams)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_rds_backup", "CreateBackup", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}

	// api: Rds - 2015-12-01 - DescribeBackupDBs
	backup_id := rdsCreatebackupResponse.BackupJobID

	instance_id := d.Get("instance_id").(string)
	start_time := time.Now().UTC().Format("2006-01-02T15:04Z")
	describe_id := fmt.Sprintf("%s", backup_id+"&"+instance_id+"&"+start_time)
	for i := 0; i < 30; i++ {
		response, err := rdsservice.DoDescribebackupsRequest(describe_id)
		if err == nil {
			log.Printf("Backup is %+v", response.Items.Backup)
			if len(response.Items.Backup) > 0 {
				start_time, err = rdsservice.FormatUtcTime(response.Items.Backup[0].BackupStartTime)
				if err != nil {
					return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg, "FormatMongodbTime", errmsgs.AlibabacloudStackSdkGoERROR)
				}

				d.SetId(fmt.Sprintf("%s", strconv.Itoa(response.Items.Backup[0].BackupId)+"&"+instance_id+"&"+start_time))
				break
			}
		}
		time.Sleep(10 * time.Second)
	}
	return nil

}

func resourceAlibabacloudStackRdsBackupUpdate(d *schema.ResourceData, meta interface{}) error {
	// client := meta.(*connectivity.AlibabacloudStackClient)

	return nil
}

func resourceAlibabacloudStackRdsBackupRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	rdsservice := RdsService{client}
	response, err := rdsservice.DoDescribebackupsRequest(d.Id())
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg, "alibabacloudstack_rds_backup", errmsgs.AlibabacloudStackSdkGoERROR)
	}
	data := response.Items.Backup[0]
	d.Set("backup_db_names", data.BackupDBNames)

	d.Set("backup_id", data.BackupId)

	d.Set("backup_method", data.BackupMethod)

	d.Set("backup_mode", data.BackupMode)

	d.Set("backup_size", data.BackupSize)

	d.Set("backup_type", data.BackupType)

	d.Set("status", data.BackupStatus)
	d.Set("start_time", data.BackupStartTime)
	d.Set("end_time", data.BackupEndTime)
	return nil
}

func resourceAlibabacloudStackRdsBackupDelete(d *schema.ResourceData, meta interface{}) error {
	return nil
}

type RdsCreatebackupResponse struct {
	RequestId   string `json:"RequestId"`
	BackupJobID string `json:"BackupJobID"`
}
