package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product VPNGateway Resouce SslVpnServer
import (
	"encoding/json"
	"strconv"
	"time"

	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/errmsgs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func resourceAlibabacloudStackVpngatewaySslvpnserver() *schema.Resource {
	resource := &schema.Resource{
		Schema: map[string]*schema.Schema{

			"cipher": {
				Type:     schema.TypeString,
				Computed: true,
				Optional: true,
			},

			"client_ip_pool": {
				Type:     schema.TypeString,
				Required: true,
			},

			"compress": {
				Type:     schema.TypeBool,
				Default:  false,
				Optional: true,
			},

			"connections": {
				Type:     schema.TypeInt,
				Computed: true,
			},

			"create_time": {
				Type:     schema.TypeInt,
				Computed: true,
			},

			"internet_ip": {
				Type:     schema.TypeString,
				Computed: true,
			},

			"local_subnet": {
				Type:     schema.TypeString,
				Required: true,
			},

			"max_connections": {
				Type:     schema.TypeInt,
				Computed: true,
			},

			"port": {
				Type:     schema.TypeInt,
				Optional: true,
				Computed: true,
			},

			"proto": {
				Type:     schema.TypeString,
				Optional: true,
				Computed: true,
			},

			"ssl_vpn_server_id": {
				Type:     schema.TypeString,
				Computed: true,
			},

			"ssl_vpn_server_name": {
				Type:     schema.TypeString,
				Required: true,
			},

			"vpn_gateway_id": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
			},
		},
	}
	setResourceFunc(resource, resourceAlibabacloudStackVpngatewaySslvpnserverCreate,
		resourceAlibabacloudStackVpngatewaySslvpnserverRead,
		resourceAlibabacloudStackVpngatewaySslvpnserverUpdate,
		resourceAlibabacloudStackVpngatewaySslvpnserverDelete)
	return resource
}

func resourceAlibabacloudStackVpngatewaySslvpnserverCreate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)

	// api: Vpc - 2016-04-28 - CreateSslVpnServer
	request := client.NewCommonRequest("POST", "Vpc", "2016-04-28", "CreateSslVpnServer", "")
	VpcCreatesslvpnserverResponseObj := VpcCreatesslvpnserverResponse{}

	//调用request_params_handler

	if v, ok := d.GetOk("cipher"); ok {
		request.QueryParams["Cipher"] = v.(string)
	}

	request.QueryParams["ClientIpPool"] = d.Get("client_ip_pool").(string)

	if v, ok := d.GetOk("compress"); ok {
		request.QueryParams["Compress"] = strconv.FormatBool(v.(bool))
	}

	request.QueryParams["LocalSubnet"] = d.Get("local_subnet").(string)

	if v, ok := d.GetOk("port"); ok {
		request.QueryParams["Port"] = strconv.Itoa(v.(int))
	}

	if v, ok := d.GetOk("proto"); ok {
		request.QueryParams["Proto"] = v.(string)
	}

	if v, ok := d.GetOk("ssl_vpn_server_name"); ok {
		request.QueryParams["Name"] = v.(string)
	}

	request.QueryParams["VpnGatewayId"] = d.Get("vpn_gateway_id").(string)

	bresponse, err := client.ProcessCommonRequest(request)
	addDebug(request.GetActionName(), bresponse, request, request.QueryParams)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_vpn_gateway_ssl_vpn_server", "CreateSslVpnServer", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}

	err = json.Unmarshal(bresponse.GetHttpContentBytes(), &VpcCreatesslvpnserverResponseObj)
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
			"alibabacloudstack_vpn_gateway_ssl_vpn_server", "CreateSslVpnServer", errmsgs.AlibabacloudStackSdkGoERROR)
	}

	ssl_vpn_server_id := VpcCreatesslvpnserverResponseObj.SslVpnServerId

	d.SetId(ssl_vpn_server_id)
	return nil

}

func resourceAlibabacloudStackVpngatewaySslvpnserverUpdate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)

	if d.IsNewResource() {
		return nil
	}

	// Cipher
	// ClientIpPool
	// Compress
	// LocalSubnet
	// Port
	// Proto
	// RegionId
	// SslVpnServerId
	// SslVpnServerName
	// api: Vpc - 2016-04-28 - ModifySslVpnServer
	if d.HasChanges("cipher", "client_ip_pool", "compress", "local_subnet", "port", "proto", "ssl_vpn_server_name") {
		request := client.NewCommonRequest("POST", "Vpc", "2016-04-28", "ModifySslVpnServer", "")
		VpcModifysslvpnserverResponseObj := VpcModifysslvpnserverResponse{}

		if v, ok := d.GetOk("cipher"); ok {
			request.QueryParams["Cipher"] = v.(string)
		}

		if v, ok := d.GetOk("client_ip_pool"); ok {
			request.QueryParams["ClientIpPool"] = v.(string)
		}
		request.QueryParams["Compress"] = strconv.FormatBool(d.Get("compress").(bool))

		if v, ok := d.GetOk("local_subnet"); ok {
			request.QueryParams["LocalSubnet"] = v.(string)
		}

		if v, ok := d.GetOk("port"); ok {
			request.QueryParams["Port"] = strconv.Itoa(v.(int))
		}

		if v, ok := d.GetOk("proto"); ok {
			request.QueryParams["Proto"] = v.(string)
		}

		request.QueryParams["SslVpnServerId"] = d.Id()

		if v, ok := d.GetOk("ssl_vpn_server_name"); ok {
			request.QueryParams["Name"] = v.(string)
		}

		bresponse, err := client.ProcessCommonRequest(request)
		addDebug(request.GetActionName(), bresponse, request, request.QueryParams)
		if err != nil {
			if bresponse == nil {
				return errmsgs.WrapErrorf(err, "Process Common Request Failed")
			}
			errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
			return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,
				"alibabacloudstack_vpn_gateway_ssl_vpn_server", "ModifySslVpnServer", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
		}

		err = json.Unmarshal(bresponse.GetHttpContentBytes(), &VpcModifysslvpnserverResponseObj)
		if err != nil {
			return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
				"alibabacloudstack_vpn_gateway_ssl_vpn_server", "ModifySslVpnServer", errmsgs.AlibabacloudStackSdkGoERROR)
		}

	}

	return nil
}

func resourceAlibabacloudStackVpngatewaySslvpnserverRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	vpn_gatewayssl_vpn_serverservice := VpnGatewayService{client}
	for i := 0; i < 12; i++ {
		response, err := vpn_gatewayssl_vpn_serverservice.DoVpcDescribesslvpnserversRequest(d.Id())
		if err != nil {
			return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg, "alibabacloudstack_vpngateway_sslvpnserver", errmsgs.AlibabacloudStackSdkGoERROR)
		}

		if len(response.SslVpnServers.SslVpnServer) > 0 {
			break
		}
		if i < 11 {
			time.Sleep(time.Duration(5) * time.Second)
		}
	}
	response, _ := vpn_gatewayssl_vpn_serverservice.DoVpcDescribesslvpnserversRequest(d.Id())
	data := &response.SslVpnServers.SslVpnServer[0]
	d.Set("cipher", data.Cipher)

	d.Set("client_ip_pool", data.ClientIpPool)

	d.Set("compress", data.Compress)

	d.Set("connections", data.Connections)

	d.Set("create_time", data.CreateTime)

	d.Set("internet_ip", data.InternetIp)

	d.Set("local_subnet", data.LocalSubnet)

	d.Set("max_connections", data.MaxConnections)

	d.Set("port", data.Port)

	d.Set("proto", data.Proto)

	d.Set("ssl_vpn_server_name", data.Name)

	d.Set("vpn_gateway_id", data.VpnGatewayId)

	return nil
}

func resourceAlibabacloudStackVpngatewaySslvpnserverDelete(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	// api: Vpc - 2016-04-28 - DeleteSslVpnServer
	request := client.NewCommonRequest("POST", "Vpc", "2016-04-28", "DeleteSslVpnServer", "")
	// VpcDeletesslvpnserverResponseObj := VpcDeletesslvpnserverResponse{}

	//调用request_params_handler

	request.QueryParams["SslVpnServerId"] = d.Id()
	var errmsg string
	var err error
	for i := 0; i < 12; i++ {
		if bresponse, e := client.ProcessCommonRequest(request); e == nil {
			return nil
		} else {
			err = e
			errmsg = errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
			time.Sleep(time.Duration(5) * time.Second)
		}
	}
	return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_vpn_gateway_ssl_vpn_server", "DeleteSslVpnServer", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
}

type VpcCreatesslvpnserverResponse struct {
	RequestId      string `json:"RequestId"`
	SslVpnServerId string `json:"SslVpnServerId"`
	Name           string `json:"Name"`
}

type VpcModifysslvpnserverResponse struct {
	RequestId      string `json:"RequestId"`
	RegionId       string `json:"RegionId"`
	SslVpnServerId string `json:"SslVpnServerId"`
	VpnGatewayId   string `json:"VpnGatewayId"`
	Name           string `json:"Name"`
	LocalSubnet    string `json:"LocalSubnet"`
	ClientIpPool   string `json:"ClientIpPool"`
	CreateTime     int    `json:"CreateTime"`
	Cipher         string `json:"Cipher"`
	Proto          string `json:"Proto"`
	Port           int    `json:"Port"`
	Compress       bool   `json:"Compress"`
	Connections    int    `json:"Connections"`
	MaxConnections int    `json:"MaxConnections"`
	InternetIp     string `json:"InternetIp"`
}

type VpcDeletesslvpnserverResponse struct {
	RequestId string `json:"RequestId"`
}
