package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product DRDS Resouce Database
import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/errmsgs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
)

func resourceAlibabacloudStackDrdsRdsInstnace() *schema.Resource {
	resource := &schema.Resource{
		Schema: map[string]*schema.Schema{

			"storage_type": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
			},

			"category": {
				Type:         schema.TypeString,
				Required:     true,
				ForceNew:     true,
				ValidateFunc: validation.StringInSlice([]string{"HighAvailability"}, false),
			},

			"db_instance_class": {
				Type:     schema.TypeString,
				Required: true,
			},

			"drds_instance_id": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
			},

			"zone_id": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
			},
			"db_instance_storage": {
				Type:     schema.TypeInt,
				Required: true,
			},

			"rds_instance_id": {
				Type:     schema.TypeString,
				Computed: true,
			},

			"create_time": {
				Type:     schema.TypeString,
				Computed: true,
			},

			"status": {
				Type:     schema.TypeString,
				Computed: true,
			},
			"force_remove": {
				Type:     schema.TypeBool,
				Optional: true,
				Default:  false,
			},
		},
	}
	setResourceFunc(resource, resourceAlibabacloudStackDrdsRdsInstnaceCreate, resourceAlibabacloudStackDrdsRdsInstnaceRead, resourceAlibabacloudStackDrdsRdsInstnaceUpdate, resourceAlibabacloudStackDrdsRdsInstnaceDelete)
	return resource
}

func resourceAlibabacloudStackDrdsRdsInstnaceCreate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	drdsRdsservice := DrdsService{client}

	// api: Drds - 2019-01-23 - CreateDrdsDB
	params := map[string]interface{}{
		"commodityCode":         "bards",
		"orderType":             "BUY",
		"engine":                "MySQL",
		"azoneId":               d.Get("zone_id").(string),
		"category":              d.Get("category").(string),
		"nodeType":              d.Get("category").(string),
		"dBInstanceClass":       d.Get("db_instance_class").(string),
		"dBInstanceStorage":     d.Get("db_instance_storage").(int),
		"quantity":              1,
		"DRDSInstanceId":        d.Get("drds_instance_id").(string),
		"DBInstanceStorageType": d.Get("storage_type").(string),
		"MultiZone":             "false",
	}

	jsonBytes, err := json.Marshal(params)
	if err != nil {
		return err
	}

	reqQuery := map[string]interface{}{
		"Params": string(jsonBytes),
	}

	request, err := client.DoTeaRequest("POST", "Drds", "2019-01-23", "CreateOrderForRds", "", nil, reqQuery, nil)

	if err != nil {
		errmsg := ""
		if request != nil {
			errmsg = request["Message"].(string)
		}
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_drds_database", "CreateDrdsDB", errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}

	data := request["Data"].([]interface{})
	if len(data) == 0 {
		return fmt.Errorf("No private rds created")
	}

	d.SetId(fmt.Sprintf("%s:%s", d.Get("drds_instance_id").(string), data[0].(string)))

	stateConf := BuildStateConf([]string{"Creating"}, []string{"Running"}, d.Timeout(schema.TimeoutCreate), 10*time.Second, drdsRdsservice.PrivateRdsStateRefreshFunc(d.Id(), []string{"Stopping"}))

	if _, err := stateConf.WaitForState(); err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.IdMsg, d.Id())
	}

	return nil

}

func resourceAlibabacloudStackDrdsRdsInstnaceUpdate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	drdsRdsservice := DrdsService{client}

	if d.IsNewResource() {
		return nil
	}

	// DrdsRdsName

	// InstanceId

	// IpWhiteList

	// api: Drds - 2019-01-23 - ModifyDrdsIpWhiteList
	if d.HasChanges("db_instance_class", "db_instance_storage") {

		reqQuery := map[string]interface{}{
			"InstClass": d.Get("db_instance_class").(string),
			"Storage":   d.Get("db_instance_storage").(int),
		}
		if parts, err := ParseResourceId(d.Id(), 2); err != nil {
			return err
		} else {
			reqQuery["DrdsInstanceId"] = parts[0]
			reqQuery["StoreInstanceId"] = parts[1]
		}

		_, err := client.DoTeaRequest("POST", "Drds", "2019-01-23", "ModifyDBInstanceSpec", "", nil, reqQuery, nil)
		if err != nil {
			return err
		}
		stateConf := BuildStateConf([]string{"Changing Specifications"}, []string{"Running"}, d.Timeout(schema.TimeoutCreate), 10*time.Second, drdsRdsservice.PrivateRdsStateRefreshFunc(d.Id(), []string{"Stopping"}))

			if _, err := stateConf.WaitForState(); err != nil {
				return errmsgs.WrapErrorf(err, errmsgs.IdMsg, d.Id())
		}
	}

	return nil
}

func resourceAlibabacloudStackDrdsRdsInstnaceRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	drdsRdsservice := DrdsService{client}
	response, err := drdsRdsservice.DescribeDrdsRdsInstance(d.Id())
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg, "alibabacloudstack_drds_database", errmsgs.AlibabacloudStackSdkGoERROR)
	}
	if parts, err := ParseResourceId(d.Id(), 2); err != nil {
		return err
	} else {
		d.Set("drds_instance_id", parts[0])
		d.Set("rds_instance_id", parts[1])
	}

	d.Set("db_instance_storage", response["DBInstanceStorage"])
	d.Set("create_time", response["ExpireTime"])
	if v, err := response["DBInstanceStatus"].(json.Number).Int64(); err != nil {
		return err
	} else {
		d.Set("status", DrdsPrivateRdsDbInstanceStatus[int(v)])
	}

	return nil
}

func resourceAlibabacloudStackDrdsRdsInstnaceDelete(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	drdsRdsservice := DrdsService{client}
	// api: Drds - 2019-01-23 - RemoveDrdsDb
	request := client.NewCommonRequest("POST", "Drds", "2019-01-23", "RemoveDrdsMysql", "")

	//调用request_params_handler
	if parts, err := ParseResourceId(d.Id(), 2); err != nil {
		return err
	} else {
		request.QueryParams["DrdsInstanceId"] = parts[0]
		request.QueryParams["DbInstanceId"] = parts[1]
	}
	if d.Get("force_remove").(bool) {
		request.QueryParams["Force"] = "true"
	} else {
		request.QueryParams["Force"] = "false"
	}

	bresponse, err := client.ProcessCommonRequest(request)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_drds_database", "RemoveDrdsDb", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}

	stateConf := BuildStateConf([]string{"Running", "Deleting"}, []string{}, d.Timeout(schema.TimeoutCreate), 10*time.Second, drdsRdsservice.PrivateRdsStateRefreshFunc(d.Id(), []string{"Stopping"}))

	if _, err := stateConf.WaitForState(); err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.IdMsg, d.Id())
	}

	return nil
}
