package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product DRDS Resouce Account
import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/errmsgs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
)

func resourceAlibabacloudStackDrdsPolardbxAccount() *schema.Resource {
	resource := &schema.Resource{
		Schema: map[string]*schema.Schema{

			"instance_id": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
			},

			"account_name": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
			},

			"description": {
				Type:     schema.TypeString,
				Optional: true,
				Computed: true,
			},

			"account_type": {
				Type:         schema.TypeString,
				Optional:     true,
				Computed:     true,
				ValidateFunc: validation.StringInSlice([]string{"Normal", "Super"}, false),
			},
			"password": {
				Type:      schema.TypeString,
				Required:  true,
				Sensitive: true,
			},

			"db_privileges": {
				Type:     schema.TypeSet,
				Optional: true,
				Computed: true,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"db_name": {
							Type:     schema.TypeString,
							Required: true,
						},
						"privilege": {
							Type:         schema.TypeString,
							Required:     true,
							ValidateFunc: validation.StringInSlice([]string{"ReadOnly", "ReadWrite", "DMLOnly", "DDLOnly"}, false),
						},
					},
				},
			},
		},
	}
	setResourceFunc(resource, resourceAlibabacloudStackDrdsPolardbxAccountCreate, resourceAlibabacloudStackDrdsPolardbxAccountRead, resourceAlibabacloudStackDrdsPolardbxAccountUpdate, resourceAlibabacloudStackDrdsPolardbxAccountDelete)
	return resource
}

func resourceAlibabacloudStackDrdsPolardbxAccountCreate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	account_type := d.Get("account_type").(string)
	action := "CreateAccount"
	if account_type == "Super" {
		action = "CreateSuperAccount"
	}
	reqQuery := map[string]interface{}{
		"DBInstanceName":     d.Get("instance_id").(string),
		"AccountName":        d.Get("account_name").(string),
		"AccountType":        account_type,
		"AccountPassword":    d.Get("password").(string),
		"AccountDescription": d.Get("description").(string),
	}

	privileges := make([]string, 0)
	dbname := make([]string, 0)
	for _, d := range d.Get("db_privileges").(*schema.Set).List() {
		dbPrivilege := d.(map[string]interface{})
		privileges = append(privileges, dbPrivilege["privilege"].(string))
		dbname = append(dbname, dbPrivilege["db_name"].(string))
	}
	reqQuery["AccountPrivilege"] = strings.Join(privileges, ",")
	reqQuery["DBName"] = strings.Join(dbname, ",")

	_, err := client.DoTeaRequest("POST", "polardbx", "2020-02-02", action, "", nil, reqQuery, nil)
	if err != nil {
		return err
	}

	d.SetId(fmt.Sprintf("%s:%s", d.Get("instance_id").(string), d.Get("account_name").(string)))
	return nil

}

func resourceAlibabacloudStackDrdsPolardbxAccountUpdate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)

	var instanceId, DrdsPolardbxAccountName string
	if parts, err := ParseResourceId(d.Id(), 2); err != nil {
		return err
	} else {
		instanceId = parts[0]
		DrdsPolardbxAccountName = parts[1]
	}

	if d.HasChanges("description") && d.Get("description").(string) != "" {
		request := client.NewCommonRequest("POST", "polardbx", "2020-02-02", "ModifyAccountDescription", "")

		request.QueryParams["AccountDescription"] = d.Get("description").(string)
		request.QueryParams["AccountName"] = DrdsPolardbxAccountName
		request.QueryParams["DBInstanceName"] = instanceId

		bresponse, err := client.ProcessCommonRequest(request)
		if err != nil {
			if bresponse == nil {
				return errmsgs.WrapErrorf(err, "Process Common Request Failed")
			}
			errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
			return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,
				"alibabacloudstack_drds_polardbx_account", "ModifyAccountDescription", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
		}

	}

	if d.IsNewResource() {
		return nil
	}

	if d.HasChanges("password") {
		request := client.NewCommonRequest("POST", "polardbx", "2020-02-02", "ResetAccountPassword", "")
		DrdsChangeaccountpasswordResponse := DrdsChangeaccountpasswordResponse{}

		request.QueryParams["AccountName"] = DrdsPolardbxAccountName
		request.QueryParams["DBInstanceName"] = instanceId

		request.QueryParams["AccountPassword"] = d.Get("password").(string)

		bresponse, err := client.ProcessCommonRequest(request)
		if err != nil {
			if bresponse == nil {
				return errmsgs.WrapErrorf(err, "Process Common Request Failed")
			}
			errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
			return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,
				"alibabacloudstack_drds_polardbx_account", "ResetAccountPassword", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
		}

		err = json.Unmarshal(bresponse.GetHttpContentBytes(), &DrdsChangeaccountpasswordResponse)
		if err != nil {
			return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
				"alibabacloudstack_drds_polardbx_account", "ResetAccountPassword", errmsgs.AlibabacloudStackSdkGoERROR)
		}

	}

	// DbPrivileges

	// DrdsPolardbxAccountName

	// InstanceId

	// api: Drds - 2019-01-23 - ModifyAccountPrivilege
	if d.HasChanges("db_privileges") {
		reqQuery := map[string]interface{}{
			"DBInstanceName": d.Get("instance_id").(string),
			"AccountName":    d.Get("drds_account_name").(string),
		}

		privileges := make([]string, 0)
		dbname := make([]string, 0)
		for _, d := range d.Get("db_privileges").(*schema.Set).List() {
			dbPrivilege := d.(map[string]interface{})
			privileges = append(privileges, dbPrivilege["privilege"].(string))
			dbname = append(dbname, dbPrivilege["db_name"].(string))
		}
		reqQuery["AccountPrivilege"] = strings.Join(privileges, ",")
		reqQuery["DBName"] = strings.Join(dbname, ",")
		_, err := client.DoTeaRequest("POST", "polardbx", "2020-02-02", "ModifyAccountPrivilege", "", nil, reqQuery, nil)
		if err != nil {
			return err
		}
	}

	return nil
}

func resourceAlibabacloudStackDrdsPolardbxAccountRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	Polardbxservice := PolardbXService{client}
	account, err := Polardbxservice.DoPolardbxDescribeAccountListRequest(d.Id())
	if err != nil {
		if errmsgs.NotFoundError(err) {
			d.SetId("")
		}
		return errmsgs.WrapError(err)
	}

	d.Set("description", account.AccountDescription)
	d.Set("account_name", account.AccountName)
	switch account.AccountType {
	case "0":
		d.Set("account_type", "Normal")
	case "1":
		d.Set("account_type", "Super")
	}
	db_names := make([]string, 0)
	if account.DBName != "" {
		db_names = strings.Split(account.DBName, ",")
	}
	privileges := make([]string, 0)
	if account.AccountPrivilege != "" {
		privileges = strings.Split(account.AccountPrivilege, ",")
	}
	if len(db_names) > 0 && len(privileges) > 0 {
		db_privileges := make([]map[string]interface{}, 0)
		for i, db_name := range db_names {
			db_privileges = append(db_privileges, map[string]interface{}{
				"db_name":   db_name,
				"privilege": privileges[i],
			})
		}
		d.Set("db_privileges", db_privileges)
	}
	return nil
}

func resourceAlibabacloudStackDrdsPolardbxAccountDelete(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	// api: Drds - 2019-01-23 - RemoveInstanceAccount
	request := client.NewCommonRequest("POST", "polardbx", "2020-02-02", "DeleteAccount", "")
	parts, err := ParseResourceId(d.Id(), 2)
	if err != nil {
		return err
	}
	//调用request_params_handler
	request.QueryParams["DBInstanceName"] = parts[0]
	request.QueryParams["AccountName"] = parts[1]

	bresponse, err := client.ProcessCommonRequest(request)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_drds_polardbx_account", "DeleteAccount", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}

	return nil
}

type DrdsCreateAccountResponse struct {
	RequestId string `json:"RequestId"`
	Success   bool   `json:"Success"`
}
