package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product DRDS Resouce Account
import (
	"fmt"

	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/errmsgs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
)

func resourceAlibabacloudStackPolardbxAccountDatabaseBinding() *schema.Resource {
	resource := &schema.Resource{
		Schema: map[string]*schema.Schema{

			"instance_id": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
			},

			"account_name": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
			},

			"db_name": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
			},
			"privilege": {
				Type:         schema.TypeString,
				Required:     true,
				ValidateFunc: validation.StringInSlice([]string{"ReadOnly", "ReadWrite", "DMLOnly", "DDLOnly"}, false),
			},
		},
	}
	setResourceFunc(resource, resourceAlibabacloudStackPolardbxAccountDatabaseBindingCreate, resourceAlibabacloudStackPolardbxAccountDatabaseBindingRead, resourceAlibabacloudStackPolardbxAccountDatabaseBindingUpdate, resourceAlibabacloudStackPolardbxAccountDatabaseBindingDelete)
	return resource
}

func resourceAlibabacloudStackPolardbxAccountDatabaseBindingCreate(d *schema.ResourceData, meta interface{}) error {
	accountName := d.Get("account_name").(string)
	instanceID := d.Get("instance_id").(string)
	db_name := d.Get("db_name").(string)
	d.SetId(fmt.Sprintf("%s:%s:%s", instanceID, accountName, db_name))
	return nil
}

func resourceAlibabacloudStackPolardbxAccountDatabaseBindingUpdate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	privilege := d.Get("privilege").(string)
	Polardbxservice := PolardbXService{client}
	return Polardbxservice.PolardbxAccountDatabaseBinding(d.Id(), privilege)
}

func resourceAlibabacloudStackPolardbxAccountDatabaseBindingRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	Polardbxservice := PolardbXService{client}
	privilege, err := Polardbxservice.DescribePolardbXAccountDBPrivilege(d.Id())
	if err != nil {
		if errmsgs.NotFoundError(err) {
			d.SetId("")
		}
		return errmsgs.WrapError(err)
	}

	d.Set("instance_id", privilege.InstanceId)
	d.Set("account_name", privilege.AccountName)
	d.Set("db_name", privilege.DBName)
	d.Set("privilege", privilege.Privilege)
	return nil
}

func resourceAlibabacloudStackPolardbxAccountDatabaseBindingDelete(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	privilege := "none"
	Polardbxservice := PolardbXService{client}
	return Polardbxservice.PolardbxAccountDatabaseBinding(d.Id(), privilege)
}
