package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product EBS Resouce DiskReplicaGroup
import (
	"encoding/json"
	"fmt"
	"strconv"
	"time"

	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/errmsgs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func resourceAlibabacloudStackEbsDiskreplicagroup() *schema.Resource {
	resource := &schema.Resource{
		Schema: map[string]*schema.Schema{
			"description": {
				Type:     schema.TypeString,
				Optional: true,
			},

			"destination_region_id": {
				Type:     schema.TypeString,
				Required: true,
			},

			"destination_zone_id": {
				Type:     schema.TypeString,
				Required: true,
			},

			"disk_replica_group_name": {
				Type:     schema.TypeString,
				Optional: true,
			},

			"last_recover_point": {
				Type:     schema.TypeInt,
				Optional: true,
				Computed: true,
			},

			"pair_ids": {
				Type:     schema.TypeList,
				Computed: true,
				Elem:     &schema.Schema{Type: schema.TypeString},
			},

			"pair_number": {
				Type:     schema.TypeInt,
				Computed: true,
			},

			// "bandwidth": {
			// 	Type:     schema.TypeInt,
			// 	Optional: true,
			// 	Computed: true,
			// },
			// 环境测试中，属性设置和修改无效

			"rpo": {
				Type:     schema.TypeInt,
				Optional: true,
				Computed: true,
			},

			"region_id": {
				Type:     schema.TypeString,
				Optional: true,
			},

			"site": {
				Type:     schema.TypeString,
				Optional: true,
			},

			"source_region_id": {
				Type:     schema.TypeString,
				Required: true,
			},

			"source_zone_id": {
				Type:     schema.TypeString,
				Required: true,
			},
			
			"replica_group_id":{
				Type:     schema.TypeString,
				Computed: true,
			},

			"status": {
				Type:     schema.TypeString,
				Optional: true,
				Computed: true,
			},

			"tags": tagsSchema(),
		},
	}
	setResourceFunc(resource, resourceAlibabacloudStackEbsDiskreplicagroupCreate,
		resourceAlibabacloudStackEbsDiskreplicagroupRead,
		resourceAlibabacloudStackEbsDiskreplicagroupUpdate,
		resourceAlibabacloudStackEbsDiskreplicagroupDelete)
	return resource
}

func resourceAlibabacloudStackEbsDiskreplicagroupCreate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)

	// api: ebs - 2021-07-30 - CreateDiskReplicaGroup
	request := client.NewCommonRequest("POST", "ebs", "2021-07-30", "CreateDiskReplicaGroup", "")
	EbsCreatediskreplicagroupResponse := &EbsCreatediskreplicagroupResponse{}

	//调用request_params_handler

	if v, ok := d.GetOk("description"); ok {
		request.QueryParams["Description"] = v.(string)
	}

	if v, ok := d.GetOk("destination_region_id"); ok {
		request.QueryParams["DestinationRegionId"] = v.(string)
	} else {
		return fmt.Errorf("DestinationRegionId is required")
	}

	if v, ok := d.GetOk("destination_zone_id"); ok {
		request.QueryParams["DestinationZoneId"] = v.(string)
	} else {
		return fmt.Errorf("DestinationZoneId is required")
	}

	if v, ok := d.GetOk("disk_replica_group_name"); ok {
		request.QueryParams["GroupName"] = v.(string)
	}

	if v, ok := d.GetOk("rpo"); ok {
		request.QueryParams["RPO"] = strconv.Itoa(v.(int))
	}

	// if v, ok := d.GetOk("bandwidth"); ok {
	// 	request.QueryParams["Bandwidth"] = v.(string)
	// }

	if v, ok := d.GetOk("source_region_id"); ok {
		request.QueryParams["RegionId"] = v.(string)
	} else {
		return fmt.Errorf("SourceRegionId is required")
	}

	if v, ok := d.GetOk("source_zone_id"); ok {
		request.QueryParams["SourceZoneId"] = v.(string)
	} else {
		return fmt.Errorf("SourceZoneId is required")
	}

	bresponse, err := client.ProcessCommonRequest(request)
	addDebug(request.GetActionName(), bresponse, request, request.QueryParams)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_ebs_disk_replica_group", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}

	err = json.Unmarshal(bresponse.GetHttpContentBytes(), &EbsCreatediskreplicagroupResponse)
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
			"alibabacloudstack_ebs_disk_replica_group", "CreateDiskReplicaGroup", errmsgs.AlibabacloudStackSdkGoERROR)
	}

	replica_group_id := EbsCreatediskreplicagroupResponse.ReplicaGroupId
	d.SetId(fmt.Sprintf("%s", replica_group_id))
	ebsdisk_replica_groupservice := EbsService{client}
	stateConf := BuildStateConf([]string{"creating"}, []string{"created"}, d.Timeout(schema.TimeoutCreate), 10*time.Second, ebsdisk_replica_groupservice.EbsDiskreplicagroupStatusRefreshFunc(d.Id(), []string{"failed"}))

	if _, err := stateConf.WaitForState(); err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.IdMsg, d.Id())
	}
	return nil

}

func resourceAlibabacloudStackEbsDiskreplicagroupUpdate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)

	// api: ebs - 2021-07-30 - ModifyDiskReplicaGroup
	if d.HasChanges("description", "disk_replica_group_name", "rpo") {
		request := client.NewCommonRequest("POST", "ebs", "2021-07-30", "ModifyDiskReplicaGroup", "")
		EbsModifydiskreplicagroupResponse := &EbsModifydiskreplicagroupResponse{}
		request.QueryParams["ReplicaGroupId"] = d.Id()
		if v, ok := d.GetOk("description"); ok {
			request.QueryParams["Description"] = v.(string)
		}

		if v, ok := d.GetOk("disk_replica_group_name"); ok {
			request.QueryParams["GroupName"] = v.(string)
		}

		if v, ok := d.GetOk("rpo"); ok { 
			request.QueryParams["RPO"] = fmt.Sprintf("%d", v.(int))
		}

		// if v, ok := d.GetOk("bandwidth"); ok {
		// 	request.QueryParams["Bandwidth"] = v.(string)
		// }

		bresponse, err := client.ProcessCommonRequest(request)
		addDebug(request.GetActionName(), bresponse, request, request.QueryParams)
		if err != nil {
			if bresponse == nil {
				return errmsgs.WrapErrorf(err, "Process Common Request Failed")
			}
			errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
			return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,
				"alibabacloudstack_ebs_disk_replica_group", "ModifyDiskReplicaGroup", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
		}

		err = json.Unmarshal(bresponse.GetHttpContentBytes(), &EbsModifydiskreplicagroupResponse)
		if err != nil {
			return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
				"alibabacloudstack_ebs_disk_replica_group", "ModifyDiskReplicaGroup", errmsgs.AlibabacloudStackSdkGoERROR)
		}

	}

	// RegionId

	// ReplicaGroupId

	// api: ebs - 2021-07-30 - RemoveDiskReplicaPair
	// if d.HasChanges("region_id") {
	// 	request := client.NewCommonRequest("POST", "ebs", "2021-07-30", "RemoveDiskReplicaPair", "")
	// 	EbsRemovediskreplicapairResponse := &EbsRemovediskreplicapairResponse{}
	//  request.QueryParams["ReplicaGroupId"] = d.Id()
	// 	request.QueryParams["RegionId"] = d.Get("source_region_id").(string)

	// 	bresponse, err := client.ProcessCommonRequest(request)
	// 	addDebug(request.GetActionName(), bresponse, request, request.QueryParams)
	// 	if err != nil {
	// 		if bresponse == nil {
	// 			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
	// 		}
	// 		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
	// 		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,
	// 			"alibabacloudstack_ebs_disk_replica_group", "RemoveDiskReplicaPair", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	// 	}

	// 	err = json.Unmarshal(bresponse.GetHttpContentBytes(), &EbsRemovediskreplicapairResponse)
	// 	if err != nil {
	// 		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
	// 			"alibabacloudstack_ebs_disk_replica_group", "RemoveDiskReplicaPair", errmsgs.AlibabacloudStackSdkGoERROR)
	// 	}

	// }

	// RegionId

	// ReplicaGroupId

	// api: ebs - 2021-07-30 - ReprotectDiskReplicaGroup
	// if d.HasChanges("region_id") {
	// 	request := client.NewCommonRequest("POST", "ebs", "2021-07-30", "ReprotectDiskReplicaGroup", "")
	// 	EbsReprotectdiskreplicagroupResponse := &EbsReprotectdiskreplicagroupResponse{}
	//  request.QueryParams["ReplicaGroupId"] = d.Id()
	// 	request.QueryParams["RegionId"] = d.Get("source_region_id").(string)

	// 	bresponse, err := client.ProcessCommonRequest(request)
	// 	addDebug(request.GetActionName(), bresponse, request, request.QueryParams)
	// 	if err != nil {
	// 		if bresponse == nil {
	// 			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
	// 		}
	// 		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
	// 		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,
	// 			"alibabacloudstack_ebs_disk_replica_group", "ReprotectDiskReplicaGroup", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	// 	}

	// 	err = json.Unmarshal(bresponse.GetHttpContentBytes(), &EbsReprotectdiskreplicagroupResponse)
	// 	if err != nil {
	// 		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
	// 			"alibabacloudstack_ebs_disk_replica_group", "ReprotectDiskReplicaGroup", errmsgs.AlibabacloudStackSdkGoERROR)
	// 	}

	// }

	// api: ebs - 2021-07-30 - StartDiskReplicaGroup

	// 	request := client.NewCommonRequest("POST", "ebs", "2021-07-30", "StartDiskReplicaGroup", "")
	// 	EbsStartdiskreplicagroupResponse := &EbsStartdiskreplicagroupResponse{}
	//  request.QueryParams["ReplicaGroupId"] = d.Id()

	// 	bresponse, err := client.ProcessCommonRequest(request)
	// 	addDebug(request.GetActionName(), bresponse, request, request.QueryParams)
	// 	if err != nil {
	// 		if bresponse == nil {
	// 			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
	// 		}
	// 		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
	// 		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,
	// 			"alibabacloudstack_ebs_disk_replica_group", "StartDiskReplicaGroup", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	// 	}

	// 	err = json.Unmarshal(bresponse.GetHttpContentBytes(), &EbsStartdiskreplicagroupResponse)
	// 	if err != nil {
	// 		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
	// 			"alibabacloudstack_ebs_disk_replica_group", "StartDiskReplicaGroup", errmsgs.AlibabacloudStackSdkGoERROR)
	// 	}

	// }

	// RegionId

	// ReplicaGroupId

	// api: ebs - 2021-07-30 - StopDiskReplicaGroup
	// if d.HasChanges("region_id") {
	// 	request := client.NewCommonRequest("POST", "ebs", "2021-07-30", "StopDiskReplicaGroup", "")
	// 	EbsStopdiskreplicagroupResponse := &EbsStopdiskreplicagroupResponse{}

	// 	request.QueryParams["ReplicaGroupId"] = d.Id()

	// 	bresponse, err := client.ProcessCommonRequest(request)
	// 	addDebug(request.GetActionName(), bresponse, request, request.QueryParams)
	// 	if err != nil {
	// 		if bresponse == nil {
	// 			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
	// 		}
	// 		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
	// 		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,
	// 			"alibabacloudstack_ebs_disk_replica_group", "StopDiskReplicaGroup", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	// 	}

	// 	err = json.Unmarshal(bresponse.GetHttpContentBytes(), &EbsStopdiskreplicagroupResponse)
	// 	if err != nil {
	// 		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
	// 			"alibabacloudstack_ebs_disk_replica_group", "StopDiskReplicaGroup", errmsgs.AlibabacloudStackSdkGoERROR)
	// 	}

	// }

	return nil
}

func resourceAlibabacloudStackEbsDiskreplicagroupRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	ebsdisk_replica_groupservice := EbsService{client}
	data, err := ebsdisk_replica_groupservice.DescribeEbsDiskreplicagroups(d.Id())
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg, "alibabacloudstack_ebs_diskreplicagroup", errmsgs.AlibabacloudStackSdkGoERROR)
	}
	d.Set("description", data.Description)

	d.Set("destination_region_id", data.DestinationRegionId)

	d.Set("destination_zone_id", data.DestinationZoneId)

	d.Set("disk_replica_group_name", data.GroupName)

	d.Set("last_recover_point", data.LastRecoverPoint)

	d.Set("pair_number", data.PairNumber)

	d.Set("rpo", data.RPO)

	d.Set("pair_ids", data.PairIds)

	d.Set("site", data.Site)

	d.Set("source_region_id", data.SourceRegionId)

	d.Set("source_zone_id", data.SourceZoneId)

	d.Set("status", data.Status)
	
	d.Set("replica_group_id", data.ReplicaGroupId)

	return nil
}

func resourceAlibabacloudStackEbsDiskreplicagroupDelete(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	// api: ebs - 2021-07-30 - DeleteDiskReplicaGroup
	request := client.NewCommonRequest("POST", "ebs", "2021-07-30", "DeleteDiskReplicaGroup", "")
	// EbsDeletediskreplicagroupResponse := &EbsDeletediskreplicagroupResponse{}

	//调用request_params_handler
	request.QueryParams["ReplicaGroupId"] = d.Id()
	request.QueryParams["RegionId"] = d.Get("source_region_id").(string)
	bresponse, err := client.ProcessCommonRequest(request)
	addDebug(request.GetActionName(), bresponse, request, request.QueryParams)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_ebs_disk_replica_group", "DeleteDiskReplicaGroup", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}
	ebsdisk_replica_groupservice := EbsService{client}
	stateConf := BuildStateConf([]string{"deleting"}, []string{}, d.Timeout(schema.TimeoutCreate), 10*time.Second, ebsdisk_replica_groupservice.EbsDiskreplicagroupStatusRefreshFunc(d.Id(), []string{"failed"}))

	if _, err := stateConf.WaitForState(); err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.IdMsg, d.Id())
	}
	return nil
}

type EbsCreatediskreplicagroupResponse struct {
	RequestId      string `json:"RequestId"`
	ReplicaGroupId string `json:"ReplicaGroupId"`
}

type EbsAdddiskreplicapairResponse struct {
	RequestId string `json:"RequestId"`
}
type EbsFailoverdiskreplicagroupResponse struct {
	RequestId string `json:"RequestId"`
}
type EbsModifydiskreplicagroupResponse struct {
	RequestId string `json:"RequestId"`
}
type EbsRemovediskreplicapairResponse struct {
	RequestId string `json:"RequestId"`
}
type EbsReprotectdiskreplicagroupResponse struct {
	RequestId string `json:"RequestId"`
}
type EbsStartdiskreplicagroupResponse struct {
	RequestId string `json:"RequestId"`
}
type EbsStopdiskreplicagroupResponse struct {
	RequestId string `json:"RequestId"`
}

type EbsDeletediskreplicagroupResponse struct {
	RequestId string `json:"RequestId"`
}
