package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product ExpressConnect Resouce VbrPconnAssociation
import (
	"encoding/json"
	"fmt"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/errmsgs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func resourceAlibabacloudStackExpressconnectVbrpconnassociation() *schema.Resource {
	resource := &schema.Resource{
		Schema: map[string]*schema.Schema{
			"physical_connection_id": {
				Type:     schema.TypeString,
				Required: true,
			},
			"vbr_id": {
				Type:     schema.TypeString,
				Required: true,
			},
			"vlan_id": {
				Type:     schema.TypeString,
				Required: true,
			},
			"circuit_code": {
				Type:     schema.TypeString,
				Optional: true,
			},
			"local_gateway_ip": {
				Type:     schema.TypeString,
				Optional: true,
			},
			"peer_gateway_ip": {
				Type:     schema.TypeString,
				Optional: true,
			},
			"peering_subnet_mask": {
				Type:     schema.TypeString,
				Optional: true,
			},
			"enable_ipv6": {
				Type:     schema.TypeString,
				Optional: true,
				Default:  "false",
			},
			"local_ipv6_gateway_ip": {
				Type:     schema.TypeString,
				Optional: true,
			},
			"peer_ipv6_gateway_ip": {
				Type:     schema.TypeString,
				Optional: true,
			},
			"peering_ipv6_subnet_mask": {
				Type:     schema.TypeString,
				Optional: true,
			},
			"status": {
				Type:     schema.TypeString,
				Computed: true,
			},
		},
	}
	setResourceFunc(resource, resourceAlibabacloudStackExpressconnectVbrpconnassociationCreate,
		resourceAlibabacloudStackExpressconnectVbrpconnassociationRead,
		resourceAlibabacloudStackExpressconnectVbrpconnassociationUpdate,
		resourceAlibabacloudStackExpressconnectVbrpconnassociationDelete)
	return resource
}

func resourceAlibabacloudStackExpressconnectVbrpconnassociationCreate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)

	// api: Vpc - 2016-04-28 - AssociatePhysicalConnectionToVirtualBorderRouter
	request := client.NewCommonRequest("POST", "Vpc", "2016-04-28", "AssociatePhysicalConnectionToVirtualBorderRouter", "")
	VpcAssociatephysicalconnectiontovirtualborderrouterResponseObj := VpcAssociatephysicalconnectiontovirtualborderrouterResponse{}

	//调用request_params_handler

	if v, ok := d.GetOk("enable_ipv6"); ok {
		request.QueryParams["EnableIpv6"] = v.(string)
	}
	if v, ok := d.GetOk("local_gateway_ip"); ok {
		request.QueryParams["LocalGatewayIp"] = v.(string)
	}
	if v, ok := d.GetOk("local_ipv6_gateway_ip"); ok {
		request.QueryParams["LocalIpv6GatewayIp"] = v.(string)
	}
	if v, ok := d.GetOk("peer_gateway_ip"); ok {
		request.QueryParams["PeerGatewayIp"] = v.(string)
	}
	if v, ok := d.GetOk("peer_ipv6_gateway_ip"); ok {
		request.QueryParams["PeerIpv6GatewayIp"] = v.(string)
	}
	if v, ok := d.GetOk("peering_ipv6_subnet_mask"); ok {
		request.QueryParams["PeeringIpv6SubnetMask"] = v.(string)
	}
	if v, ok := d.GetOk("peering_subnet_mask"); ok {
		request.QueryParams["PeeringSubnetMask"] = v.(string)
	}
	request.QueryParams["PhysicalConnectionId"] = d.Get("physical_connection_id").(string)
	request.QueryParams["VbrId"] = d.Get("vbr_id").(string)
	request.QueryParams["VlanId"] = d.Get("vlan_id").(string)

	bresponse, err := client.ProcessCommonRequest(request)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_express_connect_vbr_pconn_association", "AssociatePhysicalConnectionToVirtualBorderRouter", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}

	err = json.Unmarshal(bresponse.GetHttpContentBytes(), &VpcAssociatephysicalconnectiontovirtualborderrouterResponseObj)
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
			"alibabacloudstack_express_connect_vbr_pconn_association", "AssociatePhysicalConnectionToVirtualBorderRouter", errmsgs.AlibabacloudStackSdkGoERROR)
	}

	physical_connection_id := d.Get("physical_connection_id").(string)

	vbr_id := d.Get("vbr_id").(string)

	d.SetId(fmt.Sprintf("%s", physical_connection_id+":"+vbr_id))
	return nil

}

func resourceAlibabacloudStackExpressconnectVbrpconnassociationUpdate(d *schema.ResourceData, meta interface{}) error {
	//client := meta.(*connectivity.AlibabacloudStackClient)
	if d.IsNewResource() {
		return nil
	}
	return nil
}

func resourceAlibabacloudStackExpressconnectVbrpconnassociationRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	expressconnectService := ExpressconnectService{client}
	response, err := expressconnectService.DoVpcDescribevirtualborderroutersRequest(d.Id())
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg, "alibabacloudstack_expressconnect_vbrpconnassociation", errmsgs.AlibabacloudStackSdkGoERROR)
	}
	data := response.VirtualBorderRouterSet.VirtualBorderRouterType[0].AssociatedPhysicalConnections.AssociatedPhysicalConnection[0]
	d.Set("circuit_code", data.CircuitCode)

	d.Set("enable_ipv6", data.EnableIpv6)

	d.Set("local_gateway_ip", data.LocalGatewayIp)

	d.Set("local_ipv6_gateway_ip", data.LocalIpv6GatewayIp)

	d.Set("peer_gateway_ip", data.PeerGatewayIp)

	d.Set("peer_ipv6_gateway_ip", data.PeerIpv6GatewayIp)

	d.Set("peering_ipv6_subnet_mask", data.PeeringIpv6SubnetMask)

	d.Set("peering_subnet_mask", data.PeeringSubnetMask)

	d.Set("physical_connection_id", data.PhysicalConnectionId)

	d.Set("record_total", data)

	d.Set("status", data.Status)

	d.Set("vlan_id", data.VlanId)

	return nil
}

func resourceAlibabacloudStackExpressconnectVbrpconnassociationDelete(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	// api: Vpc - 2016-04-28 - UnassociatePhysicalConnectionFromVirtualBorderRouter
	request := client.NewCommonRequest("POST", "Vpc", "2016-04-28", "UnassociatePhysicalConnectionFromVirtualBorderRouter", "")
	VpcUnassociatephysicalconnectionfromvirtualborderrouterResponseObj := VpcUnassociatephysicalconnectionfromvirtualborderrouterResponse{}

	//调用request_params_handler

	request.QueryParams["PhysicalConnectionId"] = d.Get("physical_connection_id").(string)
	request.QueryParams["VbrId"] = d.Get("vbr_id").(string)

	bresponse, err := client.ProcessCommonRequest(request)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_express_connect_vbr_pconn_association", "UnassociatePhysicalConnectionFromVirtualBorderRouter", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}

	err = json.Unmarshal(bresponse.GetHttpContentBytes(), &VpcUnassociatephysicalconnectionfromvirtualborderrouterResponseObj)
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
			"alibabacloudstack_express_connect_vbr_pconn_association", "UnassociatePhysicalConnectionFromVirtualBorderRouter", errmsgs.AlibabacloudStackSdkGoERROR)
	}

	return nil
}

type VpcAssociatephysicalconnectiontovirtualborderrouterResponse struct {
	RequestId string `json:"RequestId"`
}

type VpcUnassociatephysicalconnectionfromvirtualborderrouterResponse struct {
	RequestId string `json:"RequestId"`
}
