package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product PolarDB Resouce Backup
import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/errmsgs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
)

func resourceAlibabacloudStackPolardbBackup() *schema.Resource {
	resource := &schema.Resource{
		Schema: map[string]*schema.Schema{
			"backup_method": {
				Type:         schema.TypeString,
				Optional:     true,
				Computed:     true,
				ValidateFunc: validation.StringInSlice([]string{"Logical", "Physical", "Snapshot"}, false),
			},

			"backup_intranet_download_url": {
				Type:     schema.TypeString,
				Computed: true,
			},

			"backup_mode": {
				Type:     schema.TypeString,
				Computed: true,
			},

			"backup_size": {
				Type:     schema.TypeInt,
				Computed: true,
			},

			"backup_id": {
				Type:     schema.TypeString,
				Computed: true,
			},

			"slave_status": {
				Type:     schema.TypeString,
				Computed: true,
			},

			"host_instance_id": {
				Type:     schema.TypeString,
				Computed: true,
			},

			"backup_db_names": {
				Type:     schema.TypeString,
				Computed: true,
			},

			"store_status": {
				Type:     schema.TypeString,
				Computed: true,
			},

			"db_instance_id": {
				Type:     schema.TypeString,
				Required: true,
			},

			"db_name": {
				Type:     schema.TypeString,
				Optional: true,
			},

			"backup_download_url": {
				Type:     schema.TypeString,
				Computed: true,
			},

			"backup_end_time": {
				Type:     schema.TypeString,
				Computed: true,
			},

			"backup_start_time": {
				Type:     schema.TypeString,
				Computed: true,
			},

			"backup_type": {
				Type:         schema.TypeString,
				Optional:     true,
				Computed:     true,
				ValidateFunc: validation.StringInSlice([]string{"Auto", "FullBackup"}, false),
			},
			"backup_strategy": {
				Type:         schema.TypeString,
				Optional:     true,
				Computed:     true,
				ValidateFunc: validation.StringInSlice([]string{"instance", "db"}, false),
			},
			"meta_status": {
				Type:     schema.TypeString,
				Computed: true,
			},

			"backup_scale": {
				Type:     schema.TypeString,
				Computed: true,
			},

			"backup_status": {
				Type:     schema.TypeString,
				Computed: true,
			},

			"backup_location": {
				Type:     schema.TypeString,
				Computed: true,
			},
		},
	}
	setResourceFunc(resource, resourceAlibabacloudStackPolardbBackupCreate,
		resourceAlibabacloudStackPolardbBackupRead,
		resourceAlibabacloudStackPolardbBackupUpdate,
		resourceAlibabacloudStackPolardbBackupDelete)
	return resource
}

func resourceAlibabacloudStackPolardbBackupCreate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)

	// api: polardb - 2017-08-01 - CreateBackup
	request := client.NewCommonRequest("POST", "polardb", "2024-01-30", "CreateBackup", "")
	PolardbCreatebackupResponseObj := PolardbCreatebackupResponse{}

	//调用request_params_handler

	request.QueryParams["DBInstanceId"] = d.Get("db_instance_id").(string)

	if v, ok := d.GetOk("backup_method"); ok {
		request.QueryParams["BackupMethod"] = v.(string)
		if v.(string) == "logical" {
			if v, ok := d.GetOk("backup_strategy"); ok {
				request.QueryParams["BackupStrategy"] = v.(string)
			} else {
				request.QueryParams["BackupStrategy"] = "instance"
			}
		}
	}

	if v, ok := d.GetOk("db_name"); ok {
		request.QueryParams["DBName"] = v.(string)
	}

	if v, ok := d.GetOk("backup_type"); ok {
		request.QueryParams["BackupType"] = v.(string)
	}

	bresponse, err := client.ProcessCommonRequest(request)
	addDebug(request.GetActionName(), bresponse, request, request.QueryParams)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_polar_db_backup", "CreateBackup", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}

	err = json.Unmarshal(bresponse.GetHttpContentBytes(), &PolardbCreatebackupResponseObj)
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
			"alibabacloudstack_polar_db_backup", "CreateBackup", errmsgs.AlibabacloudStackSdkGoERROR)
	}

	backup_jobid := PolardbCreatebackupResponseObj.BackupJobId
	d.SetId(fmt.Sprintf("%s:%s", d.Get("db_instance_id").(string), backup_jobid))
	polar_dbbackupservice := PolardbService{client}
	stateConf := BuildStateConf([]string{}, []string{"Success"}, d.Timeout(schema.TimeoutCreate), 2*time.Minute, polar_dbbackupservice.PolardbDescribebackupsStateRefreshFunc(d.Id(), []string{"Failed"}))
	if _, err := stateConf.WaitForState(); err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.IdMsg, d.Id())
	}
	return nil
}

func resourceAlibabacloudStackPolardbBackupUpdate(d *schema.ResourceData, meta interface{}) error {
	return nil
}

func resourceAlibabacloudStackPolardbBackupRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	polar_dbbackupservice := PolardbService{client}
	data, err := polar_dbbackupservice.DoPolardbDescribebackupsRequest(d.Id())
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg, "alibabacloudstack_polardb_backup", errmsgs.AlibabacloudStackSdkGoERROR)
	}
	d.Set("backup_method", data.BackupMethod)
	d.Set("backup_intranet_download_url", data.BackupIntranetDownloadURL)
	d.Set("backup_mode", data.BackupMode)
	d.Set("backup_size", data.BackupSize)
	d.Set("backup_id", data.BackupId)
	d.Set("slave_status", data.SlaveStatus)
	d.Set("host_instance_id", data.HostInstanceID)
	d.Set("backup_db_names", data.BackupDBNames)
	d.Set("store_status", data.StoreStatus)
	d.Set("db_instance_id", data.DBInstanceId)
	d.Set("backup_download_url", data.BackupDownloadURL)
	d.Set("backup_end_time", data.BackupEndTime)
	d.Set("backup_start_time", data.BackupStartTime)
	d.Set("backup_type", data.BackupType)
	d.Set("meta_status", data.MetaStatus)
	d.Set("backup_scale", data.BackupScale)
	d.Set("backup_status", data.BackupStatus)
	d.Set("backup_location", data.BackupLocation)
	return nil
}

func resourceAlibabacloudStackPolardbBackupDelete(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	// api: polardb - 2024-01-30 - DeleteBackup
	request := client.NewCommonRequest("POST", "polardb", "2024-01-30", "DeleteBackup", "")

	//调用request_params_handler
	param := strings.Split(d.Id(), ":")

	request.QueryParams["DBInstanceId"] = param[0]
	request.QueryParams["BackupId"] = param[1]

	bresponse, err := client.ProcessCommonRequest(request)
	addDebug(request.GetActionName(), bresponse, request, request.QueryParams)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_polar_db_backup", "DeleteBackup", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}

	return nil
}

type PolardbCreatebackupResponse struct {
	RequestId   string `json:"RequestId"`
	BackupJobId string `json:"BackupJobId"`
}
