package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product polardb Resouce Account
import (
	"fmt"
	"strings"

	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/errmsgs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
)

func resourceAlibabacloudStackPolardbAccountDatabaseBinding() *schema.Resource {
	resource := &schema.Resource{
		Schema: map[string]*schema.Schema{
			"account_name": {
				Type:     schema.TypeString,
				Required: true,
			},
			"db_instance_id": {
				Type:     schema.TypeString,
				Required: true,
			},

			"database_privileges": {
				Type:     schema.TypeSet,
				Optional: true,

				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{

						"privilege": {
							Type:         schema.TypeString,
							Optional:     true,
							ValidateFunc: validation.StringInSlice([]string{"ReadWrite", "ReadOnly", "DDLOnly", "DMLOnly"}, false),
						},
						"db_name": {
							Type:     schema.TypeString,
							Optional: true,
						},
					},
				},
			},
		},
	}
	setResourceFunc(resource, resourceAlibabacloudStackPolardbAccountDatabaseBindingCreate,
		resourceAlibabacloudStackPolardbAccountDatabaseBindingRead, resourceAlibabacloudStackPolardbAccountDatabaseBindingUpdate, resourceAlibabacloudStackPolardbAccountDatabaseBindingDelete)
	return resource
}

func resourceAlibabacloudStackPolardbAccountDatabaseBindingCreate(d *schema.ResourceData, meta interface{}) error {
	accountName := d.Get("account_name").(string)

	dbInstanceId := d.Get("db_instance_id").(string)

	d.SetId(fmt.Sprintf("%s:%s", dbInstanceId, accountName))
	return nil

}

func resourceAlibabacloudStackPolardbAccountDatabaseBindingUpdate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	var dbInstanceId, accountName string
	if parts, err := ParseResourceId(d.Id(), 2); err != nil {
		return err
	} else {
		dbInstanceId = parts[0]
		accountName = parts[1]
	}
	removePrivileges := make([]interface{}, 0)
	addPrivileges := make([]interface{}, 0)
	if d.HasChanges("database_privileges") {
		if d.IsNewResource() {
			addPrivileges = d.Get("database_privileges").(*schema.Set).List()
		} else {
			o, n := d.GetChange("database_privileges")
			old := o.(*schema.Set)
			new := n.(*schema.Set)
			removePrivileges = old.Difference(new).List()
			addPrivileges = new.Difference(old).List()
		}
		if len(removePrivileges) > 0 {
			request := client.NewCommonRequest("POST", "polardb", "2024-01-30", "RevokeAccountPrivilege", "")
			request.QueryParams["AccountName"] = accountName
			request.QueryParams["DBInstanceId"] = dbInstanceId
			removeDbnames := make([]string, 0)
			for _, dbprivilege := range removePrivileges {
				removeDbnames = append(removeDbnames, dbprivilege.(map[string]interface{})["db_name"].(string))
			}
			request.QueryParams["AccountPrivilege"] = fmt.Sprintf("%s,%s", strings.Repeat("REVOKE,", len(removeDbnames)-1), "REVOKE")
			request.QueryParams["DBName"] = strings.Join(removeDbnames, ",")
			bresponse, err := client.ProcessCommonRequest(request)
			addDebug(request.GetActionName(), bresponse, request, request.QueryParams)
			if err != nil {
				if bresponse == nil {
					return errmsgs.WrapErrorf(err, "Process Common Request Failed")
				}
				errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
				return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,
					"alibabacloudstack_polardb_account_database_binding", "RevokeAccountPrivilege", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
			}
		}
		if len(addPrivileges) > 0 {
			request := client.NewCommonRequest("POST", "polardb", "2024-01-30", "GrantAccountPrivilege", "")
			request.QueryParams["AccountName"] = accountName
			request.QueryParams["DBInstanceId"] = dbInstanceId
			privileges := make([]string, 0)
			dbNames := make([]string, 0)
			for _, dbprivilege := range addPrivileges {
				privileges = append(privileges, dbprivilege.(map[string]interface{})["privilege"].(string))
				dbNames = append(dbNames, dbprivilege.(map[string]interface{})["db_name"].(string))
			}
			request.QueryParams["AccountPrivilege"] = strings.Join(privileges, ",")
			request.QueryParams["DBName"] = strings.Join(dbNames, ",")
			bresponse, err := client.ProcessCommonRequest(request)
			addDebug(request.GetActionName(), bresponse, request, request.QueryParams)
			if err != nil {
				if bresponse == nil {
					return errmsgs.WrapErrorf(err, "Process Common Request Failed")
				}
				errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
				return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,
					"alibabacloudstack_polardb_account_database_binding", "GrantAccountPrivilege", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
			}
		}
	}
	return nil
}

func resourceAlibabacloudStackPolardbAccountDatabaseBindingRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	polardbservice := PolardbService{client}
	response, err := polardbservice.DescribeDBAccount(d.Id())
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg, "alibabacloudstack_polardb_account_database_binding", errmsgs.AlibabacloudStackSdkGoERROR)
	}
	data := response.Accounts.DBInstanceAccount[0]

	d.Set("account_name", data.AccountName)

	d.Set("db_instance_id", data.DBInstanceId)

	var databasePrivileges []map[string]interface{}
	for _, dbPrivilege := range data.DatabasePrivileges.DatabasePrivilege {
		privilege := map[string]interface{}{
			"privilege": dbPrivilege.AccountPrivilege,
			"db_name":   dbPrivilege.DBName,
		}
		databasePrivileges = append(databasePrivileges, privilege)
	}
	d.Set("database_privileges", databasePrivileges)

	return nil
}

func resourceAlibabacloudStackPolardbAccountDatabaseBindingDelete(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	var dbInstanceId, accountName string
	if parts, err := ParseResourceId(d.Id(), 2); err != nil {
		return err
	} else {
		dbInstanceId = parts[0]
		accountName = parts[1]
	}
	databasePrivileges := d.Get("database_privileges").(*schema.Set).List()
	removeDbnames := make([]string, 0)
	for _, dbPrivilege := range databasePrivileges {
		removeDbnames = append(removeDbnames, dbPrivilege.(map[string]interface{})["db_name"].(string))
	}
	request := client.NewCommonRequest("POST", "polardb", "2024-01-30", "RevokeAccountPrivilege", "")
	request.QueryParams["AccountName"] = accountName
	request.QueryParams["DBInstanceId"] = dbInstanceId
	request.QueryParams["AccountPrivilege"] = fmt.Sprintf("%s,%s", strings.Repeat("REVOKE,", len(removeDbnames)-1), "REVOKE")
	request.QueryParams["DBName"] = strings.Join(removeDbnames, ",")
	bresponse, err := client.ProcessCommonRequest(request)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,
			"alibabacloudstack_polardb_account_database_binding", "RevokeAccountPrivilege", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}
	return nil
}
