package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product DRDS Resouce Database
import (
	"context"
	"encoding/json"
	"fmt"
	"reflect"
	"regexp"
	"sort"
	"strings"
	"time"

	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/errmsgs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
)

func resourceAlibabacloudStackDrdsDatabase() *schema.Resource {
	resource := &schema.Resource{
		Schema: map[string]*schema.Schema{

			"instance_id": {
				Type:     schema.TypeString,
				Required: true,
			},

			"drds_database_name": {
				Type:         schema.TypeString,
				Required:     true,
				ValidateFunc: validation.StringMatch(regexp.MustCompile("^[a-z][a-z0-9_]{0,23}$"), "The database name must be 1 to 24 characters in length and can contain lowercase letters, digits, and underscores (_). It must start with a letter."),
			},

			"split_mode": {
				Type:     schema.TypeString,
				Optional: true,
				Default:  "HORIZONTAL",
			},

			"encode": {
				Type:     schema.TypeString,
				Optional: true,
				Default:  "utf8",
			},

			"create_time": {
				Type:     schema.TypeString,
				Computed: true,
			},

			"password": {
				Type:         schema.TypeString,
				Sensitive:    true,
				Required:     true,
				ValidateFunc: validation.StringLenBetween(8, 30),
			},

			"rds_instance_ids": {
				Type:     schema.TypeList,
				MinItems: 1,
				Required: true,
				Elem:     &schema.Schema{Type: schema.TypeString},
				DiffSuppressFunc: func(k, oldValue, newValue string, d *schema.ResourceData) bool {
					if k == "rds_instance_ids.#" {
						return oldValue == newValue
					}
					var oldValues, newValues []string
					old, new := d.GetChange("rds_instance_ids")
					for _, v := range old.([]interface{}) {
						oldValues = append(oldValues, v.(string))
					}
					sort.Strings(oldValues)
					for _, v := range new.([]interface{}) {
						newValues = append(newValues, v.(string))
					}
					sort.Strings(newValues)
					return reflect.DeepEqual(oldValues, newValues)
				},
			},

			"ip_white_list": {
				Type:     schema.TypeMap,
				Optional: true,
				Elem:     &schema.Schema{Type: schema.TypeString},
				DiffSuppressFunc: func(k, oldValue, newValue string, d *schema.ResourceData) bool {
					if k == "ip_white_list.%" {
						return true
					}
					if k == "ip_white_list.default" && oldValue == "*.*.*.*" && newValue == "" {
						return true
					}
					var oldValues, newValues []string
					for _, v := range strings.Split(oldValue, ",") {
						oldValues = append(oldValues, strings.Trim(v, " "))
					}
					sort.Strings(oldValues)
					for _, v := range strings.Split(newValue, ",") {
						newValues = append(newValues, strings.Trim(v, " "))
					}
					sort.Strings(newValues)
					return strings.Join(oldValues, ",") == strings.Join(newValues, ",")
				},
			},

			"status": {
				Type:     schema.TypeString,
				Computed: true,
			},

			"storage_type": {
				Type:     schema.TypeString,
				Optional: true,
				Default:  "RDS",
			},
		},
		CustomizeDiff: func(_ context.Context, d *schema.ResourceDiff, _ interface{}) error {
			if d.HasChange("ip_white_list") {
				oldVal, newVal := d.GetChange("ip_white_list")
				oldMap, _ := oldVal.(map[string]interface{})
				newMap, _ := newVal.(map[string]interface{})

				for oldKey := range oldMap {
					if _, exists := newMap[oldKey]; !exists {
						if oldKey == "default" && oldMap[oldKey].(string) == "*.*.*.*" {
							continue
						}
						return fmt.Errorf("ip_white_list key %q cannot be removed. Keys can only be added, not deleted.", oldKey)
					}
				}
			}
			if d.HasChange("rds_instance_ids") {
				oldVal, newVal := d.GetChange("rds_instance_ids")
				newMap := map[string]interface{}{}
				for _, key := range newVal.([]interface{}) {
					newMap[key.(string)] = ""
				}
				for _, oldKey := range oldVal.([]interface{}) {
					if _, exists := newMap[oldKey.(string)]; !exists {
						return fmt.Errorf("rds_instance_ids key %q cannot be removed. instance can only be added, not deleted.", oldKey)
					}
				}
			}

			return nil
		},
	}
	setResourceFunc(resource, resourceAlibabacloudStackDrdsDatabaseCreate, resourceAlibabacloudStackDrdsDatabaseRead, resourceAlibabacloudStackDrdsDatabaseUpdate, resourceAlibabacloudStackDrdsDatabaseDelete)
	return resource
}

func resourceAlibabacloudStackDrdsDatabaseCreate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	drdsService := DrdsService{client}

	// api: Drds - 2019-01-23 - CreateDrdsDB
	reqQuery := map[string]interface{}{
		"DbName":               d.Get("drds_database_name").(string),
		"DrdsInstanceId":       d.Get("instance_id").(string),
		"Encode":               d.Get("encode").(string),
		"Password":             d.Get("password").(string),
		"DbInstType":           d.Get("storage_type").(string),
		"DbInstanceIsCreating": false,
		"RdsInstance":          d.Get("rds_instance_ids").([]interface{}),
		"Type":                 d.Get("split_mode").(string),
	}
	request, err := client.DoTeaRequest("POST", "Drds", "2019-01-23", "CreateDrdsDB", "", nil, reqQuery, nil)

	if err != nil {
		errmsg := ""
		if request != nil {
			errmsg = request["Message"].(string)
		}
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_drds_database", "CreateDrdsDB", errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}

	drds_database_name := d.Get("drds_database_name").(string)

	instance_id := d.Get("instance_id").(string)

	d.SetId(fmt.Sprintf("%s:%s", instance_id, drds_database_name))

	stateConf := BuildStateConf([]string{"INIT"}, []string{"NORMAL"}, d.Timeout(schema.TimeoutCreate), 10*time.Second, drdsService.DbStateRefreshFunc(d.Id(), []string{"INIT_FAIL"}))

	if _, err := stateConf.WaitForState(); err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.IdMsg, d.Id())
	}

	return nil

}

func resourceAlibabacloudStackDrdsDatabaseUpdate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	drdsService := DrdsService{client}
	var drdsInstanceId, databaseName string
	if parts, err := ParseResourceId(d.Id(), 2); err != nil {
		return err
	} else {
		drdsInstanceId = parts[0]
		databaseName = parts[1]
	}
	// DrdsDatabaseName

	// InstanceId

	// IpWhiteList

	// api: Drds - 2019-01-23 - ModifyDrdsIpWhiteList
	if d.HasChange("ip_white_list") {
		request := client.NewCommonRequest("POST", "Drds", "2019-01-23", "ModifyDrdsIpWhiteList", "")

		request.QueryParams["DbName"] = databaseName
		request.QueryParams["DrdsInstanceId"] = drdsInstanceId

		newMap := d.Get("ip_white_list").(map[string]interface{})

		for key, value := range newMap {
			if !d.HasChange(fmt.Sprintf("ip_white_list.%s", key)) {
				continue
			}
			request.QueryParams["IpWhiteList"] = value.(string)
			request.QueryParams["GroupName"] = key
			bresponse, err := client.ProcessCommonRequest(request)
			if err != nil {
				if bresponse == nil {
					return errmsgs.WrapErrorf(err, "Process Common Request Failed")
				}
				errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
				return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,
					"alibabacloudstack_drds_database", "ModifyDrdsIpWhiteList", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
			}
		}

	}

	if d.IsNewResource() {
		return nil
	}

	if d.HasChange("password") {
		request := client.NewCommonRequest("POST", "Drds", "2019-01-23", "ChangeAccountPassword", "")

		request.QueryParams["AccountName"] = databaseName
		request.QueryParams["DrdsInstanceId"] = drdsInstanceId

		request.QueryParams["Password"] = d.Get("password").(string)

		bresponse, err := client.ProcessCommonRequest(request)
		if err != nil {
			if bresponse == nil {
				return errmsgs.WrapErrorf(err, "Process Common Request Failed")
			}
			errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
			return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,
				"alibabacloudstack_drds_database", "ModifyDrdsIpWhiteList", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
		}
	}

	if d.HasChange("rds_instance_ids") {
		if task, err := drdsService.DescribeDrdsDbTask(d.Id()); task != nil {
			return fmt.Errorf("There are currently rearrange tasks in expansion, please wait for them to complete.")
		} else if err != nil && !errmsgs.NotFoundError(err) {
			return err
		}

		old, new := d.GetChange("rds_instance_ids")
		oldMap := map[string]interface{}{}
		for _, o := range old.([]interface{}) {
			oldMap[o.(string)] = ""
		}
		newInstance := []string{}
		for _, n := range new.([]interface{}) {
			rdsId := n.(string)
			if _, exist := oldMap[rdsId]; exist {
				continue
			}
			newInstance = append(newInstance, rdsId)
		}
		reqQuery := map[string]interface{}{
			"DbName":               databaseName,
			"DrdsInstanceId":       drdsInstanceId,
			"DbInstanceIsCreating": false,
			"DbInstType":           d.Get("storage_type").(string),
			"InstanceList":         newInstance,
		}
		repsonse, err := client.DoTeaRequest("POST", "Drds", "2019-01-23", "RearrangeDbToInstance", "", nil, reqQuery, nil)
		if err != nil {
			return err
		}
		transferTaskInfos := []map[string]interface{}{}
		for _, d := range repsonse["Data"].(map[string]interface{})["data"].([]interface{}) {
			rearrangeInfo := d.(map[string]interface{})
			transferTask := map[string]interface{}{
				"SrcInstanceName": rearrangeInfo["SrcInstance"].(string),
				"DstInstanceName": rearrangeInfo["DstInstance"].(string),
				"DbName":          rearrangeInfo["SrcDbName"].(string),
			}
			transferTaskInfos = append(transferTaskInfos, transferTask)
		}

		reqQuery = map[string]interface{}{
			"DbName":               databaseName,
			"DrdsInstanceId":       drdsInstanceId,
			"DbInstanceIsCreating": false,
			"DbInstType":           d.Get("storage_type").(string),
			"TransferTaskInfos":    transferTaskInfos,
			"TaskName":             "terraform_auto",
			"TaskDesc":             "alibabacloudstack Automated ",
		}
		repsonse, err = client.DoTeaRequest("POST", "Drds", "2019-01-23", "SubmitSmoothExpandTask", "", nil, reqQuery, nil)
		if err != nil {
			return err
		}

		stateConf := BuildStateConf([]string{"Running"}, []string{"Success"}, 60*time.Minute, 10*time.Second, drdsService.DbTaskRefreshFunc(d.Id(), []string{"Error"}))

		if _, err := stateConf.WaitForState(); err != nil {
			return errmsgs.WrapErrorf(err, errmsgs.IdMsg, d.Id())
		}

		task, err := drdsService.DescribeDrdsDbTask(d.Id())
		if err != nil {
			return err
		}

		var targetId int
		parentJobId := task["ParentJobId"].(string)
		if v, err := task["TargetId"].(json.Number).Int64(); err != nil {
			return err
		} else {
			targetId = int(v)
		}

		reqQuery = map[string]interface{}{
			"DbName":         databaseName,
			"DrdsInstanceId": drdsInstanceId,
			"TaskId":         targetId,
			"JobId":          targetId,
			"ParentJobId":    parentJobId,
			"ExpandType":     "smooth_expand",
			"IsRetry":        false,
		}
		repsonse, err = client.DoTeaRequest("POST", "Drds", "2019-01-23", "SubmitSwitchTask", "", nil, reqQuery, nil)
		if err != nil {
			return err
		}
		stateConf = BuildStateConf([]string{"Running"}, []string{"Success"}, 60*time.Minute, 10*time.Second, drdsService.DbTaskRefreshFunc(d.Id(), []string{"Error"}))

		if _, err := stateConf.WaitForState(); err != nil {
			return errmsgs.WrapErrorf(err, errmsgs.IdMsg, d.Id())
		}

		task, err = drdsService.DescribeDrdsDbTask(d.Id())
		if err != nil {
			return err
		}

		if v, err := task["TargetId"].(json.Number).Int64(); err != nil {
			return err
		} else {
			targetId = int(v)
		}

		reqQuery = map[string]interface{}{
			"DbName":         databaseName,
			"DrdsInstanceId": drdsInstanceId,
			"TaskId":         targetId,
			"JobId":          targetId,
			"ParentJobId":    parentJobId,
			"ExpandType":     "smooth_expand",
			"IsRetry":        false,
		}
		repsonse, err = client.DoTeaRequest("POST", "Drds", "2019-01-23", "SubmitCleanTask", "", nil, reqQuery, nil)
		if err != nil {
			return err
		}
		stateConf = BuildStateConf([]string{"Running"}, []string{}, 60*time.Minute, 10*time.Second, drdsService.DbTaskRefreshFunc(d.Id(), []string{"Error"}))

		if _, err := stateConf.WaitForState(); err != nil {
			return errmsgs.WrapErrorf(err, errmsgs.IdMsg, d.Id())
		}
	}

	return nil
}

func resourceAlibabacloudStackDrdsDatabaseRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	drdsdatabaseservice := DrdsService{client}
	response, err := drdsdatabaseservice.DescribeDrdsDatabase(d.Id())
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg, "alibabacloudstack_drds_database", errmsgs.AlibabacloudStackSdkGoERROR)
	}
	data := response.Data

	sec := data.CreateTime / 1000
	nsec := (data.CreateTime % 1000) * int64(time.Millisecond)
	createTime := time.Unix(sec, nsec).UTC() // Key change: directly convert to UTC
	d.Set("create_time", createTime.Format("2006-01-02T15:04:05-07:00"))

	d.Set("drds_database_name", data.DbName)

	d.Set("split_mode", data.Mode)

	d.Set("status", data.Status)

	d.Set("storage_type", data.DbInstType)

	var drdsInstanceId, databaseName string
	if parts, err := ParseResourceId(d.Id(), 2); err != nil {
		return err
	} else {
		drdsInstanceId = parts[0]
		databaseName = parts[1]
		d.Set("instance_id", drdsInstanceId)
	}
	reqQuery := map[string]interface{}{
		"DbName":         databaseName,
		"DrdsInstanceId": drdsInstanceId,
		"PageSize":       100,
	}
	repsonse, err := client.DoTeaRequest("GET", "Drds", "2019-01-23", "DescribeDrdsDBIpWhiteList", "", nil, reqQuery, nil)
	if err != nil {
		return err
	}
	ipWhiteList := map[string]string{}
	for _, ips := range repsonse["IpWhiteList"].(map[string]interface{})["Ip"].([]interface{}) {
		parts := strings.Split(ips.(string), ":")
		ipWhiteList[parts[0]] = parts[1]
	}
	d.Set("ip_white_list", ipWhiteList)

	repsonse, err = client.DoTeaRequest("GET", "Drds", "2019-01-23", "DescribeDrdsDbInstances", "", nil, reqQuery, nil)
	if err != nil {
		return err
	}
	rdsInstanceIds := []string{}
	for _, d := range repsonse["DbInstances"].(map[string]interface{})["DbInstance"].([]interface{}) {
		dbInstance := d.(map[string]interface{})
		rdsInstanceIds = append(rdsInstanceIds, dbInstance["DBInstanceId"].(string))
	}
	d.Set("rds_instance_ids", rdsInstanceIds)

	return nil
}

func resourceAlibabacloudStackDrdsDatabaseDelete(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	drdsService := DrdsService{client}
	// api: Drds - 2019-01-23 - RemoveDrdsDb
	request := client.NewCommonRequest("POST", "Drds", "2019-01-23", "RemoveDrdsDb", "")

	// Call request_params_handler

	if parts, err := ParseResourceId(d.Id(), 2); err != nil {
		return err
	} else {
		request.QueryParams["DrdsInstanceId"] = parts[0]
		request.QueryParams["DbName"] = parts[1]
	}

	bresponse, err := client.ProcessCommonRequest(request)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_drds_database", "RemoveDrdsDb", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}
	stateConf := BuildStateConf([]string{"DELETE", "NORMAL"}, []string{}, d.Timeout(schema.TimeoutCreate), 10*time.Second, drdsService.DbStateRefreshFunc(d.Id(), []string{"Error"}))

	if _, err := stateConf.WaitForState(); err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.IdMsg, d.Id())
	}
	return nil
}

type DrdsCreatedrdsdbResponse struct {
	RequestId string `json:"RequestId"`
	Success   bool   `json:"Success"`
}

type DrdsModifydrdsipwhitelistResponse struct {
	RequestId string `json:"RequestId"`
	Success   bool   `json:"Success"`
}

type DrdsRemovedrdsdbResponse struct {
	RequestId string `json:"RequestId"`
	Success   bool   `json:"Success"`
}
