package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product ExpressConnect Resouce BgpNetwork
import (
	"fmt"
	"log"
	"regexp"
	"strings"
	"strconv"
	"time"
	"encoding/json"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/auth/credentials"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
	"github.com/aliyun/alibaba-cloud-sdk-go/services/ecs"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/errmsgs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
    "github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
)




func resourceAlibabacloudStackExpressconnectBgpnetwork() *schema.Resource {
	resource := &schema.Resource{
		Schema: map[string]*schema.Schema{
            
			
			
				
					
						"dst_cidr_block": {
	Type: schema.TypeString,
	Required: true,


},
					
				
			
				
			
				
			
				
					
						"record_total": {
	Type: schema.TypeInt,
    Optional: true,
	Computed: true,


},
					
				
			
				
					
						"region_id": {
	Type: schema.TypeString,
	Required: true,


},
					
				
			
				
					
						"router_id": {
	Type: schema.TypeString,
	Required: true,


},
					
				
			
				
					
						"status": {
	Type: schema.TypeString,
    Optional: true,
	Computed: true,


},
					
				
			
				
					
						"vpc_id": {
	Type: schema.TypeString,
    Optional: true,


},
					
				
			
        },
	}
	setResourceFunc(resource, resourceAlibabacloudStackExpressconnectBgpnetworkCreate,
		resourceAlibabacloudStackExpressconnectBgpnetworkRead,
		resourceAlibabacloudStackExpressconnectBgpnetworkUpdate,
		resourceAlibabacloudStackExpressconnectBgpnetworkDelete,)
	return resource
}

func resourceAlibabacloudStackExpressconnectBgpnetworkCreate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	
	
		
		// api: Vpc - 2016-04-28 - AddBgpNetwork
        request := client.NewCommonRequest("POST", "Vpc", "2016-04-28", "AddBgpNetwork", "")
	    VpcAddbgpnetworkResponseObj := VpcAddbgpnetworkResponse{}

		
		
			
			
				//调用request_params_handler
    
        
        
    
        
        
                request.QueryParams["DstCidrBlock"] = d.Get("dst_cidr_block").(string)
        
    
        
    
        
        
    
        
        
                request.QueryParams["RegionId"] = d.Get("region_id").(string)
        
    
        
    
        
        
    
        
        
                request.QueryParams["RouterId"] = d.Get("router_id").(string)
        
    
        
    
        
        
    
        
        
            if v, ok := d.GetOk("vpc_id"); ok{
                request.QueryParams["VpcId"] = v.(string)
            }
        
    
        
    
			
		


        bresponse, err :=client.ProcessCommonRequest(request)
        if err != nil {
            if bresponse == nil {
                return errmsgs.WrapErrorf(err, "Process Common Request Failed")
            }
            errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
            return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,  "alibabacloudstack_express_connect_bgp_network", "AddBgpNetwork", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
        }

		
	

	
			dst_cidr_block := d.Get("dst_cidr_block").(string)
	
			router_id := d.Get("router_id").(string)
	

	d.SetId(fmt.Sprintf("%s", dst_cidr_block + "_" + router_id))
    return nil

}

func resourceAlibabacloudStackExpressconnectBgpnetworkUpdate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	
    return nil
}


func resourceAlibabacloudStackExpressconnectBgpnetworkRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	express_connectbgp_networkservice := 
ExpressconnectService{client}
	response, err := express_connectbgp_networkservice.DoVpcDescribebgpnetworksRequest(d, client)
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg, "alibabacloudstack_expressconnect_bgpnetwork", errmsgs.AlibabacloudStackSdkGoERROR)
	}
	data := response.BgpNetworks.BgpNetwork[0]
	d.Set("dst_cidr_block", data.DstCidrBlock)
	
	d.Set("page_number", data)
	
	d.Set("page_size", data)
	
	d.Set("router_id", data.RouterId)
	
	d.Set("status", data.Status)
	
	d.Set("vpc_id", data.VpcId)
	
    return nil
}

func resourceAlibabacloudStackExpressconnectBgpnetworkDelete(d *schema.ResourceData, meta interface{}) error {
		client := meta.(*connectivity.AlibabacloudStackClient)
		// api: Vpc - 2016-04-28 - DeleteBgpNetwork
		request := client.NewCommonRequest("POST", "Vpc", "2016-04-28", "DeleteBgpNetwork", "")
		VpcDeletebgpnetworkResponseObj := VpcDeletebgpnetworkResponse{}

		
		
			
			
				//调用request_params_handler
    
        
        
    
        
        
                request.QueryParams["DstCidrBlock"] = d.Get("dst_cidr_block").(string)
        
    
        
    
        
        
    
        
        
                request.QueryParams["RegionId"] = d.Get("region_id").(string)
        
    
        
    
        
        
    
        
        
                request.QueryParams["RouterId"] = d.Get("router_id").(string)
        
    
        
    
			
		

		bresponse, err :=client.ProcessCommonRequest(request)
		if err != nil {
			if bresponse == nil {
				return errmsgs.WrapErrorf(err, "Process Common Request Failed")
			}
			errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
			return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,  "alibabacloudstack_express_connect_bgp_network", "DeleteBgpNetwork", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
		}

		
	
	return nil
}

type VpcAddbgpnetworkResponse struct {RequestId string `json:"RequestId"`
}




type VpcDeletebgpnetworkResponse struct {RequestId string `json:"RequestId"`
}

