package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product CEN Resouce CenInstance
import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/errmsgs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func resourceAlibabacloudStackCenTransitRouterRouterTable() *schema.Resource {
	resource := &schema.Resource{
		Schema: map[string]*schema.Schema{
			"transit_router_id": {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: "The ID of the transit router.",
			},
			"transit_router_route_table_name": {
				Type:        schema.TypeString,
				Optional:    true,
				Computed:    true,
				Description: "The name of the route table.",
			},
			"transit_router_route_table_description": {
				Type:        schema.TypeString,
				Optional:    true,
				Computed:    true,
				Description: "The description of the route table.",
			},
			"create_time": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The creation time of the route table.",
			},
			"transit_router_route_table_id": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The ID of the transit router route table.",
			},
			"transit_router_route_table_type": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The type of the transit router route table.",
			},
			"status": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The status of the transit router route table.",
			},
			"tags": {
				Type:     schema.TypeSet,
				Optional: true,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"tag_key": {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "The key of the tag.",
						},
						"tag_value": {
							Type:        schema.TypeString,
							Optional:    true,
							Description: "The value of the tag.",
						},
					},
				},
				Description: "The tags of the transit router route table.",
			},
		},
	}
	setResourceFunc(resource, resourceAlibabacloudStackCenTransitRouterRouterTableCreate,
		resourceAlibabacloudStackCenTransitRouterRouterTableRead,
		resourceAlibabacloudStackCenTransitRouterRouterTableUpdate,
		resourceAlibabacloudStackCenTransitRouterRouterTableDelete)
	return resource
}

func resourceAlibabacloudStackCenTransitRouterRouterTableCreate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	cencen_instanceservice := CenService{client}
	// api: Cbn - 2017-09-12 - CreateCen
	request := client.NewCommonRequest("POST", "Cbn", "2017-09-12", "CreateTransitRouterRouteTable", "")
	CbnCreateTransitRouterRouterTableResponseObj := CbnCreateTransitRouterRouterTableResponse{}
	request.QueryParams["TransitRouterId"] = d.Get("transit_router_id").(string)
	if v, ok := d.GetOk("transit_router_route_table_name"); ok {
		request.QueryParams["TransitRouterRouteTableName"] = v.(string)
	}
	if v, ok := d.GetOk("transit_router_route_table_description"); ok {
		request.QueryParams["TransitRouterRouteTableDescription"] = v.(string)
	}
	bresponse, err := client.ProcessCommonRequest(request)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_cen_transit_router_route_table", "CreateTransitRouterRouteTable", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}

	err = json.Unmarshal(bresponse.GetHttpContentBytes(), &CbnCreateTransitRouterRouterTableResponseObj)
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
			"alibabacloudstack_cen_cen_instance", "CreateCen", errmsgs.AlibabacloudStackSdkGoERROR)
	}

	route_table_id := CbnCreateTransitRouterRouterTableResponseObj.TransitRouterRouteTableId

	d.SetId(fmt.Sprintf("%s:%s", d.Get("transit_router_id").(string), route_table_id))
	err = cencen_instanceservice.WaitForTransitRouterTable(d.Id(), Active, 120)
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,
			"alibabacloudstack_cen_transit_router_route_table", "CreateTransitRouterRouteTable", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, err)

	}
	return nil
}

func resourceAlibabacloudStackCenTransitRouterRouterTableUpdate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	// api: Cbn - 2017-09-12 - ModifyCenAttribute
	if d.HasChanges("transit_router_route_table_name", "transit_router_route_table_description") {
		request := client.NewCommonRequest("POST", "Cbn", "2017-09-12", "UpdateTransitRouterRouteTable", "")
		// CbnModifycenattributeResponseObj := CbnModifycenattributeResponse{}

		if v, ok := d.GetOk("transit_router_route_table_name"); ok {
			request.QueryParams["TransitRouterRouteTableName"] = v.(string)
		}
		if v, ok := d.GetOk("transit_router_route_table_description"); ok {
			request.QueryParams["TransitRouterRouteTableDescription"] = v.(string)
		}
		parts := strings.Split(d.Id(), ":")
		route_table_id := parts[1]
		request.QueryParams["TransitRouterRouteTableId"] = route_table_id
		bresponse, err := client.ProcessCommonRequest(request)
		addDebug(request.GetActionName(), bresponse, request, request.QueryParams)
		if err != nil {
			if bresponse == nil {
				return errmsgs.WrapErrorf(err, "Process Common Request Failed")
			}
			errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
			return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,
				"alibabacloudstack_cen_transit_router_route_table", "UpdateTransitRouterRouteTable", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
		}
	}
	return nil
}

func resourceAlibabacloudStackCenTransitRouterRouterTableRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	cencen_instanceservice := CenService{client}
	response, err := cencen_instanceservice.DoCbnDescribeTransitRouterRouteTablesRequest(d.Id())
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg, "alibabacloudstack_cen_transit_router_route_table", errmsgs.AlibabacloudStackSdkGoERROR)
	}
	parts := strings.Split(d.Id(), ":")
	route_table_id := parts[1]
	for _, v := range response.TransitRouterRouteTables {
		if v.TransitRouterRouteTableId == route_table_id {
			d.Set("create_time", v.CreateTime)
			d.Set("transit_router_route_table_name", v.TransitRouterRouteTableName)
			d.Set("transit_router_route_table_description", v.TransitRouterRouteTableDescription)
			d.Set("transit_router_route_table_id", v.TransitRouterRouteTableId)
			d.Set("transit_router_route_table_type", v.TransitRouterRouteTableType)
			d.Set("status", v.TransitRouterRouteTableStatus)
			break
		}
	}

	return nil
}

func resourceAlibabacloudStackCenTransitRouterRouterTableDelete(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	cencen_instanceservice := CenService{client}
	// api: Cbn - 2017-09-12 - DeleteCen
	request := client.NewCommonRequest("POST", "Cbn", "2017-09-12", "DeleteTransitRouterRouteTable", "")
	// CbnDeletecenResponseObj := CbnDeletecenResponse{}
	parts := strings.Split(d.Id(), ":")
	route_table_id := parts[1]
	request.QueryParams["TransitRouterRouteTableId"] = route_table_id

	bresponse, err := client.ProcessCommonRequest(request)
	addDebug(request.GetActionName(), bresponse, request, request.QueryParams)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_cen_transit_router_route_table", "DeleteTransitRouterRouteTable", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}

	// 	for i in ran
	// 	response, err := cencen_instanceservice.DoCbnDescribeTransitRouterRouteTablesRequest(d.Id())
	// 	for _, v := range response.TransitRouterRouteTables {
	// 		if v.TransitRouterRouteTableId == route_table_id {
	flag := true
	for i := 0; i < 10; i++ {
		response, err := cencen_instanceservice.DoCbnDescribeTransitRouterRouteTablesRequest(d.Id())
		if err != nil {
			return errmsgs.WrapErrorf(err, "DoCbnDescribeTransitRouterRouteTablesRequest")
		}
		for _, v := range response.TransitRouterRouteTables {
			if v.TransitRouterRouteTableId == route_table_id {
				flag = false
				break
			}
		}
		if flag == false {
			time.Sleep(time.Duration(2) * time.Second)
		} else {
			break
		}
	}

	return nil
}

type CbnCreateTransitRouterRouterTableResponse struct {
	TransitRouterRouteTableId string `json:"TransitRouterRouteTableId"`
	RequestId                 string `json:"RequestId"`
}
