package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product ECS Resouce Invocation
import (
	"encoding/json"
	"fmt"

	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/errmsgs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func resourceAlibabacloudStackEcsInvocation() *schema.Resource {
	resource := &schema.Resource{
		Schema: map[string]*schema.Schema{

			"command_id": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
			},

			"create_time": {
				Type:     schema.TypeString,
				Computed: true,
			},

			"instance_ids": {
				Type:     schema.TypeList,
				Elem:     &schema.Schema{Type: schema.TypeString},
				Required: true,
				ForceNew: true,
			},

			"invocation_id": {
				Type:     schema.TypeString,
				Computed: true,
			},

			"repeat_mode": {
				Type:     schema.TypeString,
				Optional: true,
				ForceNew: true,
			},

			"tags": tagsSchema(),

			"username": {
				Type:     schema.TypeString,
				Optional: true,
				ForceNew: true,
			},
		},
	}
	setResourceFunc(resource, resourceAlibabacloudStackEcsInvocationCreate,
		resourceAlibabacloudStackEcsInvocationRead,
		resourceAlibabacloudStackEcsInvocationUpdate,
		resourceAlibabacloudStackEcsInvocationDelete)
	return resource
}

func resourceAlibabacloudStackEcsInvocationCreate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)

	// api: Ecs - 2014-05-26 - InvokeCommand
	request := client.NewCommonRequest("POST", "Ecs", "2014-05-26", "InvokeCommand", "")

	//调用request_params_handler

	if v, ok := d.GetOk("command_id"); ok {
		request.QueryParams["CommandId"] = v.(string)
	} else {
		return fmt.Errorf("CommandId is required")
	}

	if v, ok := d.GetOk("repeat_mode"); ok {
		request.QueryParams["RepeatMode"] = v.(string)
	}

	if v, ok := d.GetOk("username"); ok {
		request.QueryParams["Username"] = v.(string)
	}

	instanceIds := d.Get("instance_ids").([]interface{})
	for i, v := range instanceIds {
		key := fmt.Sprintf("InstanceId.%d", i+1)
		request.QueryParams[key] = v.(string)
	}

	bresponse, err := client.ProcessCommonRequest(request)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_ecs_invocation", "InvokeCommand", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}

	EcsinvokeResponse := EcsInvokecommandResponse{}
	err = json.Unmarshal(bresponse.GetHttpContentBytes(), &EcsinvokeResponse)
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
			"alibabacloudstack_ebs_invocation", "InvokeCommand", errmsgs.AlibabacloudStackSdkGoERROR)
	}

	ecsinvake_id := EcsinvokeResponse.InvokeId

	d.SetId(ecsinvake_id)

	return nil
}

func resourceAlibabacloudStackEcsInvocationUpdate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)

	// InvocationId

	// RegionId

	// ResourceType

	// Tags

	// api: Ecs - 2014-05-26 - TagResources
	err := setTags(client, TagResourceEcsInvocation, d)
	if err != nil {
		return errmsgs.WrapError(err)
	}

	// 	bresponse, err := client.ProcessCommonRequest(request)
	// 	if err != nil {
	// 		if bresponse == nil {
	// 			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
	// 		}
	// 		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
	// 		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,
	// 			"alibabacloudstack_ecs_invocation", "TagResources", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	// 	}

	// 	err = json.Unmarshal(bresponse.GetHttpContentBytes(), &EcsTagresourcesResponseObj)
	// 	if err != nil {
	// 		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
	// 			"alibabacloudstack_ecs_invocation", "TagResources", errmsgs.AlibabacloudStackSdkGoERROR)
	// 	}

	// }

	// // InvocationId

	// // RegionId

	// // ResourceType

	// // Tags

	// // api: Ecs - 2014-05-26 - UntagResources
	// if d.HasChanges("region_id", "resource_type", "tags") {
	// 	request := client.NewCommonRequest("POST", "Ecs", "2014-05-26", "UntagResources", "")
	// 	EcsUntagresourcesResponseObj := EcsInvokeUntagresourcesResponse{}

	// 	if v, ok := d.GetOk("invocation_id"); ok {
	// 		request.QueryParams["ResourceId[*]"] = v.(string)
	// 	}

	// 	if v, ok := d.GetOk("region_id"); ok {
	// 		request.QueryParams["RegionId"] = v.(string)
	// 	} else {
	// 		return fmt.Errorf("RegionId is required")
	// 	}

	// 	if v, ok := d.GetOk("resource_type"); ok {
	// 		request.QueryParams["ResourceType"] = v.(string)
	// 	} else {
	// 		return fmt.Errorf("ResourceType is required")
	// 	}

	// 	if v, ok := d.GetOk("tags"); ok {
	// 		tagsList := v.([]interface{})
	// 		tagsValues := make([]map[string]interface{}, 0)
	// 		for _, item := range tagsList {
	// 			itemMap := item.(map[string]interface{})
	// 			item_data := make(map[string]interface{})

	// 			if v, ok := itemMap["tag_key"]; ok && v != "" {
	// 				item_data["TagKey[*]"] = v.(string)
	// 			}

	// 			tagsValues = append(tagsValues, item_data)
	// 		}
	// 		data, _ := json.Marshal(tagsValues)
	// 		request.QueryParams["Tags"] = string(data)
	// 	}

	// 	bresponse, err := client.ProcessCommonRequest(request)
	// 	if err != nil {
	// 		if bresponse == nil {
	// 			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
	// 		}
	// 		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
	// 		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,
	// 			"alibabacloudstack_ecs_invocation", "UntagResources", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	// 	}

	// 	err = json.Unmarshal(bresponse.GetHttpContentBytes(), &EcsUntagresourcesResponseObj)
	// 	if err != nil {
	// 		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
	// 			"alibabacloudstack_ecs_invocation", "UntagResources", errmsgs.AlibabacloudStackSdkGoERROR)
	// 	}

	// }

	return nil
}

func resourceAlibabacloudStackEcsInvocationRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	ecsinvocationservice :=
		EcsService{client}
	response, err := ecsinvocationservice.DoEcsDescribeinvocationresultsRequest(d.Id())
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg, "alibabacloudstack_ecs_invocation", errmsgs.AlibabacloudStackSdkGoERROR)
	}
	data := response.Invocation.InvocationResults.InvocationResult[0]
	d.Set("command_id", data.CommandId)

	d.Set("create_time", data.StartTime)

	d.Set("invocation_id", data.InvokeId)

	d.Set("username", data.Username)
	d.Set("instance_ids", []string{data.InstanceId})
	d.Set("tags", ecsinvocationservice.tagsToMap(data.Tags.Tag))

	return nil
}

func resourceAlibabacloudStackEcsInvocationDelete(d *schema.ResourceData, meta interface{}) error {
	return nil
}

type EcsInvokecommandResponse struct {
	InvokeId  string `json:"InvokeId"`
	RequestId string `json:"RequestId"`
}

type EcsInvoketagresourcesResponse struct {
	RequestId string `json:"RequestId"`
}
type EcsInvokeUntagresourcesResponse struct {
	RequestId string `json:"RequestId"`
}
