package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product ExpressConnect Resouce VbrPconnAssociation
import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/errmsgs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func resourceAlibabacloudStackExpressconnectVbrpconnassociation() *schema.Resource {
	resource := &schema.Resource{
		Schema: map[string]*schema.Schema{
			"physical_connection_id": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
			},
			"vbr_id": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
			},
			"vlan_id": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
			},
			"circuit_code": {
				Type:     schema.TypeString,
				Computed: true,
			},
			"local_gateway_ip": {
				Type:     schema.TypeString,
				Optional: true,
				ForceNew: true,
			},
			"peer_gateway_ip": {
				Type:     schema.TypeString,
				Optional: true,
				ForceNew: true,
			},
			"peering_subnet_mask": {
				Type:     schema.TypeString,
				Optional: true,
				ForceNew: true,
			},
			"enable_ipv6": {
				Type:     schema.TypeBool,
				Optional: true,
				Default:  false,
				ForceNew: true,
			},
			"local_ipv6_gateway_ip": {
				Type:         schema.TypeString,
				Optional:     true,
				ForceNew:     true,
				RequiredWith: []string{"peer_ipv6_gateway_ip", "peering_ipv6_subnet_mask"},
			},
			"peer_ipv6_gateway_ip": {
				Type:         schema.TypeString,
				Optional:     true,
				ForceNew:     true,
				RequiredWith: []string{"local_ipv6_gateway_ip", "peering_ipv6_subnet_mask"},
			},
			"peering_ipv6_subnet_mask": {
				Type:         schema.TypeString,
				Optional:     true,
				ForceNew:     true,
				RequiredWith: []string{"local_ipv6_gateway_ip", "peer_ipv6_gateway_ip"},
			},
			"status": {
				Type:     schema.TypeString,
				Computed: true,
			},
		},
	}
	setResourceFunc(resource, resourceAlibabacloudStackExpressconnectVbrpconnassociationCreate,
		resourceAlibabacloudStackExpressconnectVbrpconnassociationRead,
		nil,
		resourceAlibabacloudStackExpressconnectVbrpconnassociationDelete)
	return resource
}

func resourceAlibabacloudStackExpressconnectVbrpconnassociationCreate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)

	// api: Vpc - 2016-04-28 - AssociatePhysicalConnectionToVirtualBorderRouter
	request := client.NewCommonRequest("POST", "Vpc", "2016-04-28", "AssociatePhysicalConnectionToVirtualBorderRouter", "")
	VpcAssociatephysicalconnectiontovirtualborderrouterResponseObj := VpcAssociatephysicalconnectiontovirtualborderrouterResponse{}

	// Call request_params_handler

	if v, ok := d.GetOk("enable_ipv6"); ok && v.(bool) {
		request.QueryParams["EnableIpv6"] = "true"
		if _, ok := d.GetOk("local_ipv6_gateway_ip"); !ok {
			return fmt.Errorf("local_ipv6_gateway_ip is required while enable_ipv6 is true")
		}
		request.QueryParams["LocalIpv6GatewayIp"] = d.Get("local_ipv6_gateway_ip").(string)
		request.QueryParams["PeerIpv6GatewayIp"] = d.Get("peer_ipv6_gateway_ip").(string)
		request.QueryParams["PeeringIpv6SubnetMask"] = d.Get("peering_ipv6_subnet_mask").(string)
	} else {
		request.QueryParams["EnableIpv6"] = "false"
	}
	if v, ok := d.GetOk("local_gateway_ip"); ok {
		request.QueryParams["LocalGatewayIp"] = v.(string)
	}
	if v, ok := d.GetOk("peer_gateway_ip"); ok {
		request.QueryParams["PeerGatewayIp"] = v.(string)
	}
	if v, ok := d.GetOk("peering_subnet_mask"); ok {
		request.QueryParams["PeeringSubnetMask"] = v.(string)
	}
	request.QueryParams["PhysicalConnectionId"] = d.Get("physical_connection_id").(string)
	request.QueryParams["VbrId"] = d.Get("vbr_id").(string)
	request.QueryParams["VlanId"] = d.Get("vlan_id").(string)

	bresponse, err := client.ProcessCommonRequest(request)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_express_connect_vbr_pconn_association", "AssociatePhysicalConnectionToVirtualBorderRouter", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}

	err = json.Unmarshal(bresponse.GetHttpContentBytes(), &VpcAssociatephysicalconnectiontovirtualborderrouterResponseObj)
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
			"alibabacloudstack_express_connect_vbr_pconn_association", "AssociatePhysicalConnectionToVirtualBorderRouter", errmsgs.AlibabacloudStackSdkGoERROR)
	}

	physical_connection_id := d.Get("physical_connection_id").(string)

	vbr_id := d.Get("vbr_id").(string)

	d.SetId(fmt.Sprintf("%s", physical_connection_id+":"+vbr_id))

	expressconnectservice := ExpressconnectService{client}

	stateConf := BuildStateConf([]string{"Creating"}, []string{"Associated"}, d.Timeout(schema.TimeoutCreate), 10*time.Second, expressconnectservice.ExpressconnectVbrPconnAssociationStateRefreshFunc(d.Id(), []string{"Failed"}))

	if _, err := stateConf.WaitForState(); err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.IdMsg, d.Id())
	}
	return nil

}

func resourceAlibabacloudStackExpressconnectVbrpconnassociationUpdate(d *schema.ResourceData, meta interface{}) error {
	//	 Currently not editable
	//		client := meta.(*connectivity.AlibabacloudStackClient)
	//		if d.IsNewResource() {
	//			return nil
	//		}
	//
	//		if d.HasChanges("local_gateway_ip", "peer_gateway_ip", "peering_subnet_mask", "enable_ipv6", "local_ipv6_gateway_ip", "peer_ipv6_gateway_ip", "peering_ipv6_subnet_mask") {
	//			request := client.NewCommonRequest("POST", "Vpc", "2016-04-28", "ModifyVirtualBorderRouterAttribute", "")
	//			if v, ok := d.GetOk("enable_ipv6"); ok && v.(bool) {
	//				request.QueryParams["EnableIpv6"] = "true"
	//				if _, ok := d.GetOk("local_ipv6_gateway_ip"); !ok {
	//					return fmt.Errorf("local_ipv6_gateway_ip is required while enable_ipv6 is true")
	//				}
	//				request.QueryParams["LocalIpv6GatewayIp"] = d.Get("local_ipv6_gateway_ip").(string)
	//				request.QueryParams["PeerIpv6GatewayIp"] = d.Get("peer_ipv6_gateway_ip").(string)
	//				request.QueryParams["PeeringIpv6SubnetMask"] = d.Get("peering_ipv6_subnet_mask").(string)
	//			} else {
	//				request.QueryParams["EnableIpv6"] = "false"
	//			}
	//			if v, ok := d.GetOk("local_gateway_ip"); ok {
	//				request.QueryParams["LocalGatewayIp"] = v.(string)
	//			}
	//			if v, ok := d.GetOk("peer_gateway_ip"); ok {
	//				request.QueryParams["PeerGatewayIp"] = v.(string)
	//			}
	//			if v, ok := d.GetOk("peering_subnet_mask"); ok {
	//				request.QueryParams["PeeringSubnetMask"] = v.(string)
	//			}
	//			request.QueryParams["PhysicalConnectionId"] = d.Get("physical_connection_id").(string)
	//			request.QueryParams["VbrId"] = d.Get("vbr_id").(string)
	//			request.QueryParams["VlanId"] = d.Get("vlan_id").(string)
	//
	//			bresponse, err := client.ProcessCommonRequest(request)
	//			if err != nil {
	//				if bresponse == nil {
	//					return errmsgs.WrapErrorf(err, "Process Common Request Failed")
	//				}
	//				errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
	//				return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_express_connect_vbr_pconn_association", "AssociatePhysicalConnectionToVirtualBorderRouter", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	//			}
	//
	//			expressconnectservice := ExpressconnectService{client}
	//
	//			stateConf := BuildStateConf([]string{"Updating"}, []string{"Associated"}, d.Timeout(schema.TimeoutCreate), 10*time.Second, expressconnectservice.ExpressconnectVbrPconnAssociationStateRefreshFunc(d.Id(), []string{"Failed"}))
	//
	//			if _, err := stateConf.WaitForState(); err != nil {
	//				return errmsgs.WrapErrorf(err, errmsgs.IdMsg, d.Id())
	//			}
	//			return nil
	//		}
			return nil
}

func resourceAlibabacloudStackExpressconnectVbrpconnassociationRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	expressconnectService := ExpressconnectService{client}
	data, err := expressconnectService.DoVpcDescribeVbrpconnassociationRequest(d.Id())
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg, "alibabacloudstack_expressconnect_vbrpconnassociation", errmsgs.AlibabacloudStackSdkGoERROR)
	}

	parts := strings.Split(d.Id(), ":")
	d.Set("physical_connection_id", parts[0])
	d.Set("vbr_id", parts[1])

	d.Set("circuit_code", data.CircuitCode)

	d.Set("enable_ipv6", data.EnableIpv6)

	d.Set("local_gateway_ip", data.LocalGatewayIp)

	d.Set("local_ipv6_gateway_ip", data.LocalIpv6GatewayIp)

	d.Set("peer_gateway_ip", data.PeerGatewayIp)

	d.Set("peer_ipv6_gateway_ip", data.PeerIpv6GatewayIp)

	d.Set("peering_ipv6_subnet_mask", data.PeeringIpv6SubnetMask)

	d.Set("peering_subnet_mask", data.PeeringSubnetMask)

	d.Set("status", data.Status)

	d.Set("vlan_id", data.VlanId)

	return nil
}

func resourceAlibabacloudStackExpressconnectVbrpconnassociationDelete(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	// api: Vpc - 2016-04-28 - UnassociatePhysicalConnectionFromVirtualBorderRouter
	request := client.NewCommonRequest("POST", "Vpc", "2016-04-28", "UnassociatePhysicalConnectionFromVirtualBorderRouter", "")
	VpcUnassociatephysicalconnectionfromvirtualborderrouterResponseObj := VpcUnassociatephysicalconnectionfromvirtualborderrouterResponse{}

	// Call request_params_handler

	request.QueryParams["PhysicalConnectionId"] = d.Get("physical_connection_id").(string)
	request.QueryParams["VbrId"] = d.Get("vbr_id").(string)

	bresponse, err := client.ProcessCommonRequest(request)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_express_connect_vbr_pconn_association", "UnassociatePhysicalConnectionFromVirtualBorderRouter", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}

	err = json.Unmarshal(bresponse.GetHttpContentBytes(), &VpcUnassociatephysicalconnectionfromvirtualborderrouterResponseObj)
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
			"alibabacloudstack_express_connect_vbr_pconn_association", "UnassociatePhysicalConnectionFromVirtualBorderRouter", errmsgs.AlibabacloudStackSdkGoERROR)
	}

	expressconnectservice := ExpressconnectService{client}

	stateConf := BuildStateConf([]string{"UnAssociating"}, []string{}, d.Timeout(schema.TimeoutCreate), 10*time.Second, expressconnectservice.ExpressconnectVbrPconnAssociationStateRefreshFunc(d.Id(), []string{"Failed"}))

	if _, err := stateConf.WaitForState(); err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.IdMsg, d.Id())
	}

	return nil
}

type VpcAssociatephysicalconnectiontovirtualborderrouterResponse struct {
	RequestId string `json:"RequestId"`
}

type VpcUnassociatephysicalconnectionfromvirtualborderrouterResponse struct {
	RequestId string `json:"RequestId"`
}
