package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product ECS Resouce Invocation
import (
	"fmt"
	"log"
	"regexp"
	"strings"
	"strconv"
	"time"
	"encoding/json"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/auth/credentials"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
	"github.com/aliyun/alibaba-cloud-sdk-go/services/ecs"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/errmsgs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
    "github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
)




func resourceAlibabacloudStackEcsInvocation() *schema.Resource {
	resource := &schema.Resource{
		Schema: map[string]*schema.Schema{
            
			
			
				
					
						"command_id": {
	Type: schema.TypeString,
	Required: true,


},
					
				
			
				
					
						"create_time": {
	Type: schema.TypeString,
    Optional: true,
	Computed: true,


},
					
				
			
				
					
						"frequency": {
	Type: schema.TypeString,
    Optional: true,


},
					
				
			
				
					
						"instance_id": {
	Type: schema.TypeList,
	Required: true,


	
	Elem: &schema.Schema{
		Type:         schema.TypeString,
		Computed: true,
    },
	

},
					
				
			
				
					
						"invocation_id": {
	Type: schema.TypeString,
    Optional: true,


},
					
				
			
				
			
				
			
				
					
						"page_total": {
	Type: schema.TypeInt,
    Optional: true,
	Computed: true,


},
					
				
			
				
					
						"parameters": {
	Type: schema.TypeMap,
    Optional: true,


},
					
				
			
				
					
						"region_id": {
	Type: schema.TypeString,
	Required: true,


},
					
				
			
				
					
						"repeat_mode": {
	Type: schema.TypeString,
    Optional: true,
	Computed: true,


},
					
				
			
				
					
						"resource_type": {
	Type: schema.TypeString,
    Optional: true,


},
					
				
			
				
					
					"tags": tagsSchema(),
					
				
			
				
					
						"timed": {
	Type: schema.TypeBool,
    Optional: true,


},
					
				
			
				
					
						"username": {
	Type: schema.TypeString,
    Optional: true,


},
					
				
			
				
					
						"windows_password_name": {
	Type: schema.TypeString,
    Optional: true,


},
					
				
			
        },
	}
	setResourceFunc(resource, AlibabacloudStackEcsInvocationCreate,
		AlibabacloudStackEcsInvocationRead,
		AlibabacloudStackEcsInvocationUpdate,
		AlibabacloudStackEcsInvocationDelete,)
	return resource
}

func resourceAlibabacloudStackEcsInvocationCreate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	
	
		
		// api: Ecs - 2014-05-26 - InvokeCommand
        request := client.NewCommonRequest("POST", "Ecs", "2014-05-26", "InvokeCommand", "")
	    EcsInvokecommandResponseObj := EcsInvokecommandResponse{}

		
		
			
			
				//调用request_params_handler
    
        
        
    
        
        if v, ok := d.GetOk("command_id"); ok{
                request.QueryParams["CommandId"] = v.(string)
            } else {
                return fmt.Errorf("CommandId is required")
            }
        
    
        
    
        
        
    
        
        if v, ok := d.GetOk("frequency"); ok{
                request.QueryParams["Frequency"] = v.(string)
            }
        
    
        
    
        
        
    
        
        if v, ok := d.GetOk("parameters"); ok{
                request.QueryParams["Parameters"] = v.(string)
            }
        
    
        
    
        
        
    
        
        if v, ok := d.GetOk("region_id"); ok{
                request.QueryParams["RegionId"] = v.(string)
            } else {
                return fmt.Errorf("RegionId is required")
            }
        
    
        
    
        
        
    
        
        if v, ok := d.GetOk("timed"); ok{
                request.QueryParams["Timed"] = strconv.FormatBool(v.(bool))
            }
        
    
        
    
        
        
    
        
        if v, ok := d.GetOk("username"); ok{
                request.QueryParams["Username"] = v.(string)
            }
        
    
        
    
        
        
    
        
        if v, ok := d.GetOk("windows_password_name"); ok{
                request.QueryParams["WindowsPasswordName"] = v.(string)
            }
        
    
        
    
			
		


        bresponse, err :=client.ProcessCommonRequest(request)
        if err != nil {
            if bresponse == nil {
                return errmsgs.WrapErrorf(err, "Process Common Request Failed")
            }
            errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
            return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,  "alibabacloudstack_ecs_invocation", "InvokeCommand", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
        }

		
			err = json.Unmarshal(bresponse.GetHttpContentBytes(),&EcsInvokecommandResponseObj)
			if err != nil {
				return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg, 
					"alibabacloudstack_ecs_invocation", "InvokeCommand", errmsgs.AlibabacloudStackSdkGoERROR)
			}
		
	

	
			invocation_id := d.Get("invocation_id").(string)
	

	d.SetId(fmt.Sprintf("%s", invocation_id))
    return resourceAlibabacloudStackEcsInvocationUpdate(d, meta)

}

func resourceAlibabacloudStackEcsInvocationUpdate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	
		
		
		
				
				
				
					// InvocationId
					
				
					// RegionId
					
						
					
				
					// ResourceType
					
						
					
				
					// Tags
					
						
					
				
				
				
		

		
			// api: Ecs - 2014-05-26 - TagResources
			if d.HasChanges("region_id", "resource_type", "tags") {
			request := client.NewCommonRequest("POST", "Ecs", "2014-05-26", "TagResources", "")
			EcsTagresourcesResponseObj := EcsTagresourcesResponse{}

			
				
					
						
        
        if v, ok := d.GetOk("invocation_id"); ok{
                request.QueryParams["ResourceId[*]"] = v.(string)
            }
        
    
					
						
        
        if v, ok := d.GetOk("region_id"); ok{
                request.QueryParams["RegionId"] = v.(string)
            } else {
                return fmt.Errorf("RegionId is required")
            }
        
    
					
						
        
        if v, ok := d.GetOk("resource_type"); ok{
                request.QueryParams["ResourceType"] = v.(string)
            } else {
                return fmt.Errorf("ResourceType is required")
            }
        
    
					
						if v, ok := d.GetOk("tags"); ok{
            tagsList := v.([]interface{})
            tagsValues := make([]map[string]interface{}, 0)
            for _, item := range tagsList {
                itemMap := item.(map[string]interface{})
                item_data := make(map[string]interface{})
                
                    if v, ok := itemMap["tag_key"]; ok && v != "" {
                        item_data["Tag[*].Key"] = v.(string)
                    }
                    
                
                    if v, ok := itemMap["tag_value"]; ok && v != "" {
                        item_data["Tag[*].Value"] = v.(string)
                    }
                    
                
                tagsValues = append(tagsValues, item_data)
            }
            data, _ := json.Marshal(tagsValues)
            request.QueryParams["Tags"] = string(data)
        }
    
					
				
			
			bresponse, err :=client.ProcessCommonRequest(request)
			if err != nil {
				if bresponse == nil {
					return errmsgs.WrapErrorf(err, "Process Common Request Failed")
				}
				errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
				return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,  
					"alibabacloudstack_ecs_invocation", "TagResources", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
			}
			
				err = json.Unmarshal(bresponse.GetHttpContentBytes(), &EcsTagresourcesResponseObj)
				if err != nil {
					return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg, 
						"alibabacloudstack_ecs_invocation", "TagResources", errmsgs.AlibabacloudStackSdkGoERROR)
				}
			
			}
		
		
	
		
		
		
				
				
				
					// InvocationId
					
				
					// RegionId
					
						
					
				
					// ResourceType
					
						
					
				
					// Tags
					
						
					
				
				
				
		

		
			// api: Ecs - 2014-05-26 - UntagResources
			if d.HasChanges("region_id", "resource_type", "tags") {
			request := client.NewCommonRequest("POST", "Ecs", "2014-05-26", "UntagResources", "")
			EcsUntagresourcesResponseObj := EcsUntagresourcesResponse{}

			
				
					
						
        
        if v, ok := d.GetOk("invocation_id"); ok{
                request.QueryParams["ResourceId[*]"] = v.(string)
            }
        
    
					
						
        
        if v, ok := d.GetOk("region_id"); ok{
                request.QueryParams["RegionId"] = v.(string)
            } else {
                return fmt.Errorf("RegionId is required")
            }
        
    
					
						
        
        if v, ok := d.GetOk("resource_type"); ok{
                request.QueryParams["ResourceType"] = v.(string)
            } else {
                return fmt.Errorf("ResourceType is required")
            }
        
    
					
						if v, ok := d.GetOk("tags"); ok{
            tagsList := v.([]interface{})
            tagsValues := make([]map[string]interface{}, 0)
            for _, item := range tagsList {
                itemMap := item.(map[string]interface{})
                item_data := make(map[string]interface{})
                
                    if v, ok := itemMap["tag_key"]; ok && v != "" {
                        item_data["TagKey[*]"] = v.(string)
                    }
                    
                
                tagsValues = append(tagsValues, item_data)
            }
            data, _ := json.Marshal(tagsValues)
            request.QueryParams["Tags"] = string(data)
        }
    
					
				
			
			bresponse, err :=client.ProcessCommonRequest(request)
			if err != nil {
				if bresponse == nil {
					return errmsgs.WrapErrorf(err, "Process Common Request Failed")
				}
				errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
				return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,  
					"alibabacloudstack_ecs_invocation", "UntagResources", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
			}
			
				err = json.Unmarshal(bresponse.GetHttpContentBytes(), &EcsUntagresourcesResponseObj)
				if err != nil {
					return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg, 
						"alibabacloudstack_ecs_invocation", "UntagResources", errmsgs.AlibabacloudStackSdkGoERROR)
				}
			
			}
		
		
	
    return resourceAlibabacloudStackEcsInvocationRead(d, meta)
}


func resourceAlibabacloudStackEcsInvocationRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	ecsinvocationservice := 
EcsService{client}
	response, err := ecsinvocationservice.DoEcsDescribeinvocationresultsRequest(d, client)
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg, "alibabacloudstack_ecs_invocation", errmsgs.AlibabacloudStackSdkGoERROR)
	}
	data := response.Invocation.InvocationResults.InvocationResult[0]
	d.Set("command_id", data.CommandId)
	
	d.Set("create_time", data.StartTime)
	
	d.Set("invocation_id", data.InvokeId)
	
	d.Set("username", data.Username)
	
    return nil
}

func resourceAlibabacloudStackEcsInvocationDelete(d *schema.ResourceData, meta interface{}) error {
	return nil
}

type EcsInvokecommandResponse struct {InvokeId string `json:"InvokeId"`
RequestId string `json:"RequestId"`
}


type EcsTagresourcesResponse struct {RequestId string `json:"RequestId"`
}
type EcsUntagresourcesResponse struct {RequestId string `json:"RequestId"`
}



