package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product VPC Resouce DhcpOptionsSet
import (
	"encoding/json"
	"fmt"
	"slices"
	"strconv"

	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/errmsgs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func resourceAlibabacloudStackVpcDhcpoptionsset() *schema.Resource {
	resource := &schema.Resource{
		Schema: map[string]*schema.Schema{

			"all": {
				Type:     schema.TypeBool,
				Optional: true,
			},

			"associate_vpcs": {
				Type:     schema.TypeList,
				Optional: true,
				Computed: true,

				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{

						"associate_status": {
							Type:     schema.TypeString,
							Optional: true,
							Computed: true,
						},

						"vpc_id": {
							Type:     schema.TypeString,
							Required: true,
						},
					},
				},
			},

			"dhcp_options_set_description": {
				Type:     schema.TypeString,
				Optional: true,
			},

			"dhcp_options_set_id": {
				Type:     schema.TypeString,
				Optional: true,
			},

			"dhcp_options_set_name": {
				Type:     schema.TypeString,
				Optional: true,
			},

			"domain_name": {
				Type:     schema.TypeString,
				Optional: true,
			},

			"domain_name_servers": {
				Type:     schema.TypeString,
				Optional: true,
			},
			"resource_type": {
				Type:     schema.TypeString,
				Required: true,
			},

			"status": {
				Type:     schema.TypeString,
				Optional: true,
				Computed: true,
			},

			"tags": tagsSchema(),
		},
	}
	setResourceFunc(resource, resourceAlibabacloudStackVpcDhcpoptionssetCreate,
		resourceAlibabacloudStackVpcDhcpoptionssetRead,
		resourceAlibabacloudStackVpcDhcpoptionssetUpdate,
		resourceAlibabacloudStackVpcDhcpoptionssetDelete)
	return resource
}

func resourceAlibabacloudStackVpcDhcpoptionssetCreate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)

	// api: Vpc - 2016-04-28 - CreateDhcpOptionsSet
	request := client.NewCommonRequest("POST", "Vpc", "2016-04-28", "CreateDhcpOptionsSet", "")
	VpcCreatedhcpoptionssetResponseObj := VpcCreatedhcpoptionssetResponse{}

	if v, ok := d.GetOk("dhcp_options_set_description"); ok {
		request.QueryParams["DhcpOptionsSetDescription"] = v.(string)
	}

	if v, ok := d.GetOk("dhcp_options_set_name"); ok {
		request.QueryParams["DhcpOptionsSetName"] = v.(string)
	}

	if v, ok := d.GetOk("domain_name"); ok {
		request.QueryParams["DomainName"] = v.(string)
	}

	if v, ok := d.GetOk("domain_name_servers"); ok {
		request.QueryParams["DomainNameServers"] = v.(string)
	}

	bresponse, err := client.ProcessCommonRequest(request)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_vpc_dhcp_options_set", "CreateDhcpOptionsSet", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}

	err = json.Unmarshal(bresponse.GetHttpContentBytes(), &VpcCreatedhcpoptionssetResponseObj)
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
			"alibabacloudstack_vpc_dhcp_options_set", "CreateDhcpOptionsSet", errmsgs.AlibabacloudStackSdkGoERROR)
	}

	dhcp_options_set_id := VpcCreatedhcpoptionssetResponseObj.DhcpOptionsSetId

	d.SetId(fmt.Sprintf("%s", dhcp_options_set_id))
	return nil

}

func resourceAlibabacloudStackVpcDhcpoptionssetUpdate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	vpcService := VpcService{client}
	if d.HasChange("tags") {
		if err := vpcService.SetResourceTags(d, "vpc"); err != nil {
			return errmsgs.WrapError(err)
		}
	}

	if d.HasChanges("associate_vpcs") {
		old, new := d.GetChange("associate_vpcs")
		added := make([]string, 0)
		removed := make([]string, 0)
		for _, vpc := range old.([]string) {
			exists := slices.Contains(new.([]string), vpc)
			if !exists {
				removed = append(removed, vpc)
			}
		}
		for _, vpc := range new.([]string) {
			exists := slices.Contains(old.([]string), vpc)
			if !exists {
				added = append(added, vpc)
			}
		}

		add_request := client.NewCommonRequest("POST", "Vpc", "2016-04-28", "AttachDhcpOptionsSetToVpc", "")
		add_request.QueryParams["DhcpOptionsSetId"] = d.Id()
		for _, vpc := range added {
			add_request.QueryParams["VpcId"] = vpc
			bresponse, err := client.ProcessCommonRequest(add_request)
			if err != nil {
				if bresponse == nil {
					return errmsgs.WrapErrorf(err, "Process Common Request Failed")
				}
				errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
				return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,
					"alibabacloudstack_vpc_dhcp_options_set", "AttachDhcpOptionsSetToVpc", add_request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
			}

		}
		remove_request := client.NewCommonRequest("POST", "Vpc", "2016-04-28", "DetachDhcpOptionsSetFromVpc", "")
		remove_request.QueryParams["DhcpOptionsSetId"] = d.Id()
		for _, vpc := range removed {
			remove_request.QueryParams["VpcId"] = vpc
			bresponse, err := client.ProcessCommonRequest(remove_request)
			if err != nil {
				if bresponse == nil {
					return errmsgs.WrapErrorf(err, "Process Common Request Failed")
				}
				errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
				return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,
					"alibabacloudstack_vpc_dhcp_options_set", "DetachDhcpOptionsSetFromVpc", remove_request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
			}
		}

	}
	// DhcpOptionsSetId

	// RegionId

	// ResourceType

	// Tags

	// api: Vpc - 2016-04-28 - TagResources
	if d.HasChanges("region_id", "resource_type", "tags") {
		request := client.NewCommonRequest("POST", "Vpc", "2016-04-28", "TagResources", "")
		VpcTagresourcesResponseObj := VpcTagresourcesResponse{}

		if v, ok := d.GetOk("dhcp_options_set_id"); ok {
			request.QueryParams["ResourceId[*]"] = v.(string)
		}

		if v, ok := d.GetOk("region_id"); ok {
			request.QueryParams["RegionId"] = v.(string)
		} else {
			return fmt.Errorf("RegionId is required")
		}

		if v, ok := d.GetOk("resource_type"); ok {
			request.QueryParams["ResourceType"] = v.(string)
		} else {
			return fmt.Errorf("ResourceType is required")
		}

		if v, ok := d.GetOk("tags"); ok {
			tagsList := v.([]interface{})
			tagsValues := make([]map[string]interface{}, 0)
			for _, item := range tagsList {
				itemMap := item.(map[string]interface{})
				item_data := make(map[string]interface{})

				if v, ok := itemMap["tag_key"]; ok && v != "" {
					item_data["Tag[*].Key"] = v.(string)
				}

				if v, ok := itemMap["tag_value"]; ok && v != "" {
					item_data["Tag[*].Value"] = v.(string)
				}

				tagsValues = append(tagsValues, item_data)
			}
			data, _ := json.Marshal(tagsValues)
			request.QueryParams["Tags"] = string(data)
		}

		bresponse, err := client.ProcessCommonRequest(request)
		if err != nil {
			if bresponse == nil {
				return errmsgs.WrapErrorf(err, "Process Common Request Failed")
			}
			errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
			return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,
				"alibabacloudstack_vpc_dhcp_options_set", "TagResources", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
		}

		err = json.Unmarshal(bresponse.GetHttpContentBytes(), &VpcTagresourcesResponseObj)
		if err != nil {
			return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
				"alibabacloudstack_vpc_dhcp_options_set", "TagResources", errmsgs.AlibabacloudStackSdkGoERROR)
		}

	}

	// api: Vpc - 2016-04-28 - UpdateDhcpOptionsSetAttribute
	if d.HasChanges("dhcp_options_set_description", "dhcp_options_set_name", "domain_name", "domain_name_servers", "dry_run", "region_id") {
		request := client.NewCommonRequest("POST", "Vpc", "2016-04-28", "UpdateDhcpOptionsSetAttribute", "")
		VpcUpdatedhcpoptionssetattributeResponseObj := VpcUpdatedhcpoptionssetattributeResponse{}
		request.QueryParams["DhcpOptionsSetId"] = d.Id()
		if v, ok := d.GetOk("dhcp_options_set_description"); ok {
			request.QueryParams["DhcpOptionsSetDescription"] = v.(string)
		}

		if v, ok := d.GetOk("dhcp_options_set_name"); ok {
			request.QueryParams["DhcpOptionsSetName"] = v.(string)
		}

		if v, ok := d.GetOk("domain_name"); ok {
			request.QueryParams["DomainName"] = v.(string)
		}

		if v, ok := d.GetOk("domain_name_servers"); ok {
			request.QueryParams["DomainNameServers"] = v.(string)
		}

		bresponse, err := client.ProcessCommonRequest(request)
		if err != nil {
			if bresponse == nil {
				return errmsgs.WrapErrorf(err, "Process Common Request Failed")
			}
			errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
			return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,
				"alibabacloudstack_vpc_dhcp_options_set", "UpdateDhcpOptionsSetAttribute", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
		}

		err = json.Unmarshal(bresponse.GetHttpContentBytes(), &VpcUpdatedhcpoptionssetattributeResponseObj)
		if err != nil {
			return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
				"alibabacloudstack_vpc_dhcp_options_set", "UpdateDhcpOptionsSetAttribute", errmsgs.AlibabacloudStackSdkGoERROR)
		}

	}

	return nil
}

func resourceAlibabacloudStackVpcDhcpoptionssetRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	vpcdhcp_options_setservice := VpcService{client}
	response, err := vpcdhcp_options_setservice.DoVpcGetdhcpoptionssetRequest(d.Id())
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg, "alibabacloudstack_vpc_dhcpoptionsset", errmsgs.AlibabacloudStackSdkGoERROR)
	}
	data := response
	d.Set("dhcp_options_set_description", data.DhcpOptionsSetDescription)

	d.Set("dhcp_options_set_id", data.DhcpOptionsSetId)

	d.Set("dhcp_options_set_name", data.DhcpOptionsSetName)

	d.Set("domain_name", data.DhcpOptions.DomainName)

	d.Set("domain_name_servers", data.DhcpOptions.DomainNameServers)

	d.Set("owner_id", data.OwnerId)

	d.Set("status", data.Status)

	return nil
}

func resourceAlibabacloudStackVpcDhcpoptionssetDelete(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	// api: Vpc - 2016-04-28 - DeleteDhcpOptionsSet
	request := client.NewCommonRequest("POST", "Vpc", "2016-04-28", "DeleteDhcpOptionsSet", "")
	VpcDeletedhcpoptionssetResponseObj := VpcDeletedhcpoptionssetResponse{}

	//调用request_params_handler

	if v, ok := d.GetOk("dhcp_options_set_id"); ok {
		request.QueryParams["DhcpOptionsSetId"] = v.(string)
	} else {
		return fmt.Errorf("DhcpOptionsSetId is required")
	}

	if v, ok := d.GetOk("dry_run"); ok {
		request.QueryParams["DryRun"] = strconv.FormatBool(v.(bool))
	}

	if v, ok := d.GetOk("region_id"); ok {
		request.QueryParams["RegionId"] = v.(string)
	} else {
		return fmt.Errorf("RegionId is required")
	}

	bresponse, err := client.ProcessCommonRequest(request)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_vpc_dhcp_options_set", "DeleteDhcpOptionsSet", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}

	err = json.Unmarshal(bresponse.GetHttpContentBytes(), &VpcDeletedhcpoptionssetResponseObj)
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
			"alibabacloudstack_vpc_dhcp_options_set", "DeleteDhcpOptionsSet", errmsgs.AlibabacloudStackSdkGoERROR)
	}

	return nil
}

type VpcCreatedhcpoptionssetResponse struct {
	RequestId        string `json:"RequestId"`
	DhcpOptionsSetId string `json:"DhcpOptionsSetId"`
}

type VpcAttachdhcpoptionssettovpcResponse struct {
	RequestId string `json:"RequestId"`
}
type VpcDetachdhcpoptionssetfromvpcResponse struct {
	RequestId string `json:"RequestId"`
}
type VpcMoveresourcegroupResponse struct {
	RequestId string `json:"RequestId"`
}
type VpcReplacevpcdhcpoptionssetResponse struct {
	RequestId string `json:"RequestId"`
}
type VpcTagresourcesResponse struct {
	RequestId string `json:"RequestId"`
}
type VpcUntagresourcesResponse struct {
	RequestId string `json:"RequestId"`
}
type VpcUpdatedhcpoptionssetattributeResponse struct {
	RequestId string `json:"RequestId"`
}

type VpcDeletedhcpoptionssetResponse struct {
	RequestId string `json:"RequestId"`
}
