package alibabacloudstack

// Generated By apsara-orchestration-generator
// Product EBS Resouce DiskReplicaPair
import (
	"encoding/json"
	"fmt"
	"strconv"
	"time"

	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/connectivity"
	"github.com/aliyun/terraform-provider-alibabacloudstack/alibabacloudstack/errmsgs"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func resourceAlibabacloudStackEbsDiskreplicapair() *schema.Resource {
	resource := &schema.Resource{
		Schema: map[string]*schema.Schema{

			// "bandwidth": {
			// 	Type:     schema.TypeInt,
			// 	Optional: true,
			// 	Computed: true,
			// },
			// In the environment testing phase, attribute setting and modification are invalid

			"description": {
				Type:     schema.TypeString,
				Optional: true,
			},

			"destination_disk_id": {
				Type:     schema.TypeString,
				Required: true,
			},

			"destination_region_id": {
				Type:     schema.TypeString,
				Required: true,
			},

			"destination_zone_id": {
				Type:     schema.TypeString,
				Required: true,
			},

			"source_disk_id": {
				Type:     schema.TypeString,
				Required: true,
			},

			"disk_replica_pair_name": {
				Type:     schema.TypeString,
				Optional: true,
			},

			"last_recover_point": {
				Type:     schema.TypeInt,
				Optional: true,
				Computed: true,
			},

			"one_shot": {
				Type:     schema.TypeBool,
				Optional: true,
			},

			"rpo": {
				Type:     schema.TypeInt,
				Optional: true,
			},

			"source_region_id": {
				Type:     schema.TypeString,
				Required: true,
			},

			"replica_group_id": {
				Type:     schema.TypeString,
				Optional: true,
			},

			"source_zone_id": {
				Type:     schema.TypeString,
				Required: true,
			},

			"replica_pair_id":{
				Type:     schema.TypeString,
				Computed: true,
			},
			
			"create_time": {
			  Type:         schema.TypeString,
			  Computed: true,
			},
			
			"status": {
				Type:     schema.TypeString,
				Optional: true,
				Computed: true,
			},

			// TODO: ResourceMeta defines this attribute, but no related API is defined
			//"tags": tagsSchema(),
		},
	}
	setResourceFunc(resource, resourceAlibabacloudStackEbsDiskreplicapairCreate,
		resourceAlibabacloudStackEbsDiskreplicapairRead,
		resourceAlibabacloudStackEbsDiskreplicapairUpdate,
		resourceAlibabacloudStackEbsDiskreplicapairDelete)
	return resource
}

func resourceAlibabacloudStackEbsDiskreplicapairCreate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)

	// api: ebs - 2021-07-30 - CreateDiskReplicaPair
	request := client.NewCommonRequest("POST", "ebs", "2021-07-30", "CreateDiskReplicaPair", "")
	EbsCreatediskreplicapairResponse := EbsCreatediskreplicapairResponse{}

	// Call request_params_handler

	// if v, ok := d.GetOk("bandwidth"); ok {
	// 	request.QueryParams["Bandwidth"] = strconv.Itoa(v.(int))
	// }

	if v, ok := d.GetOk("description"); ok {
		request.QueryParams["Description"] = v.(string)
	}

	if v, ok := d.GetOk("destination_disk_id"); ok {
		request.QueryParams["DestinationDiskId"] = v.(string)
	} else {
		return fmt.Errorf("DestinationDiskId is required")
	}

	if v, ok := d.GetOk("destination_region_id"); ok {
		request.QueryParams["DestinationRegionId"] = v.(string)
	} else {
		return fmt.Errorf("DestinationRegionId is required")
	}

	if v, ok := d.GetOk("destination_zone_id"); ok {
		request.QueryParams["DestinationZoneId"] = v.(string)
	} else {
		return fmt.Errorf("DestinationZoneId is required")
	}

	if v, ok := d.GetOk("source_disk_id"); ok {
		request.QueryParams["DiskId"] = v.(string)
	} else {
		return fmt.Errorf("DiskId is required")
	}

	if v, ok := d.GetOk("disk_replica_pair_name"); ok {
		request.QueryParams["PairName"] = v.(string)
	}

	if v, ok := d.GetOk("rpo"); ok {
		request.QueryParams["RPO"] = strconv.Itoa(v.(int))
	}

	if v, ok := d.GetOk("source_region_id"); ok {
		request.QueryParams["RegionId"] = v.(string)
	} else {
		return fmt.Errorf("RegionId is required")
	}

	if v, ok := d.GetOk("source_zone_id"); ok {
		request.QueryParams["SourceZoneId"] = v.(string)
	} else {
		return fmt.Errorf("SourceZoneId is required")
	}

	bresponse, err := client.ProcessCommonRequest(request)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_ebs_disk_replica_pair", "CreateDiskReplicaPair", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}

	err = json.Unmarshal(bresponse.GetHttpContentBytes(), &EbsCreatediskreplicapairResponse)
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
			"alibabacloudstack_ebs_disk_replica_pair", "CreateDiskReplicaPair", errmsgs.AlibabacloudStackSdkGoERROR)
	}

	replica_pair_id := EbsCreatediskreplicapairResponse.ReplicaPairId

	d.SetId(fmt.Sprintf("%s", replica_pair_id))
	ebsdisk_replica_groupservice := EbsService{client}
	stateConf := BuildStateConf([]string{"creating"}, []string{"created"}, d.Timeout(schema.TimeoutCreate), 10*time.Second, ebsdisk_replica_groupservice.EbsDiskreplicapairStatusRefreshFunc(d.Id(), []string{"failed"}))

	if _, err := stateConf.WaitForState(); err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.IdMsg, d.Id())
	}
	return nil

}

func resourceAlibabacloudStackEbsDiskreplicapairUpdate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)

	// RegionId

	// ReplicaPairId

	// api: ebs - 2021-07-30 - FailoverDiskReplicaPair
	// if d.HasChanges("source_region_id") {
	// 	request := client.NewCommonRequest("POST", "ebs", "2021-07-30", "FailoverDiskReplicaPair", "")
	// 	EbsFailoverdiskreplicapairResponse := EbsFailoverdiskreplicapairResponse{}
	// 	request.QueryParams["ReplicaPairId"] = d.Id()
	// 	if v, ok := d.GetOk("source_region_id"); ok {
	// 		request.QueryParams["RegionId"] = v.(string)
	// 	} else {
	// 		return fmt.Errorf("RegionId is required")
	// 	}

	// 	bresponse, err := client.ProcessCommonRequest(request)
	// 	if err != nil {
	// 		if bresponse == nil {
	// 			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
	// 		}
	// 		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
	// 		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,
	// 			"alibabacloudstack_ebs_disk_replica_pair", "FailoverDiskReplicaPair", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	// 	}

	// 	err = json.Unmarshal(bresponse.GetHttpContentBytes(), &EbsFailoverdiskreplicapairResponse)
	// 	if err != nil {
	// 		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
	// 			"alibabacloudstack_ebs_disk_replica_pair", "FailoverDiskReplicaPair", errmsgs.AlibabacloudStackSdkGoERROR)
	// 	}

	// }

	// Description

	// DiskReplicaPairName

	// RegionId

	// ReplicaPairId

	// api: ebs - 2021-07-30 - ModifyDiskReplicaPair
	if d.HasChanges("description", "disk_replica_pair_name", "rpo") {
		request := client.NewCommonRequest("POST", "ebs", "2021-07-30", "ModifyDiskReplicaPair", "")
		EbsModifydiskreplicapairResponse := EbsModifydiskreplicapairResponse{}
		request.QueryParams["ReplicaPairId"] = d.Id()
		if v, ok := d.GetOk("description"); ok {
			request.QueryParams["Description"] = v.(string)
		}

		if v, ok := d.GetOk("disk_replica_pair_name"); ok {
			request.QueryParams["PairName"] = v.(string)
		}

		if v, ok := d.GetOk("rpo"); ok {
			request.QueryParams["RPO"] = strconv.Itoa(v.(int))

		}

		bresponse, err := client.ProcessCommonRequest(request)
		if err != nil {
			if bresponse == nil {
				return errmsgs.WrapErrorf(err, "Process Common Request Failed")
			}
			errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
			return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,
				"alibabacloudstack_ebs_disk_replica_pair", "ModifyDiskReplicaPair", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
		}

		err = json.Unmarshal(bresponse.GetHttpContentBytes(), &EbsModifydiskreplicapairResponse)
		if err != nil {
			return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
				"alibabacloudstack_ebs_disk_replica_pair", "ModifyDiskReplicaPair", errmsgs.AlibabacloudStackSdkGoERROR)
		}

	}

	// RegionId

	// ReplicaPairId

	// api: ebs - 2021-07-30 - ReprotectDiskReplicaPair
	// if d.HasChanges("source_region_id") {
	// 	request := client.NewCommonRequest("POST", "ebs", "2021-07-30", "ReprotectDiskReplicaPair", "")
	// 	EbsReprotectdiskreplicapairResponse := EbsReprotectdiskreplicapairResponse{}
	//	request.QueryParams["ReplicaPairId"] = d.Id()
	// 	if v, ok := d.GetOk("source_region_id"); ok {
	// 		request.QueryParams["RegionId"] = v.(string)
	// 	} else {
	// 		return fmt.Errorf("RegionId is required")
	// 	}

	// 	bresponse, err := client.ProcessCommonRequest(request)
	// 	if err != nil {
	// 		if bresponse == nil {
	// 			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
	// 		}
	// 		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
	// 		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,
	// 			"alibabacloudstack_ebs_disk_replica_pair", "ReprotectDiskReplicaPair", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	// 	}

	// 	err = json.Unmarshal(bresponse.GetHttpContentBytes(), &EbsReprotectdiskreplicapairResponse)
	// 	if err != nil {
	// 		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
	// 			"alibabacloudstack_ebs_disk_replica_pair", "ReprotectDiskReplicaPair", errmsgs.AlibabacloudStackSdkGoERROR)
	// 	}

	// }

	// // OneShot

	// // RegionId

	// // ReplicaPairId

	// // api: ebs - 2021-07-30 - StartDiskReplicaPair
	// if d.HasChanges("one_shot", "source_region_id") {
	// 	request := client.NewCommonRequest("POST", "ebs", "2021-07-30", "StartDiskReplicaPair", "")
	// 	EbsStartdiskreplicapairResponse := EbsStartdiskreplicapairResponse{}
	//  request.QueryParams["ReplicaPairId"] = d.Id()
	// 	if v, ok := d.GetOk("one_shot"); ok {
	// 		request.QueryParams["OneShot"] = strconv.FormatBool(v.(bool))
	// 	}

	// 	if v, ok := d.GetOk("source_region_id"); ok {
	// 		request.QueryParams["RegionId"] = v.(string)
	// 	} else {
	// 		return fmt.Errorf("RegionId is required")
	// 	}
	// 	bresponse, err := client.ProcessCommonRequest(request)
	// 	if err != nil {
	// 		if bresponse == nil {
	// 			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
	// 		}
	// 		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
	// 		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,
	// 			"alibabacloudstack_ebs_disk_replica_pair", "StartDiskReplicaPair", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	// 	}

	// 	err = json.Unmarshal(bresponse.GetHttpContentBytes(), &EbsStartdiskreplicapairResponse)
	// 	if err != nil {
	// 		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
	// 			"alibabacloudstack_ebs_disk_replica_pair", "StartDiskReplicaPair", errmsgs.AlibabacloudStackSdkGoERROR)
	// 	}

	// }

	// // RegionId

	// // ReplicaPairId

	// // api: ebs - 2021-07-30 - StopDiskReplicaPair
	// if d.HasChanges("source_region_id") {
	// 	request := client.NewCommonRequest("POST", "ebs", "2021-07-30", "StopDiskReplicaPair", "")
	// 	EbsStopdiskreplicapairResponse := EbsStopdiskreplicapairResponse{}
	//  request.QueryParams["ReplicaPairId"] = d.Id()
	// 	if v, ok := d.GetOk("source_region_id"); ok {
	// 		request.QueryParams["RegionId"] = v.(string)
	// 	} else {
	// 		return fmt.Errorf("RegionId is required")
	// 	}

	// 	bresponse, err := client.ProcessCommonRequest(request)
	// 	if err != nil {
	// 		if bresponse == nil {
	// 			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
	// 		}
	// 		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
	// 		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg,
	// 			"alibabacloudstack_ebs_disk_replica_pair", "StopDiskReplicaPair", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	// 	}

	// 	err = json.Unmarshal(bresponse.GetHttpContentBytes(), &EbsStopdiskreplicapairResponse)
	// 	if err != nil {
	// 		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg,
	// 			"alibabacloudstack_ebs_disk_replica_pair", "StopDiskReplicaPair", errmsgs.AlibabacloudStackSdkGoERROR)
	// 	}

	// }

	return nil
}

func resourceAlibabacloudStackEbsDiskreplicapairRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	ebsdisk_replica_pairservice := EbsService{client}
	replicapair, err := ebsdisk_replica_pairservice.Describediskreplicapairs(d.Id())
	if err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.DefaultErrorMsg, "alibabacloudstack_ebs_diskreplicapair", errmsgs.AlibabacloudStackSdkGoERROR)
	}
	// d.Set("bandwidth", replicapair.Bandwidth)

	d.Set("replica_pair_id", replicapair.ReplicaPairId)

	d.Set("description", replicapair.Description)

	d.Set("destination_disk_id", replicapair.DestinationDiskId)

	d.Set("destination_region_id", replicapair.DestinationRegion)

	d.Set("destination_zone_id", replicapair.DestinationZoneId)

	d.Set("source_disk_id", replicapair.SourceDiskId)

	d.Set("disk_replica_pair_name", replicapair.PairName)

	d.Set("last_recover_point", replicapair.LastRecoverPoint)

	d.Set("rpo", replicapair.RPO)

	d.Set("source_region_id", replicapair.SourceRegion)

	d.Set("source_zone_id", replicapair.SourceZoneId)

	d.Set("status", replicapair.Status)
	
	utcTime := time.Unix(replicapair.CreateTime, 0).UTC()
	d.Set("create_time", utcTime.Format("2006-01-02T15:04:05-07:00"))

	return nil
}

func resourceAlibabacloudStackEbsDiskreplicapairDelete(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*connectivity.AlibabacloudStackClient)
	// api: ebs - 2021-07-30 - DeleteDiskReplicaPair
	request := client.NewCommonRequest("POST", "ebs", "2021-07-30", "DeleteDiskReplicaPair", "")
	request.QueryParams["ReplicaPairId"] = d.Id()
	bresponse, err := client.ProcessCommonRequest(request)
	if err != nil {
		if bresponse == nil {
			return errmsgs.WrapErrorf(err, "Process Common Request Failed")
		}
		errmsg := errmsgs.GetBaseResponseErrorMessage(bresponse.BaseResponse)
		return errmsgs.WrapErrorf(err, errmsgs.RequestV1ErrorMsg, "alibabacloudstack_ebs_disk_replica_pair", "DeleteDiskReplicaPair", request.GetActionName(), errmsgs.AlibabacloudStackSdkGoERROR, errmsg)
	}
	ebsdisk_replica_groupservice := EbsService{client}
	stateConf := BuildStateConf([]string{"deleting"}, []string{}, d.Timeout(schema.TimeoutCreate), 10*time.Second, ebsdisk_replica_groupservice.EbsDiskreplicapairStatusRefreshFunc(d.Id(), []string{"failed"}))
	
	if _, err := stateConf.WaitForState(); err != nil {
		return errmsgs.WrapErrorf(err, errmsgs.IdMsg, d.Id())
	}

	return nil
}

type EbsCreatediskreplicapairResponse struct {
	RequestId     string `json:"RequestId"`
	ReplicaPairId string `json:"ReplicaPairId"`
	OrderId       string `json:"OrderId"`
}

type EbsFailoverdiskreplicapairResponse struct {
	RequestId string `json:"RequestId"`
}
type EbsModifydiskreplicapairResponse struct {
	RequestId string `json:"RequestId"`
}
type EbsReprotectdiskreplicapairResponse struct {
	RequestId string `json:"RequestId"`
}
type EbsStartdiskreplicapairResponse struct {
	RequestId string `json:"RequestId"`
}
type EbsStopdiskreplicapairResponse struct {
	RequestId string `json:"RequestId"`
}

type EbsDeletediskreplicapairResponse struct {
	RequestId string `json:"RequestId"`
}
